const letterZ = [
  { name: "Z-Zip", code: "#CBC5B6" },
  { name: "Zachary", code: "#D3A18E" },
  { name: "Zacho Blue", code: "#8FBDD2" },
  { name: "Zadar", code: "#85AAAB" },
  { name: "Zaddick", code: "#8CBEDD" },
  { name: "Zaffer", code: "#29AEB4" },
  { name: "Zaffre", code: "#0014A8" },
  { name: "Zaffre (Samson)", code: "#2D5455" },
  { name: "Zagreb LP-300", code: "#E8DEB0" },
  { name: "Zahara Brown", code: "#77523B" },
  { name: "Zahria", code: "#FFE8C2" },
  { name: "Zaire", code: "#354949" },
  { name: "Zambesi", code: "#303B34" },
  { name: "Zambeze Plains", code: "#49473E" },
  { name: "Zambezi", code: "#685558" },
  { name: "Zambia", code: "#FF9215" },
  { name: "Zamboni", code: "#ECF1EF" },
  { name: "Zanadu", code: "#96B9D9" },
  { name: "Zanah", code: "#DAECD6" },
  { name: "Zane Gray", code: "#5F676E" },
  { name: "Zany Lime", code: "#E8B849" },
  { name: "Zany Pink", code: "#E37284" },
  { name: "Zanzibar", code: "#A7867B" },
  { name: "Zanzibar Brown", code: "#5C453F" },
  { name: "Zanzibar Coast", code: "#6E413C" },
  { name: "Zanzibar Gold", code: "#B58548" },
  { name: "Zanzibar Retreat", code: "#D0AE00" },
  { name: "Zanzibar Spice", code: "#8E7364" },
  { name: "Zappa", code: "#8A8E7D" },
  { name: "Zappo", code: "#C4C0E2" },
  { name: "Zara", code: "#B48784" },
  { name: "Zay Day", code: "#DBD5C2" },
  { name: "Zealand Green", code: "#8DD59F" },
  { name: "Zealander Pine", code: "#DBEEDA" },
  { name: "Zealous", code: "#5AC9CB" },
  { name: "Zealot", code: "#007473" },
  { name: "Zebra Agate", code: "#907366" },
  { name: "Zebra Finch", code: "#CEC5BA" },
  { name: "Zebra Grass", code: "#9C9C82" },
  { name: "Zebra Print Dress", code: "#A38A83" },
  { name: "Zebrano", code: "#BC875D" },
  { name: "Zebulon", code: "#378F85" },
  { name: "Zelia", code: "#D5C0C8" },
  { name: "Zellwood", code: "#764C39" },
  { name: "Zemo's Way", code: "#967667" },
  { name: "Zen", code: "#D2D0AE" },
  { name: "Zen Blue", code: "#A7BBD0" },
  { name: "Zen Commandment", code: "#D5D3C3" },
  { name: "Zen Essence", code: "#C7BEA7" },
  { name: "Zen Garden", code: "#C7CFA2" },
  { name: "Zen Retreat", code: "#5A5A59" },
  { name: "Zenda", code: "#5C5D6B" },
  { name: "Zenful", code: "#DDDACC" },
  { name: "Zenith", code: "#95B9E1" },
  { name: "Zentury Brown", code: "#A14F34" },
  { name: "Zepher", code: "#87967B" },
  { name: "Zephyr", code: "#CE94B5" },
  { name: "Zephyr Blue", code: "#CFDFE6" },
  { name: "Zephyr Green", code: "#83AC82" },
  { name: "Zephyr Hills", code: "#D8D5CC" },
  { name: "Zeppelin", code: "#382A34" },
  { name: "Zermatt White", code: "#DFDBD1" },
  { name: "Zero", code: "#FFDAE2" },
  { name: "Zero Gravity", code: "#BFC4C4" },
  { name: "Zest", code: "#E5841B" },
  { name: "Zest (Eddie Bauer)", code: "#FBDC9A" },
  { name: "Zest (Martha Stewart)", code: "#D47A2A" },
  { name: "Zestful", code: "#94B67F" },
  { name: "Zesty (ICI)", code: "#E6D66D" },
  { name: "Zesty (True Value)", code: "#BA4D3C" },
  { name: "Zesty Apple", code: "#8FA15C" },
  { name: "Zesty Custard", code: "#FFEA8E" },
  { name: "Zesty Lilac", code: "#D7CDE7" },
  { name: "Zesty Lime", code: "#9DA61A" },
  { name: "Zeus", code: "#292319" },
  { name: "Zeus (Ace)", code: "#9E8665" },
  { name: "Zeus Shadow", code: "#855466" },
  { name: "Zeus Temple", code: "#659ACE" },
  { name: "Zibibbo", code: "#51242B" },
  { name: "Ziggurat", code: "#BFDBE2" },
  { name: "Zigzag", code: "#B77149" },
  { name: "Zimbabwe Plains", code: "#888C84" },
  { name: "Zimidar", code: "#645688" },
  { name: "Zin Cluster", code: "#463A39" },
  { name: "Zinc", code: "#919798" },
  { name: "Zinc Blue", code: "#869890" },
  { name: "Zinc Green", code: "#376A64" },
  { name: "Zinc Pink", code: "#F2D7DD" },
  { name: "Zinc White", code: "#E1DBD0" },
  { name: "Zinc-ed", code: "#68706E" },
  { name: "Zinfandel (ICI)", code: "#D5C0B6" },
  { name: "Zing", code: "#E4CB72" },
  { name: "Zinger", code: "#873D42" },
  { name: "Zingy!", code: "#E2CC5E" },
  { name: "Zinnia", code: "#9C6560" },
  { name: "Zinnia Bloom", code: "#C07CA5" },
  { name: "Zinnia Gold", code: "#FFCE76" },
  { name: "Zinnia Scarlet", code: "#FF8696" },
  { name: "Zinnia Yellow", code: "#FFC000" },
  { name: "Zinnwaldite", code: "#EBC2AF" },
  { name: "Zinnwaldite Brown", code: "#2C1608" },
  { name: "Zip Line", code: "#81A599" },
  { name: "Zipline Green", code: "#7A7E63" },
  { name: "Zippered Gray", code: "#B0B5B9" },
  { name: "Zippidy Doo Dah", code: "#E3E6BF" },
  { name: "Zippy Gold", code: "#FAB836" },
  { name: "Zippy Lavender", code: "#C3A1AD" },
  { name: "Zircon", code: "#F4F8FF" },
  { name: "Zirconia Teal", code: "#197576" },
  { name: "Zither", code: "#755A87" },
  { name: "Zoboba", code: "#CC9966" },
  { name: "Zodiac", code: "#413A5D" },
  { name: "Zodiac Blue", code: "#37849E" },
  { name: "Zodiac Gray", code: "#857D7F" },
  { name: "Zodiac Night (ICI)", code: "#006E65" },
  { name: "Zoe", code: "#5C2C3C" },
  { name: "Zoey Island", code: "#C086B0" },
  { name: "Zokine", code: "#43523C" },
  { name: "Zombie", code: "#E4D69B" },
  { name: "Zombie Green", code: "#879E4E" },
  { name: "Zomp", code: "#39A78E" },
  { name: "Zonda Grey", code: "#797372" },
  { name: "Zone grey", code: "#767E80" },
  { name: "Zoom", code: "#47B1B7" },
  { name: "Zora", code: "#FFCA42" },
  { name: "Zobra", code: "#A59B91" },
  { name: "Zoraya Blue", code: "#BCD1D1" },
  { name: "Zorro", code: "#2D3033" },
  { name: "Zucchini (Dulux)", code: "#D3D3BC" },
  { name: "Zucchini Flower", code: "#E79F4D" },
  { name: "Zuccini", code: "#044022" },
  { name: "Zuider Zee", code: "#72C1C4" },
  { name: "Zuli", code: "#656264" },
  { name: "Zulu", code: "#585156" },
  { name: "Zumthor", code: "#EDF6FF" },
  { name: "Zuni Mist", code: "#E1F1E7" },
  { name: "Zuni Turquoise", code: "#06AD8B" },
  { name: "Zunisha", code: "#899BA9" },
  { name: "Zunza", code: "#BFD1BC" },
  { name: "Zurich White", code: "#E7E2DA" },
  { name: "Zutem", code: "#D4AA25" },
];

const letterY = [
  { name: "Yabbada bbadoo", code: "#008B97" },
  { name: "Yachting", code: "#2A5A6E" },
  { name: "Yacht Club Lounge", code: "#597B8C" },
  { name: "Yachting Cat", code: "#3D526A" },
  { name: "Yachtsman", code: "#AAB3B2" },
  { name: "Yaffle Green", code: "#D4CD7C" },
  { name: "Yahoo", code: "#E9D5CC" },
  { name: "Yahoo Gold", code: "#EBB742" },
  { name: "Yak (Siko)", code: "#564337" },
  { name: "Yak Skin", code: "#D5BFB4" },
  { name: "Yale", code: "#80BBDD" },
  { name: "Yale Blue", code: "#0F4D92" },
  { name: "Yam", code: "#CC6600" },
  { name: "Yam (Pantone)", code: "#D2853D" },
  { name: "Yama", code: "#95AEA1" },
  { name: "Yama Light", code: "#48BFA8" },
  { name: "Yamabuki-iro", code: "#FFA400" },
  { name: "Yamabukicha", code: "#CB7E1F" },
  { name: "Yams", code: "#E08A4F" },
  { name: "Yanagicha", code: "#9C8A4D" },
  { name: "Yanagi nezumi", code: "#817B69" },
  { name: "Yanagi susutake", code: "#4D4B3A" },
  { name: "Yanagizome", code: "#8C9E5E" },
  { name: "Yanez", code: "#9A8873" },
  { name: "Yankee", code: "#A1703F" },
  { name: "Yankee Doodle", code: "#4D5D6C" },
  { name: "Yankees Blue", code: "#1C2841" },
  { name: "Yaquil Trail", code: "#C48178" },
  { name: "Yarborough Yellow", code: "#F6DC79" },
  { name: "Yardbird", code: "#DCE7E9" },
  { name: "Yardline", code: "#60BB75" },
  { name: "Yare", code: "#6A81AC" },
  { name: "Yarmouth Gray", code: "#8C8D8D" },
  { name: "Yarmouth Oyster", code: "#DBCCB4" },
  { name: "Yarn (Magnolia)", code: "#CECBC3" },
  { name: "Yarn (Kilz)", code: "#D2CDC4" },
  { name: "Yarrow Blossom", code: "#E8C089" },
  { name: "Yarrow Point", code: "#DCA25C" },
  { name: "Yarrow White", code: "#F3E1BE" },
  { name: "Yasna", code: "#544A50" },
  { name: "Yazoo City Yellow", code: "#FFDE5A" },
  { name: "Yeah Baby", code: "#B3E1EA" },
  { name: "Yearling", code: "#A9896F" },
  { name: "Yearling Peach", code: "#F9CC8C" },
  { name: "Yearning", code: "#CDE8FF" },
  { name: "Yeehaa", code: "#006C98" },
  { name: "Yellow", code: "#FFFF00" },
  { name: "Yellow (Ĉ)", code: "#FCE883" },
  { name: "Yellow (Munsell)", code: "#EFCC00" },
  { name: "Yellow (NCS)", code: "#FFD300" },
  { name: "Yellow (Pantone)", code: "#FEDF00" },
  { name: "Yellow (Process)", code: "#FFEF00" },
  { name: "Yellow (RYB)", code: "#FEFE33" },
  { name: "Yellow Beige", code: "#E3C08D" },
  { name: "Yellow Bouquet", code: "#EFC98F" },
  { name: "Yellow Brick Road", code: "#FFDE81" },
  { name: "Yellow Brown", code: "#BFA785" },
  { name: "Yellow Duckling", code: "#FBE9B5" },
  { name: "Yellow Fauna", code: "#E1CE94" },
  { name: "Yellow Fervor", code: "#FFC04F" },
  { name: "Yellow Grass", code: "#D8D89E" },
  { name: "Yellow Green", code: "#C5E17A" },
  { name: "Yellow green (RAL)", code: "#48A43F" },
  { name: "Yellow Grey", code: "#939176" },
  { name: "Yellow Jacket", code: "#FBC923" },
  { name: "Yellow Jessamine", code: "#FCE8BF" },
  { name: "Yellow Kerchief", code: "#EFC239" },
  { name: "Yellow Metal", code: "#716338" },
  { name: "Yellow Ochre", code: "#C6AE4E" },
  { name: "Yellow Olive", code: "#444337" },
  { name: "Yellow Orange (RAL)", code: "#FFAE42" },
  { name: "Yellow Orange", code: "#DD7907" },
  { name: "Yellow Rose", code: "#FFF000" },
  { name: "Yellow Sea", code: "#FEA904" },
  { name: "Yellow Stone", code: "#F0D390" },
  { name: "Yellow Submarine", code: "#E8D233" },
  { name: "Yellow Sunshine", code: "#FFF700" },
  { name: "Yellow Yarn", code: "#F9EBB7" },
  { name: "Yellow-Green", code: "#9ACD32" },
  { name: "Yellowbelly", code: "#FBCB72" },
  { name: "Yellowish Green", code: "#7FBF00" },
  { name: "Yellowstone", code: "#9A7452" },
  { name: "Yellowstone Gorge", code: "#C0A786" },
  { name: "Yellowtail", code: "#F7E7B4" },
  { name: "Yen", code: "#333333" },
  { name: "Yen Blue", code: "#000033" },
  { name: "Yen Green", code: "#003300" },
  { name: "Yen Magenta", code: "#330033" },
  { name: "Yen Red", code: "#330000" },
  { name: "Yen Yellow", code: "#333300" },
  { name: "Yen Mickey!", code: "#516F45" },
  { name: "Yesterday", code: "#EFEEEC" },
  { name: "Yesterday's Roses", code: "#D0BCC3" },
  { name: "Yew", code: "#475954" },
  { name: "Yew Green (Benjamin Moore)", code: "#D0C300" },
  { name: "Yew Green (Fuller Obrien)", code: "#ABAD91" },
  { name: "Yield", code: "#FFC22C" },
  { name: "Yin Yang", code: "#6483A4" },
  { name: "Ying Yang", code: "#DADCBE" },
  { name: "Yo-Yo", code: "#EC8A4A" },
  { name: "Yoga Strength", code: "#DBE0C8" },
  { name: "Yolk Yellow", code: "#E4A84C" },
  { name: "York Town", code: "#879AC5" },
  { name: "Yorkshire Teal", code: "#507372" },
  { name: "Yosemite Campfire", code: "#ED4C44" },
  { name: "Yosemite Springs", code: "#B3D6D5" },
  { name: "You Look Mauve-lous", code: "#B0A9AE" },
  { name: "Young Mermaid", code: "#7B7D5F" },
  { name: "Young Shoot", code: "#FFFFB2" },
  { name: "Your Highness", code: "#B0AEC0" },
  { name: "Your Pink", code: "#FFC3C0" },
  { name: "Your Sanctuary", code: "#D9CDC9" },
  { name: "Your Shadow", code: "#717C8E" },
  { name: "Yours Truly", code: "#F1D4CE" },
  { name: "Youth White", code: "#AACDB3" },
  { name: "Yucatan", code: "#00A0C7" },
  { name: "Yucca", code: "#68786B" },
  { name: "Yucca White", code: "#EDEBD4" },
  { name: "Yukon Gold", code: "#7B6608" },
  { name: "Yukon Gold (Do It Best)", code: "#ECD6AB" },
  { name: "Yukon Sky", code: "#94B2BB" },
  { name: "Yuletime", code: "#95CE96" },
  { name: "Yum Yum Yellow", code: "#F8DF89" },
  { name: "Yuma", code: "#CEC291" },
  { name: "Yuma Gold", code: "#FFC972" },
  { name: "Yuma Sand", code: "#FBF0CF" },
  { name: "Yuma Plummy", code: "#9F7980" },
];

const letterX = [
  { name: "X Factor", code: "#681B2B" },
  { name: "X-23", code: "#966E61" },
  { name: "X-23 Apricot", code: "#FEB36F" },
  { name: "X-23 Aspen", code: "#DDCFC1" },
  { name: "X-23-2 Passion Flower", code: "#A9C6E4" },
  { name: "X-34 San Simeon", code: "#D6B89D" },
  { name: "X-40 Dove Grey", code: "#DAD8C8" },
  { name: "X-45 Ash", code: "#CABBA8" },
  { name: "X-46 Antique Gold", code: "#DBBA99" },
  { name: "X-48 Meadowbrook", code: "#EBE0C9" },
  { name: "X-50 Crystal White", code: "#F4F3EB" },
  { name: "X-53 Pure Ivory", code: "#ECDBC1" },
  { name: "X-64 Sequoia", code: "#C6AD96" },
  { name: "X-73 Eggshell White", code: "#EBE4D2" },
  { name: "X-75 Soft Green", code: "#BDC2A4" },
  { name: "X-82 Hacienda", code: "#E3CCB1" },
  { name: "X-83 Prairie", code: "#E0D5B4" },
  { name: "X-84 Sun City", code: "#DBC5A0" },
  { name: "X-86 Sandstone Beige", code: "#DECDB4" },
  { name: "X-Ray", code: "#007597" },
  { name: "Xanadu", code: "#738674" },
  { name: "Xanadu (Ace)", code: "#EDF3F4" },
  { name: "Xanadu (Canada Hardware)", code: "#333F4A" },
  { name: "Xanadu (Crown Paint)", code: "#9AB4D0" },
  { name: "Xanadu (Dulux)", code: "#B87F1F" },
  { name: "Xanadu (Home Hardware)", code: "#394047" },
  { name: "Xanadu (Huls)", code: "#92AECE" },
  { name: "Xanadu (ICI)", code: "#504C7B" },
  { name: "Xanthi (Color Guild)", code: "#D7C1B7" },
  { name: "Xanthi (Colorwheel)", code: "#D8D2C8" },
  { name: "Xanthi (Duron)", code: "#DBC6BF" },
  { name: "Xanthic", code: "#EEED09" },
  { name: "Xanthous", code: "#F1B42F" },
  { name: "Xanthous (Dutch Boy)", code: "#ECB45E" },
  { name: "Xanthous (Dutch Boy) 2", code: "#FBC973" },
  { name: "Xanthous (Kelly Moore)", code: "#F5AE2F" },
  { name: "Xavier (Kelly Moore)", code: "#E8D7B3" },
  { name: "Xavier Blue (Olympic)", code: "#5FBADE" },
  { name: "Xavier Blue (Pittsburgh Paints)", code: "#60BADF" },
  { name: "Xenia", code: "#4F5045" },
  { name: "Xenon Blue", code: "#BAC4D5" },
  { name: "Xerophyte", code: "#BFE2BE" },
  { name: "Xerxes Blue (Bruning Paints)", code: "#B0C0E5" },
  { name: "Xerxes Blue (Huls)", code: "#99A5C5" },
  { name: "Xi Hu Huanghun (Tocol)", code: "#A095B0" },
  { name: "Xiketic", code: "#0C020F" },
  { name: "XL Aged Copper", code: "#90AA93" },
  { name: "XL Bermuda Blue", code: "#216885" },
  { name: "XL Black", code: "#2F2F30" },
  { name: "XL Black Metallic", code: "#333435" },
  { name: "XL Bright Silver", code: "#B4B6B7" },
  { name: "XL Cashmere Pearl", code: "#A59B8E" },
  { name: "XL Champagne", code: "#ADAEAB" },
  { name: "XL Champagne Gold II", code: "#A5A49E" },
  { name: "XL Champagne Metallic", code: "#A7A8A5" },
  { name: "XL Charcoal Gray", code: "#474F55" },
  { name: "XL Copper Metallic", code: "#9F9890" },
  { name: "XL Dark Blue Gray", code: "#4E5053" },
  { name: "XL Dove Gray", code: "#A3A5A4" },
  { name: "XL Eclipse Gray", code: "#5D6162" },
  { name: "XL Fashion Gray", code: "#979DA1" },
  { name: "XL Fawn Metallic", code: "#AAA5A0" },
  { name: "XL Graphite Gray", code: "#3A3F40" },
  { name: "XL Gray Sparkle", code: "#B7B8B6" },
  { name: "XL Gray Timber Wolf", code: "#B9BFC2" },
  { name: "XL Light Bronze", code: "#82796B" },
  { name: "XL Medium Gray", code: "#717270" },
  { name: "XL Metallic Mist", code: "#C0C2BE" },
  { name: "XL Mocha-Ccino", code: "#756860" },
  { name: "XL Platinum", code: "#B4B9B9" },
  { name: "XL Rosted Red Pepper", code: "#87393B" },
  { name: "XL Silver", code: "#AFB2B3" },
  { name: "XL Silver Gray", code: "#92928F" },
  { name: "XL Silver Shadow", code: "#747777" },
  { name: "XL Space Silver", code: "#BABCBB" },
  { name: "XL Steel-City Silver", code: "#ABACAA" },
  { name: "XL Sunstorm Arcadia Silver", code: "#BBBEBD" },
  { name: "XL Telegray II", code: "#94989A" },
  { name: "XLBC Autumnwood Metallic", code: "#999189" },
  { name: "XLBC Bright Silver", code: "#B6B7B7" },
  { name: "XLBC Graphite Gray", code: "#3C4042" },
  { name: "Xotic", code: "#863336" },
  { name: "XOXO", code: "#904F7D" },
  { name: "Xoxo", code: "#EA8797" },
  { name: "Xylophone", code: "#FFB6C1" },
];

const letterW = [
  { name: "Wafer", code: "#DECBC6" },
  { name: "Wageningen Green", code: "#34B233" },
  { name: "Waikawa Gray", code: "#5A6E9C" },
  { name: "Waiouru", code: "#363C0D" },
  { name: "Walmart Blue", code: "#0071CE" },
  { name: "Walnut", code: "#773F1A" },
  { name: "Wan White", code: "#E4E2DC" },
  { name: "Wanderlust", code: "#88843C" },
  { name: "Waratah", code: "#55698B" },
  { name: "Warhol", code: "#9B615F" },
  { name: "Warlord", code: "#45404F" },
  { name: "Warm Black", code: "#004242" },
  { name: "Warm Blue", code: "#6196ED" },
  { name: "Warm Gray", code: "#B5A895" },
  { name: "Warm Kwila", code: "#753A2A" },
  { name: "Warm Neutral", code: "#DABFAC" },
  { name: "Warm Olive", code: "#CBC732" },
  { name: "Warm White", code: "#FFF9F9" },
  { name: "Warmed Brown", code: "#4A302B" },
  { name: "Warrior", code: "#2D3B42" },
  { name: "Wasabi", code: "#788A25" },
  { name: "Wash the Dog (Ĉ)", code: "#FED85D" },
  { name: "Washed Green", code: "#909782" },
  { name: "Water Leaf", code: "#A1E9DE" },
  { name: "Watercourse", code: "#056F57" },
  { name: "Waterloo", code: "#7B7C94" },
  { name: "Watermelon", code: "#F05B85" },
  { name: "Watermelon Red", code: "#B85148" },
  { name: "Waterspout", code: "#A4F4F9" },
  { name: "Wattle", code: "#DCD747" },
  { name: "Watusi", code: "#FFDDCF" },
  { name: "Wave Rider", code: "#413F6E" },
  { name: "Wavelength", code: "#3C6886" },
  { name: "Wax Flower", code: "#FFC0A8" },
  { name: "Wazzup", code: "#BC9425" },
  { name: "We Peep", code: "#F7DBE6" },
  { name: "Weathered Blue", code: "#677583" },
  { name: "Weathered Grey", code: "#776F6F" },
  { name: "Weathered Yellow", code: "#E0DA9F" },
  { name: "Web Orange", code: "#FFA500" },
  { name: "Wedgewood", code: "#4E7F9E" },
  { name: "Wedgewood Blue", code: "#175169" },
  { name: "Weldon Blue", code: "#7C98AB" },
  { name: "Well Read", code: "#B43332" },
  { name: "Well Sausage", code: "#B83A24" },
  { name: "Wells Fargo", code: "#CD1409" },
  { name: "Wellywood", code: "#A3D92D" },
  { name: "Wenge", code: "#645452" },
  { name: "West Coast", code: "#625119" },
  { name: "West Side", code: "#FF910F" },
  { name: "Western Red", code: "#6B252C" },
  { name: "Wet N Wild", code: "#254375" },
  { name: "Wewak", code: "#F19BAB" },
  { name: "Wham", code: "#5FB33A" },
  { name: "Wheat", code: "#F5DEB3" },
  { name: "Wheatfield", code: "#F3EDCF" },
  { name: "Whipped Cream", code: "#F1ECD6" },
  { name: "Whiskey", code: "#D59A6F" },
  { name: "Whiskey Sour", code: "#D4915D" },
  { name: "Whisper", code: "#F7F5FA" },
  { name: "White", code: "#FFFFFF" },
  { name: "White Blue", code: "#CBD3E8" },
  { name: "White Chocolate", code: "#EDE6D6" },
  { name: "White Ice", code: "#DDF9F1" },
  { name: "White Lilac", code: "#F8F7FC" },
  { name: "White Lilen", code: "#F8F0E8" },
  { name: "White Metal", code: "#949594" },
  { name: "White Nectar", code: "#F8F6D8" },
  { name: "White Pearl", code: "#FDFDFD" },
  { name: "White Pointer", code: "#FEF8FF" },
  { name: "White Pointer 2", code: "#DAD6CC" },
  { name: "White Rock", code: "#EAE8D4" },
  { name: "White Smoke", code: "#F5F5F5" },
  { name: "White Sugar", code: "#E6E4E5" },
  { name: "White Wash", code: "#EEEBEB" },
  { name: "Whiteout", code: "#CECAC8" },
  { name: "Whizz Bang", code: "#A23A34" },
  { name: "Wicked", code: "#362F50" },
  { name: "Wild Blue Yonder", code: "#A2ADD0" },
  { name: "Wild Blue Yonder 2", code: "#7A89B8" },
  { name: "Wild Ones", code: "#2B3D7B" },
  { name: "Wild Orchid", code: "#D470A2" },
  { name: "Wild Orchid (Ĉ)", code: "#E6A8D7" },
  { name: "Wild Rice", code: "#ECE090" },
  { name: "Wild Sand", code: "#F4F4F4" },
  { name: "Wild Strawberry", code: "#FF43A4" },
  { name: "Wild Thing", code: "#FAD443" },
  { name: "Wild Watermelon", code: "#FC6C85" },
  { name: "Wild West", code: "#9A5440" },
  { name: "Wild Willow", code: "#B9C46A" },
  { name: "Wilderness", code: "#88885B" },
  { name: "Wildflower", code: "#F1E2C9" },
  { name: "William", code: "#3A686C" },
  { name: "Williamsburg Blue", code: "#778CA1" },
  { name: "Willow Brook", code: "#DFECDA" },
  { name: "Willow Grove", code: "#65745D" },
  { name: "Willpower Orange", code: "#FD5800" },
  { name: "Winchester", code: "#514E4A" },
  { name: "Wildblown Green", code: "#7E867B" },
  { name: "Windsor", code: "#3C0878" },
  { name: "Windsor Tan", code: "#A75502" },
  { name: "Wine", code: "#722F37" },
  { name: "Wine Berry", code: "#591D35" },
  { name: "Wine Dregs", code: "#673147" },
  { name: "Wine Trail", code: "#27292D" },
  { name: "Winter Blue", code: "#9EBACF" },
  { name: "Winter Hazel", code: "#D5D195" },
  { name: "Winter Sky", code: "#FF007C" },
  { name: "Winter White", code: "#F1FAFF" },
  { name: "Winter Wizard", code: "#A0E6FF" },
  { name: "Wintergreen Dream", code: "#56887D" },
  { name: "Wisp Pink", code: "#FEF4F8" },
  { name: "Wisteria", code: "#C9A0DC" },
  { name: "Wisteria 2", code: "#9771B5" },
  { name: "Wisteria 3", code: "#A4878B" },
  { name: "Wistful", code: "#A4A6D3" },
  { name: "Witch Haze", code: "#FFFC99" },
  { name: "Wombat", code: "#675744" },
  { name: "Wonderland", code: "#BB97BB" },
  { name: "Wood", code: "#4E0606" },
  { name: "Wood Bark", code: "#261105" },
  { name: "Wood Brown", code: "#C19A6B" },
  { name: "Woodburn", code: "#463629" },
  { name: "Woodland", code: "#4D5328" },
  { name: "Woodrush", code: "#302A0F" },
  { name: "Woodsmoke", code: "#0C0D0F" },
  { name: "Woodstock", code: "#839C60" },
  { name: "Woody Bay", code: "#33343A" },
  { name: "Woody Brown", code: "#483131" },
  { name: "Wot Eva", code: "#4495A4" },
  { name: "Wow", code: "#343467" },
];

const letterV = [
  { name: "Valencia", code: "#D84437" },
  { name: "Valentino", code: "#350E42" },
  { name: "Valhalla", code: "#2B194F" },
  { name: "Vampire Black", code: "#080808" },
  { name: "Van Cleef", code: "#49170C" },
  { name: "Van Dyke Brown", code: "#664228" },
  { name: "Van Gogh Green", code: "#8FB66D" },
  { name: "Vandyck Brown", code: "#7B5349" },
  { name: "Vanilla", code: "#F3E5AB" },
  { name: "Vanilla Bean Brown", code: "#362C1D" },
  { name: "Vanilla Cream", code: "#F7E0D2" },
  { name: "Vanilla Ice", code: "#F38FA9" },
  { name: "Vanilla White", code: "#F6EEE5" },
  { name: "Vanquish", code: "#63272F" },
  { name: "Vantablack", code: "#080904" },
  { name: "Varden", code: "#FFF6DF" },
  { name: "Varnish Brown", code: "#B95E33" },
  { name: "Vault", code: "#565740" },
  { name: "Vegan Green", code: "#006C47" },
  { name: "Vegas", code: "#FCB358" },
  { name: "Vegas Gold", code: "#C5B358" },
  { name: "Vehicle Body Gray", code: "#4C433D" },
  { name: "Velocity", code: "#4B4042" },
  { name: "Veltiner White", code: "#D7D8C3" },
  { name: "Velvet Beige", code: "#D0C5B1" },
  { name: "Velvet Blue", code: "#9FCAE5" },
  { name: "Velvet Gray", code: "#ACAAB3" },
  { name: "Velvet Green Gray", code: "#737866" },
  { name: "Velvet Mauve", code: "#692B57" },
  { name: "Velvet Red", code: "#904353" },
  { name: "Venetian Pink", code: "#C07B9A" },
  { name: "Venetian Red", code: "#C80815" },
  { name: "Venice Blue", code: "#055989" },
  { name: "Ventura", code: "#907C38" },
  { name: "Venus", code: "#928590" },
  { name: "Verdigris", code: "#43B3AE" },
  { name: "Verdun Green", code: "#495400" },
  { name: "Vermeer Blue", code: "#2B7CAF" },
  { name: "Vermilion", code: "#E34234" },
  { name: "Vermilion Green", code: "#474230" },
  { name: "Vermilion Red", code: "#B45A56" },
  { name: "Vermont", code: "#B2BE61" },
  { name: "Veronica", code: "#A020F0" },
  { name: "Vert", code: "#00C000" },
  { name: "Verve", code: "#5D2E3C" },
  { name: "Very Dark Purple", code: "#12020A" },
  { name: "Very Light Azure", code: "#74BBFB" },
  { name: "Very Light Blue", code: "#6666FF" },
  { name: "Very Light Malachite Green", code: "#64E986" },
  { name: "Very Light Tangelo", code: "#FFB077" },
  { name: "Very Pale Orange", code: "#FFDFBF" },
  { name: "Very Pale Yellow", code: "#FFFFBF" },
  { name: "Vespa Yellow", code: "#F3D19F" },
  { name: "Vesuvian Green", code: "#879860" },
  { name: "Vesuvian Violet", code: "#A28A9F" },
  { name: "Vesuvius", code: "#B14A08" },
  { name: "Vibe", code: "#AC3142" },
  { name: "Vibrant Green", code: "#509D83" },
  { name: "Vibrant Red", code: "#C24C6A" },
  { name: "Vibrant Soft Blue", code: "#88D6DC" },
  { name: "Victoria", code: "#534491" },
  { name: "Victoria Red", code: "#9C333C" },
  { name: "Victoria Blue", code: "#006394" },
  { name: "Vida Loca", code: "#549019" },
  { name: "Vienna", code: "#A5B376" },
  { name: "Viennese Blue", code: "#4278AF" },
  { name: "Viking", code: "#64CCDB" },
  { name: "Vin Rouge", code: "#983D61" },
  { name: "Vine leaf Green", code: "#6E5E2C" },
  { name: "Vintage", code: "#A78087" },
  { name: "Vintage Blue", code: "#6FB7CC" },
  { name: "Vintage White", code: "#FBEFE4" },
  { name: "Viola", code: "#CB8FA9" },
  { name: "Viola Black", code: "#2F2A41" },
  { name: "Viola Ice Gray", code: "#C6C8D0" },
  { name: "Violent Violet", code: "#290C5E" },
  { name: "Violet", code: "#8F00FF" },
  { name: "Violet 2", code: "#240A40" },
  { name: "Violet (Ĉ)", code: "#732E6C" },
  { name: "Violet (Power Wheel)", code: "#7F00FF" },
  { name: "Violet (RYB)", code: "#8601AF" },
  { name: "Violet (Web)", code: "#EE82EE" },
  { name: "Violet Eggplant", code: "#991199" },
  { name: "Violet Haze", code: "#6A6E9D" },
  { name: "Violet Blue", code: "#324AB2" },
  { name: "Violet Blue (Ĉ)", code: "#766EC8" },
  { name: "Violet Red", code: "#F75394" },
  { name: "Viridian", code: "#40826D" },
  { name: "Viridian Green", code: "#009698" },
  { name: "Vis Vis", code: "#FFEFA1" },
  { name: "Vision", code: "#A09BB2" },
  { name: "Visiona Red", code: "#83477D" },
  { name: "Vista Blue", code: "#7C9ED9" },
  { name: "Vista White", code: "#FCF8F7" },
  { name: "Vital Green", code: "#138859" },
  { name: "Vivid Amber", code: "#CC9900" },
  { name: "Vivid Auburn", code: "#922724" },
  { name: "Vivid Burgundy", code: "#9F1D35" },
  { name: "Vivid Cerise", code: "#DA1D81" },
  { name: "Vivid Cerulean", code: "#00AAEE" },
  { name: "Vivid Crimson", code: "#CC0033" },
  { name: "Vivid Gamboge", code: "#FF9900" },
  { name: "Vivid Lime Green", code: "#A6D608" },
  { name: "Vivid Malachite", code: "#00CC33" },
  { name: "Vivid Mulberry", code: "#B80CE3" },
  { name: "Vivid Orange", code: "#FF5F00" },
  { name: "Vivid Orange Peel", code: "#FFA000" },
  { name: "Vivid Orchid", code: "#CC00FF" },
  { name: "Vivid Raspberry", code: "#FF006C" },
  { name: "Vivid Red", code: "#F70D1A" },
  { name: "Vivid Red Tangelo", code: "#DF6124" },
  { name: "Vivid Sky Blue", code: "#00CCFF" },
  { name: "Vivid Tangelo", code: "#F07427" },
  { name: "Vivid Tangerine", code: "#FFA089" },
  { name: "Vivid Vermilion", code: "#E56024" },
  { name: "Vivid Violet", code: "#9F00FF" },
  { name: "Vivid Violet 2", code: "#803790" },
  { name: "Vivid Yellow", code: "#FFE302" },
  { name: "Vixen", code: "#81342B" },
  { name: "Volcanic Stone Green", code: "#45433B" },
  { name: "Volcano", code: "#4E2728" },
  { name: "Volt", code: "#CEFF00" },
  { name: "Voodoo", code: "#533455" },
  { name: "Vortex", code: "#3A385B" },
  { name: "Vroom", code: "#353D75" },
  { name: "Vulcan", code: "#10121D" },
];

const letterU = [
  { name: "U and I", code: "#A10A39" },
  { name: "US green", code: "#39594A" },
  { name: "UA Blue", code: "#0033AA" },
  { name: "UA Red", code: "#D9004C" },
  { name: "Ube", code: "#8878C3" },
  { name: "UCLA Blue", code: "#536895" },
  { name: "UCLA Gold", code: "#FFB300" },
  { name: "UFO Green", code: "#3CD070" },
  { name: "Ugandan Violet", code: "#6B5666" },
  { name: "Uguisu-iro", code: "#645530" },
  { name: "Uguisucha", code: "#5C4827" },
  { name: "Uhsting's Blue", code: "#1851FF" },
  { name: "Ukon-iro", code: "#E69B3A" },
  { name: "Ultra Green", code: "#7EBA4D" },
  { name: "Ultra Pink", code: "#FF6FFF" },
  { name: "Ultra Red", code: "#FC6C85" },
  { name: "Ultra Violet", code: "#9D81BA" },
  { name: "Ultra White", code: "#F3F2EC" },
  { name: "Ultramarine", code: "#3F00FF" },
  { name: "Ultramarine 2", code: "#120A8F" },
  { name: "Ultramarine 05", code: "#395161" },
  { name: "Ultramarine Blue", code: "#4166F5" },
  { name: "Ultramarine Violet", code: "#1D2A58" },
  { name: "Uluru", code: "#BF9B67" },
  { name: "Umber", code: "#635147" },
  { name: "Umber Style (Columbia Paint)", code: "#ECE6DC" },
  { name: "Umber Style (Home Hardware)", code: "#ECE6DA" },
  { name: "Umbra Gray", code: "#4B4D46" },
  { name: "Umbra Sand", code: "#87706B" },
  { name: "Umbrella (Dutch Boy)", code: "#007983" },
  { name: "Umbrella (Martha Stewart)", code: "#26424D" },
  { name: "Umbria Red", code: "#974148" },
  { name: "Umemurasaki", code: "#8F4155" },
  { name: "Umenezumi", code: "#97645A" },
  { name: "Umezome", code: "#FA9258" },
  { name: "Um Num Num Num", code: "#216A95" },
  { name: "Unbleached Silk", code: "#FFDDCA" },
  { name: "Unbriel", code: "#5E4B42" },
  { name: "Uncommon Coir", code: "#C4A98C" },
  { name: "Uncommon Clarity", code: "#F4E7C1" },
  { name: "Undercurrent", code: "#365C6C" },
  { name: "Undersea Blue", code: "#275F73" },
  { name: "Undersea Garden (Muralo)", code: "#165659" },
  { name: "Undersea Garden (Mythic)", code: "#285C60" },
  { name: "Undersea Voyage", code: "#2B878F" },
  { name: "Understated (Muralo)", code: "#B8DCCA" },
  { name: "Understated (Valspar)", code: "#D7D2BB" },
  { name: "Underwater", code: "#475B5D" },
  { name: "Underwater Cave", code: "#006771" },
  { name: "Underwater Green", code: "#9AE1C4" },
  { name: "Underwater Wonders", code: "#00A5AB" },
  { name: "Underwood", code: "#697F6C" },
  { name: "Underworld", code: "#B29C96" },
  { name: "Unexpected", code: "#DD6863" },
  { name: "Unicorn", code: "#9F90D0" },
  { name: "Unicorn Blue", code: "#00A3AC" },
  { name: "Unicorn White", code: "#D6CDC5" },
  { name: "Uniform Blue", code: "#475767" },
  { name: "Uniform Green", code: "#4C4623" },
  { name: "Uniform Green Gray", code: "#5F7B7E" },
  { name: "Uninhibited", code: "#BBD1C7" },
  { name: "Uninon Blue", code: "#55676E" },
  { name: "Unique", code: "#F2F5E8" },
  { name: "Unique Gray", code: "#CAC8CA" },
  { name: "United Nations Blue", code: "#5B92E5" },
  { name: "Universal Black", code: "#343334" },
  { name: "Universal Blue", code: "#C5D2D4" },
  { name: "Universal Green", code: "#006B38" },
  { name: "Universal Gray", code: "#CBCBCB" },
  { name: "Universal Of California Gold", code: "#B78727" },
  { name: "Universal Of Tennessee Orange", code: "#F77F00" },
  { name: "University Red", code: "#B84642" },
  { name: "Unknown Legend", code: "#3E444C" },
  { name: "Unmatched Beauty", code: "#936365" },
  { name: "Unmellow Yellow", code: "#FFFF66" },
  { name: "Un-Teal We Meet Again", code: "#7EC9C8" },
  { name: "Unwind", code: "#A8C1BB" },
  { name: "Up a Lazy River", code: "#37443C" },
  { name: "UP Forest Green", code: "#014421" },
  { name: "UP Maroon", code: "#7B1113" },
  { name: "Upon Reflection", code: "#AE9568" },
  { name: "Upsdell Red", code: "#AE2029" },
  { name: "Uptown", code: "#798E9D" },
  { name: "Uptown Girl", code: "#B45438" },
  { name: "Up, Up, and Away", code: "#7FA0CE" },
  { name: "Urahayanagi", code: "#BCB58C" },
  { name: "Uranus", code: "#CAF0F1" },
  { name: "Urban Blue", code: "#2863C9" },
  { name: "Urban Blue 2", code: "#0056A3" },
  { name: "Urban Bungalow", code: "#D7C7A9" },
  { name: "Urban Charm", code: "#B0A08B" },
  { name: "Urban Dream", code: "#C6BBAE" },
  { name: "Urban Getaway", code: "#A0957B" },
  { name: "Urban Gold", code: "#DBC7A9" },
  { name: "Urban Green", code: "#089573" },
  { name: "Urban Grey", code: "#C2BEBF" },
  { name: "Urban Jungle", code: "#33363C" },
  { name: "Urban Legend", code: "#42333A" },
  { name: "Urban Lights", code: "#8A7B6E" },
  { name: "Urban Midnight", code: "#1D5872" },
  { name: "Urban Mode", code: "#EBAC7C" },
  { name: "Urban Natural", code: "#C2BEBE" },
  { name: "Urban Oasis", code: "#39565A" },
  { name: "Urban Purple", code: "#503F76" },
  { name: "Urban Pulse", code: "#6E6867" },
  { name: "Urban Putty", code: "#ACADA6" },
  { name: "Urban Red", code: "#C20E0F" },
  { name: "Urban Stone", code: "#B7D1D5" },
  { name: "Urban Yellow", code: "#FCCD0D" },
  { name: "Urbane", code: "#D9D1CF" },
  { name: "Urbanista", code: "#C7C3BC" },
  { name: "Urobilin", code: "#E1AD21" },
  { name: "USA Blue", code: "#303C55" },
  { name: "USAFA Blue", code: "#004F98" },
  { name: "USC Cardinal", code: "#990000" },
  { name: "USC Gold", code: "#FFCC00" },
  { name: "Useful Brown", code: "#B09566" },
  { name: "Useful Gray", code: "#CFC9BB" },
  { name: "Usu-iro", code: "#A87CA0" },
  { name: "Usu'ao", code: "#8C9C76" },
  { name: "Usubeni", code: "#F2666C" },
  { name: "Usugaki", code: "#FCA474" },
  { name: "Usukō", code: "#FFA565" },
  { name: "Usumo'egi", code: "#8DB255" },
  { name: "Utah Crimson", code: "#D3003F" },
  { name: "Utopia Beckons", code: "#31B3BE" },
  { name: "Utterly Beige", code: "#B6A596" },
  { name: "Utterly Blue", code: "#AECCE4" },
  { name: "Utterly Pink", code: "#FBDCE4" },
  { name: "Utterly Violet", code: "#A6A6C4" },
];

const letterT = [
  { name: "T-Shirt Green", code: "#1BB35B" },
  { name: "Tabac", code: "#585044" },
  { name: "Tabasco", code: "#A02712" },
  { name: "Tabby", code: "#C5B298" },
  { name: "Tacao", code: "#EDB381" },
  { name: "Tacha", code: "#D6C562" },
  { name: "Taffeta", code: "#996E9E" },
  { name: "Taffy Cream", code: "#FEF1AD" },
  { name: "Tahiti Gold", code: "#E97C07" },
  { name: "Tahuna Sands", code: "#EEF0C8" },
  { name: "Takaka", code: "#3D4D78" },
  { name: "Talisman", code: "#655D50" },
  { name: "Tall Poppy", code: "#B32D29" },
  { name: "Tallow", code: "#A8A589" },
  { name: "Tamarillo", code: "#991613" },
  { name: "Tamarillo Orange", code: "#FE8915" },
  { name: "Tamarind", code: "#341515" },
  { name: "Tan", code: "#D2B48C" },
  { name: "Tan Hide", code: "#FA9D5A" },
  { name: "Tana", code: "#D9DCC1" },
  { name: "Tandoori", code: "#8D4532" },
  { name: "Tangaroa", code: "#03163C" },
  { name: "Tangelo", code: "#F94D00" },
  { name: "Tangerine", code: "#F28500" },
  { name: "Tangerine Yellow", code: "#FFCC00" },
  { name: "Tango", code: "#ED7A1C" },
  { name: "Tango Pink", code: "#E4717A" },
  { name: "Tao Grey", code: "#323436" },
  { name: "Tapa", code: "#7B7874" },
  { name: "Tapestry", code: "#B05E81" },
  { name: "Tar", code: "#383838" },
  { name: "Tara", code: "#E1F6E8" },
  { name: "Tarawera", code: "#073A50" },
  { name: "Tarmac", code: "#6F6F6E" },
  { name: "Tarot", code: "#38293D" },
  { name: "Tart Orange", code: "#FB4D46" },
  { name: "Tasman", code: "#CFDCCF" },
  { name: "Taupe", code: "#483C32" },
  { name: "Taupe Gray", code: "#8B8589" },
  { name: "Tawny", code: "#DEAA88" },
  { name: "Tawny Port", code: "#692545" },
  { name: "Tax Break", code: "#496569" },
  { name: "Te Papa Green", code: "#1E433C" },
  { name: "Tea", code: "#C1BAB0" },
  { name: "Tea Green", code: "#D0F0C0" },
  { name: "Tea Rose", code: "#F88379" },
  { name: "Teak", code: "#B19461" },
  { name: "Teal", code: "#008080" },
  { name: "Teal Blue", code: "#367588" },
  { name: "Teal Deer", code: "#99E6B3" },
  { name: "Teal Green", code: "#00827F" },
  { name: "Techno", code: "#8E886E" },
  { name: "Telemagenta", code: "#CF3476" },
  { name: "Tempo", code: "#462B31" },
  { name: "Temptress", code: "#3B000B" },
  { name: "Tenné", code: "#CD5700" },
  { name: "Tequila", code: "#FFE6C7" },
  { name: "Teranova", code: "#7A3A2B" },
  { name: "Terra Cotta", code: "#E2725B" },
  { name: "Terracotta Hit", code: "#8E5037" },
  { name: "Terracotta Pink", code: "#9B3D3D" },
  { name: "Terrain", code: "#ADAD99" },
  { name: "Texas", code: "#F8F99C" },
  { name: "Texas Rose", code: "#FFB555" },
  { name: "Thatch", code: "#B69D98" },
  { name: "Thatch Green", code: "#403D19" },
  { name: "Thistle", code: "#D8BFD8" },
  { name: "Thistle Green", code: "#CCCAA8" },
  { name: "Three Wishes", code: "#D2DAED" },
  { name: "Thulian Pink", code: "#DE6FA1" },
  { name: "Thunder", code: "#33292F" },
  { name: "Thunderbird", code: "#C02B18" },
  { name: "Tia Maria", code: "#C1440E" },
  { name: "Tiara", code: "#C3D1D1" },
  { name: "Tiber", code: "#063537" },
  { name: "Tickle Me Pink", code: "#FC89AC" },
  { name: "Tickled Pink", code: "#962C54" },
  { name: "Tidal", code: "#F1FFAD" },
  { name: "Tide", code: "#BFB8B0" },
  { name: "Tiebreaker", code: "#8E97AB" },
  { name: "Tiffany Blue", code: "#0ABAB5" },
  { name: "Tiger Lily", code: "#DDE574" },
  { name: "Tiger Orange", code: "#C46210" },
  { name: "Tiger's Eye", code: "#E08D3C" },
  { name: "Tigger", code: "#F99E45" },
  { name: "Tile Green", code: "#26433A" },
  { name: "Timber Green", code: "#16322C" },
  { name: "Timberland", code: "#4C332A" },
  { name: "Timberwolf", code: "#DBD7D2" },
  { name: "Time Out", code: "#AAC2E3" },
  { name: "Time Warp", code: "#374467" },
  { name: "Tinkerbell", code: "#FCD763" },
  { name: "Tinpan Alley", code: "#5C5B59" },
  { name: "Tiri", code: "#46413E" },
  { name: "Titan White", code: "#F0EEFF" },
  { name: "Titania", code: "#CAC7B9" },
  { name: "Titanium", code: "#878681" },
  { name: "Titanium Yellow", code: "#EEE600" },
  { name: "Toadstool", code: "#FD0100" },
  { name: "Toast", code: "#9A6E61" },
  { name: "Toasted Green", code: "#655535" },
  { name: "Tobacco Brown", code: "#715D47" },
  { name: "Tobago", code: "#44362D" },
  { name: "Toffee", code: "#71432B" },
  { name: "Toi Toi", code: "#B7AD8B" },
  { name: "Toledo", code: "#3A0020" },
  { name: "Tolopea", code: "#1B0245" },
  { name: "Tom Thumb", code: "#3F583B" },
  { name: "Tom Tom", code: "#92827F" },
  { name: "Tomahawk", code: "#524340" },
  { name: "Tomato", code: "#FF6347" },
  { name: "Tonto", code: "#9F9596" },
  { name: "Toolbox", code: "#746CC0" },
  { name: "Toolbox Red", code: "#ED2323" },
  { name: "Top Gear", code: "#24221A" },
  { name: "Top Secret", code: "#7AAC21" },
  { name: "Topaz", code: "#FFC87C" },
  { name: "Topsy Turvy", code: "#313669" },
  { name: "Tornado", code: "#5B6B84" },
  { name: "Torris Blue", code: "#487393" },
  { name: "Tosca", code: "#8D3F3F" },
  { name: "Toto", code: "#519DAF" },
  { name: "Touch Wood", code: "#3A372E" },
  { name: "Tower Gray", code: "#A9BDBF" },
  { name: "Tractor Red", code: "#FD0E35" },
  { name: "Tradewind", code: "#5FB3AC" },
  { name: "Traffic", code: "#6C6D68" },
  { name: "Traffic Light", code: "#CD5D34" },
  { name: "Trailblazer", code: "#5F4C27" },
  { name: "Trainspotter", code: "#44493F" },
  { name: "Tranquil", code: "#E6FFFF" },
  { name: "Travertine", code: "#FFFDE8" },
  { name: "Travis", code: "#B79E67" },
  { name: "Teasure", code: "#758A9C" },
  { name: "Tree Frog", code: "#50S743" },
  { name: "Tree Poppy", code: "#FC9C1D" },
  { name: "Treehouse", code: "#3B2820" },
  { name: "Treetops", code: "#A6A28F" },
  { name: "Trendy Green", code: "#7C881A" },
  { name: "Trendy Pink", code: "#8C6495" },
  { name: "Triple Perfect Taupe", code: "#867A6F" },
  { name: "Triple Spanish White", code: "#D5C4A1" },
  { name: "Triple White Pointer", code: "#C8C3B5" },
  { name: "Trinidad", code: "#E64E03" },
  { name: "Trolley Grey", code: "#808080" },
  { name: "Tropical Blue", code: "#C3DDF9" },
  { name: "Tropical Rain Forest", code: "#00755E" },
  { name: "Tropical Violet", code: "#CDA4DE" },
  { name: "Troubadour", code: "#56225A" },
  { name: "Trout", code: "#4A4E5A" },
  { name: "True Blue", code: "#0073CF" },
  { name: "True Ochre", code: "#C8A115" },
  { name: "True Red", code: "#C0003C" },
  { name: "True V", code: "#8A73D6" },
  { name: "Tsunami", code: "#6B8393" },
  { name: "Tuatara", code: "#363534" },
  { name: "Tuft Bush", code: "#FFDDCD" },
  { name: "Tulip", code: "#FF878D" },
  { name: "Tulip Orange", code: "#FF8833" },
  { name: "Tulip Tree", code: "#EAB33B" },
  { name: "Tumbleweed", code: "#4B412A" },
  { name: "Tuna", code: "#353542" },
  { name: "Tundora", code: "#4A4244" },
  { name: "Turacin", code: "#E30433" },
  { name: "Turacoverdin", code: "#666604" },
  { name: "Turbo", code: "#FAE600" },
  { name: "Turkey Blue", code: "#597BDC" },
  { name: "Turkey Umber", code: "#473D33" },
  { name: "Turmeric", code: "#CABB48" },
  { name: "Turquoise", code: "#40E0D0" },
  { name: "Turquoise Blue", code: "#00FFEF" },
  { name: "Turquoise Green", code: "#A0D6B4" },
  { name: "Turquoise Surf", code: "#00C5CD" },
  { name: "Turtle Green", code: "#8A9A5B" },
  { name: "Tuscan", code: "#FAD6A5" },
  { name: "Tuscan Brown", code: "#6F4E37" },
  { name: "Tuscan Red", code: "#7C4848" },
  { name: "Tuscan Tan", code: "#A67B5B" },
  { name: "Tuscany", code: "#C09999" },
  { name: "Tusk", code: "#EEF3C3" },
  { name: "Tussock", code: "#C5994B" },
  { name: "Tutti Frutti", code: "#9FD385" },
  { name: "Tutu", code: "#FFF1F9" },
  { name: "Twenty four seven", code: "#FAD443" },
  { name: "Twilight", code: "#E4CFDE" },
  { name: "Twilight Blue", code: "#EEFDFF" },
  { name: "Twilight Lavender", code: "#8A496B" },
  { name: "Twine", code: "#C2955D" },
  { name: "Twister", code: "#938255" },
  { name: "Twitter Blue", code: "#00ACED" },
  { name: "Tyrian Purple", code: "#66023C" },
];

const letterS = [
  { name: "Sabbatical", code: "#547377" },
  { name: "Sable", code: "#402000" },
  { name: "Saddle", code: "#4C3024" },
  { name: "Safari", code: "#C0A469" },
  { name: "Saffron", code: "#F4C430" },
  { name: "Sage", code: "#BCB88A" },
  { name: "Sahara", code: "#B7A214" },
  { name: "Sail", code: "#B8E0F9" },
  { name: "Salem", code: "#097F4B" },
  { name: "Salmon", code: "#FA8072" },
  { name: "Saloon", code: "#D5BF98" },
  { name: "Salt Box", code: "#685E6E" },
  { name: "San Felix", code: "#0B6207" },
  { name: "San Juan", code: "#304B6A" },
  { name: "Sanctuary", code: "#A68459" },
  { name: "Sand", code: "#C2B280" },
  { name: "Sandal", code: "#AA8D6F" },
  { name: "Sandalwood", code: "#8C6440" },
  { name: "Sandstorm", code: "#ECD540" },
  { name: "Sangria", code: "#92000A" },
  { name: "Sanguine", code: "#C00000" },
  { name: "Santa Fe", code: "#B16D52" },
  { name: "Santa Red", code: "#9E1D33" },
  { name: "Sap Green", code: "#507D2A" },
  { name: "Sapphire", code: "#0F52BA" },
  { name: "Saratoga", code: "#555B10" },
  { name: "Sargent Pepper", code: "#A34053" },
  { name: "Sasquatch Socks", code: "#FF4681" },
  { name: "Sassy", code: "#7E2A65" },
  { name: "Satellite", code: "#554244" },
  { name: "Saturn", code: "#FAEFAD" },
  { name: "Scarlet", code: "#FF2400" },
  { name: "Schist", code: "#A9B497" },
  { name: "School Bus Yellow", code: "#FFD800" },
  { name: "Science Blue", code: "#0066CC" },
  { name: "Scorpio", code: "#695F62" },
  { name: "Scrub", code: "#3D4031" },
  { name: "Sea Blue", code: "#006994" },
  { name: "Sea Green", code: "#1F6361" },
  { name: "Sea Nymph", code: "#78A39C" },
  { name: "Sea Serpent", code: "#4BC7CF" },
  { name: "Seagull", code: "#BFBDC8" },
  { name: "Seal", code: "#9EA587" },
  { name: "Seaweed", code: "#003A1E" },
  { name: "Secret Garden", code: "#6D6D26" },
  { name: "Seismic", code: "#9C7D67" },
  { name: "Sepia", code: "#704214" },
  { name: "Serendipity", code: "#B1B9D3" },
  { name: "Sesame", code: "#DCCBB6" },
  { name: "Shadow Blue", code: "#778BA5" },
  { name: "Shakespeare", code: "#4EABD1" },
  { name: "Shale Green", code: "#BEC3AC" },
  { name: "Shamrock", code: "#33CC99" },
  { name: "Shark", code: "#25272C" },
  { name: "Sheen Green", code: "#8FD400" },
  { name: "Sheer Black", code: "#332F2F" },
  { name: "Sherpa Blue", code: "#004950" },
  { name: "Sherwood Green", code: "#02402C" },
  { name: "Shimmering Blush", code: "#D98695" },
  { name: "Ship Cove", code: "#788BBA" },
  { name: "Shocking", code: "#E292C0" },
  { name: "Shooting Star", code: "#FDE336" },
  { name: "Showtime", code: "#2F263A" },
  { name: "Shrimp", code: "#DAA589" },
  { name: "Sidecar", code: "#F3E7BB" },
  { name: "Sienna", code: "#882D17" },
  { name: "Signal", code: "#CD1E59" },
  { name: "Silk", code: "#BDB1A8" },
  { name: "Silver", code: "#C0C0C0" },
  { name: "Sinbad", code: "#9FD7D3" },
  { name: "Sing Song", code: "#F6E0A4" },
  { name: "Sinopia", code: "#CB410B" },
  { name: "Siren", code: "#7A013A" },
  { name: "Sirocco", code: "#718080" },
  { name: "Sisal", code: "#D3CBBA" },
  { name: "Sizzling Red", code: "#FF3855" },
  { name: "Skeptic", code: "#CAE6DA" },
  { name: "Sky Blue", code: "#87CEEB" },
  { name: "Slate Blue", code: "#6A5ACD" },
  { name: "Slate Gray", code: "#708090" },
  { name: "Slime", code: "#59BE37" },
  { name: "Slugger", code: "#42342B" },
  { name: "Smiles", code: "#FBF073" },
  { name: "Smoke", code: "#738276" },
  { name: "Smooth Cream", code: "#FFE4C6" },
  { name: "Snap", code: "#5BA0D0" },
  { name: "Snow", code: "#FFFAFA" },
  { name: "Soap", code: "#CEC8EF" },
  { name: "Socrates", code: "#716D59" },
  { name: "Soft Sage", code: "#DDE3C1" },
  { name: "Solid Gold", code: "#927748" },
  { name: "Somerset", code: "#DFDD78" },
  { name: "Sonic Boom", code: "#89B737" },
  { name: "Soot", code: "#100C08" },
  { name: "Sorbus", code: "#FD7C07" },
  { name: "Sorrell Brown", code: "#CEB98F" },
  { name: "Souffle", code: "#D5C171" },
  { name: "Southwest Blue", code: "#5D76CB" },
  { name: "Soya Bean", code: "#6A6051" },
  { name: "Space Shuttle", code: "#4B433B" },
  { name: "Spanish Blue", code: "#0070B8" },
  { name: "Spanish Crimson", code: "#E51A4C" },
  { name: "Spanish Green", code: "#009150" },
  { name: "Spanish Red", code: "#E60026" },
  { name: "Spanish Violet", code: "#4C2882" },
  { name: "Spanish White", code: "#DED1B7" },
  { name: "Spark", code: "#695341" },
  { name: "Spectra", code: "#2F5A57" },
  { name: "Spice", code: "#6A442E" },
  { name: "Spicy Mustard", code: "#74640D" },
  { name: "Spider", code: "#2B291B" },
  { name: "Spinach", code: "#435D36" },
  { name: "Spindle", code: "#B6D1EA" },
  { name: "Spirulina", code: "#688C60" },
  { name: "Sponge", code: "#DCDBCD" },
  { name: "Sports Star", code: "#3D85B8" },
  { name: "Spray", code: "#79DEEC" },
  { name: "Spring Green", code: "#00FF7F" },
  { name: "Spring Rain", code: "#ACCBB1" },
  { name: "Spring Wood", code: "#F8F6F1" },
  { name: "Spritzer", code: "#C2E225" },
  { name: "Spruce", code: "#009A5B" },
  { name: "Sputnik", code: "#373E54" },
  { name: "Squall", code: "#3A3B35" },
  { name: "Squirrel", code: "#8F8176" },
  { name: "St. Patrick's Blue", code: "#23297A" },
  { name: "St Topaz", code: "#2D569B" },
  { name: "Star Command Blue", code: "#007BB8" },
  { name: "Star Dust", code: "#9F9F9C" },
  { name: "Starfruit", code: "#F1D557" },
  { name: "Stark White", code: "#E5D7BD" },
  { name: "Steel Blue", code: "#4682B4" },
  { name: "Steel Gray", code: "#43464B" },
  { name: "Steel Teal", code: "#5F8A8B" },
  { name: "Sterling Silver", code: "#9F9E9C" },
  { name: "Stiletto", code: "#9C3336" },
  { name: "Stone", code: "#828073" },
  { name: "Stone Age", code: "#B6B285" },
  { name: "Stonewall", code: "#928573" },
  { name: "Storm", code: "#36365D" },
  { name: "Stratos", code: "#000741" },
  { name: "Stratosphere", code: "#196194" },
  { name: "Straw", code: "#E4D96F" },
  { name: "Strawberry", code: "#FC5A8D" },
  { name: "Streetwise", code: "#4F6971" },
  { name: "Stromboli", code: "#325D52" },
  { name: "Sublime", code: "#CDE65D" },
  { name: "Submarine", code: "#BAC7C9" },
  { name: "Subzero", code: "#5B8D8D" },
  { name: "Sugar Plum", code: "#914E75" },
  { name: "Summer Green", code: "#96BBAB" },
  { name: "Sun", code: "#FBAC13" },
  { name: "Sundial", code: "#DDB12C" },
  { name: "Sundown", code: "#FFB1B3" },
  { name: "Sunflower", code: "#E4D422" },
  { name: "Sunny", code: "#F2F27A" },
  { name: "Sunset", code: "#FAD6A5" },
  { name: "Super Duper", code: "#42639F" },
  { name: "Super Pink", code: "#CF6BA9" },
  { name: "Super Sonic", code: "#374467" },
  { name: "Superhero", code: "#374E88" },
  { name: "Supernova", code: "#FFC901" },
  { name: "Surf", code: "#BBD7C1" },
  { name: "Sushi", code: "#87AB39" },
  { name: "Suva Gray", code: "#888387" },
  { name: "Swamp Green", code: "#ACB78E" },
  { name: "Swans Down", code: "#DCF0EA" },
  { name: "Sweet Dreams", code: "#F9D77E" },
  { name: "Sweet Pea Green", code: "#A9BE85" },
  { name: "Sweet Pink", code: "#FD9FA2" },
  { name: "Sweet Purple", code: "#8953DC" },
  { name: "Swiss Coffee", code: "#DDD6D5" },
  { name: "Sword", code: "#808284" },
  { name: "Swordfish", code: "#A7A69C" },
  { name: "Sycamore", code: "#908D39" },
  { name: "Symphony", code: "#C4D3B4" },
];

const letterR = [
  { name: "Racing Green", code: "#0C1911" },
  { name: "Rackley", code: "#5D8AA8" },
  { name: "Radical Red", code: "#FF355E" },
  { name: "Raffia", code: "#EADAB8" },
  { name: "Rain Forest", code: "#667028" },
  { name: "Rainee", code: "#B9C8AC" },
  { name: "Raisin Black", code: "#242124" },
  { name: "Raisins", code: "#4D1808" },
  { name: "Rajah", code: "#FBAB60" },
  { name: "Rangitoto", code: "#2E3222" },
  { name: "Rangoon Green", code: "#1C1E23" },
  { name: "Rapture Rose", code: "#DD768B" },
  { name: "Rare Sausage", code: "#F88B30" },
  { name: "Raspberry", code: "#E30B5D" },
  { name: "Raspberry Glace", code: "#915F6D" },
  { name: "Raspberry Pink", code: "#E25098" },
  { name: "Raspberry Rose", code: "#B3446C" },
  { name: "Raven", code: "#727B89" },
  { name: "Raven 2", code: "#141A16" },
  { name: "Raw Sienna", code: "#D27D46" },
  { name: "Raw Umber", code: "#826644" },
  { name: "Razzle Berry", code: "#D92F5E" },
  { name: "Razzle Dazzle Rose", code: "#FF33CC" },
  { name: "Razzmatazz", code: "#E3256B" },
  { name: "Razzmic Berry", code: "#8D4E85" },
  { name: "Rebecca Purple", code: "#663399" },
  { name: "Rebel", code: "#3C1206" },
  { name: "Red", code: "#FF0000" },
  { name: "Red (Ĉ)", code: "#EE204D" },
  { name: "Red (Munsell)", code: "#F2003C" },
  { name: "Red (NCS)", code: "#C40233" },
  { name: "Red (Pantone)", code: "#ED2939" },
  { name: "Red (Pigment)", code: "#ED1C24" },
  { name: "Red (RYB)", code: "#FE2712" },
  { name: "Red Baron", code: "#511D22" },
  { name: "Red Beech", code: "#7B3801" },
  { name: "Red Berry", code: "#8E0000" },
  { name: "Red Brown", code: "#A52A2A" },
  { name: "Red Demask", code: "#DA6A41" },
  { name: "Red Devil", code: "#860111" },
  { name: "Red Hot", code: "#952B32" },
  { name: "Red Leather", code: "#530100" },
  { name: "Red Ochre", code: "#612D2D" },
  { name: "Red Orange", code: "#FF5349" },
  { name: "Red Orange 2", code: "#FF3F34" },
  { name: "Red Oxide", code: "#6E0902" },
  { name: "Red Purple", code: "#E40078" },
  { name: "Red Ribbon", code: "#ED0A3F" },
  { name: "Red Robin", code: "#80341F" },
  { name: "Red Salsa (Ĉ)", code: "#FD3A4A" },
  { name: "Red Stage", code: "#D05F04" },
  { name: "Red Violet", code: "#C71585" },
  { name: "Redcorn", code: "#95001D" },
  { name: "Redden Wood", code: "#880015" },
  { name: "Redwood", code: "#A45A52" },
  { name: "Reef", code: "#C9FFA2" },
  { name: "Reef Gold", code: "#9F821C" },
  { name: "Regal Blue", code: "#013F6A" },
  { name: "Regalia", code: "#522D80" },
  { name: "Regent Gray", code: "#86949F" },
  { name: "Regent St Blue", code: "#AAD6E6" },
  { name: "Registration Black", code: "#000000" },
  { name: "Reindeer Moss Green", code: "#BDBB6E" },
  { name: "Remy", code: "#FEEBF3" },
  { name: "Renegade", code: "#592228" },
  { name: "Reno Sand", code: "#A86515" },
  { name: "Resolution Blue", code: "#002387" },
  { name: "Reunion", code: "#004F98" },
  { name: "Revolver", code: "#2C1632" },
  { name: "Rhapsody", code: "#AD603C" },
  { name: "Rhino", code: "#2E3F62" },
  { name: "Rhodium", code: "#D1D7D7" },
  { name: "Rhythm", code: "#777696" },
  { name: "Rialto", code: "#4C2322" },
  { name: "Rice Cake", code: "#FFFEF0" },
  { name: "Rice Flower", code: "#EEFFE2" },
  { name: "Rice Black", code: "#004040" },
  { name: "Rich Brilliant Lavender", code: "#F1A7FE" },
  { name: "Rich Carmine", code: "#D70040" },
  { name: "Rich Electric Blue", code: "#0892D0" },
  { name: "Rich Gold", code: "#A85307" },
  { name: "Rich Lavender", code: "#A76BCF" },
  { name: "Rich Lilac", code: "#B666D2" },
  { name: "Rich Maroon", code: "#B03060" },
  { name: "Rifle Green", code: "#444C38" },
  { name: "Rio Grande", code: "#BBD009" },
  { name: "Ripe Lemon", code: "#F4D81C" },
  { name: "Ripe Plum", code: "#410056" },
  { name: "Riptide", code: "#8BE6D8" },
  { name: "River Red", code: "#434C59" },
  { name: "Rivergum", code: "#495947" },
  { name: "Riverstone", code: "#797067" },
  { name: "Roadster", code: "#9F2C37" },
  { name: "Roast Coffee", code: "#704241" },
  { name: "Roasted Orange", code: "#A67747" },
  { name: "Rob Roy", code: "#EAC674" },
  { name: "Robin Egg Blue", code: "#00CCCC" },
  { name: "Robin Orange", code: "#DA5820" },
  { name: "Robin Egg Blue (Ĉ)", code: "#1FCECB" },
  { name: "Robin Egg Blue (CS)", code: "#9EAA9E" },
  { name: "Rock", code: "#4D3833" },
  { name: "Rock Blue", code: "#9EB1CD" },
  { name: "Rock Salt", code: "#E6D6B8" },
  { name: "Rock Spray", code: "#BA450C" },
  { name: "Rockbottom", code: "#A29A8E" },
  { name: "Rocket", code: "#86282E" },
  { name: "Rocket Metallic", code: "#8A7F80" },
  { name: "Rockpool Green", code: "#31332C" },
  { name: "Rockstar", code: "#3D3A3C" },
  { name: "Rodeo Dust", code: "#C9B29B" },
  { name: "Roller Coaster", code: "#923830" },
  { name: "Rolling Stone", code: "#747D83" },
  { name: "Roman", code: "#DE6360" },
  { name: "Roman Coffee", code: "#795D4C" },
  { name: "Roman Silver", code: "#838996" },
  { name: "Romance", code: "#FFFEFD" },
  { name: "Romance Grey", code: "#F4F0E6" },
  { name: "Romantic", code: "#FFD2B7" },
  { name: "Ronchi", code: "#ECC54E" },
  { name: "Roof Light Terracotta", code: "#A14743" },
  { name: "Roof Terracotta", code: "#A62F20" },
  { name: "Rookwood Red", code: "#723F3E" },
  { name: "Root Beer", code: "#814D30" },
  { name: "Rope", code: "#8E4D1E" },
  { name: "Rose", code: "#FF007F" },
  { name: "Rose 2", code: "#FF5050" },
  { name: "Rose 3", code: "#F03865" },
  { name: "Rose (CS)", code: "#D3A194" },
  { name: "Rose Bonbon", code: "#F9429E" },
  { name: "Rose Bud", code: "#FBB2A3" },
  { name: "Rose Bud Cherry", code: "#800B47" },
  { name: "Rose Dust", code: "#9E5E6F" },
  { name: "Rose Ebony", code: "#674846" },
  { name: "Rose Fog", code: "#E7BCB4" },
  { name: "Rose Gold", code: "#B76E79" },
  { name: "Rose Madder", code: "#E32636" },
  { name: "Rose of Sharon", code: "#BF5500" },
  { name: "Rose Pink", code: "#FF66CC" },
  { name: "Rose Quartz", code: "#AA98A9" },
  { name: "Rose Red", code: "#C21E56" },
  { name: "Rose Taupe", code: "#905D5D" },
  { name: "Rose Vale", code: "#AB4E52" },
  { name: "Rose White", code: "#FFF6F5" },
  { name: "Rosemary", code: "#FFA7A6" },
  { name: "Rosemary Leaves", code: "#748C42" },
  { name: "Rosemary Purple", code: "#9E84C5" },
  { name: "Rosewood", code: "#65000B" },
  { name: "Rossa Corsa", code: "#D40000" },
  { name: "Rosy Brown", code: "#BC8F8F" },
  { name: "Roti", code: "#C6A84B" },
  { name: "Rouge", code: "#A23B6C" },
  { name: "Royal Azure", code: "#0038A8" },
  { name: "Royal Blue (Traditional)", code: "#002366" },
  { name: "Royal Blue", code: "#4196E1" },
  { name: "Royal Brown", code: "#523B35" },
  { name: "Royal Fuchsia", code: "#CA2C92" },
  { name: "Royal Green", code: "#136207" },
  { name: "Royal Heath", code: "#AB3472" },
  { name: "Royal Orange", code: "#F99245" },
  { name: "Royal Pink", code: "#D73895" },
  { name: "Royal Purple", code: "#7851A9" },
  { name: "Royal Red", code: "#9B1C31" },
  { name: "Royal Yellow", code: "#FADA5E" },
  { name: "Rubber Duck Yellow", code: "#FBE108" },
  { name: "Ruber", code: "#CE4676" },
  { name: "Ruby", code: "#E0115F" },
  { name: "Ruby Red", code: "#9B111E" },
  { name: "Ruddy", code: "#FF0028" },
  { name: "Ruddy Brown", code: "#BB6528" },
  { name: "Ruddy Pink", code: "#E18E96" },
  { name: "Rufose", code: "#A81C07" },
  { name: "Rum", code: "#A1750D" },
  { name: "Rum Swizzle", code: "#F9F8E4" },
  { name: "Russet", code: "#80461B" },
  { name: "Rust", code: "#B7410E" },
  { name: "Rustic Red", code: "#480404" },
  { name: "Rusty Nail", code: "#86560A" },
  { name: "Rusty Red", code: "#DA2C43" },
];

const letterQ = [
  { name: "Quagmire", code: "#736657" },
  { name: "Quail Egg", code: "#ECE4D5" },
  { name: "Quail Ridge", code: "#ACA396" },
  { name: "Quail Cottage", code: "#ABA497" },
  { name: "Quaker Grey", code: "#86837E" },
  { name: "Quaking Grass", code: "#BFC2A1" },
  { name: "Quantum Green", code: "#7C948B" },
  { name: "Quantum Haze", code: "#B1B8CC" },
  { name: "Quantum Leap", code: "#8BB2C5" },
  { name: "Quark", code: "#404572" },
  { name: "Quark White", code: "#E7F1E6" },
  { name: "Quarried Limestone", code: "#EBE6D6" },
  { name: "Quarry Beige", code: "#D2C2B4" },
  { name: "Quarry Pond", code: "#255970" },
  { name: "Quarry Stone", code: "#7B745E" },
  { name: "Quarter Dutch White", code: "#FBF4DF" },
  { name: "Quarter Imagine", code: "#CBC2BE" },
  { name: "Quarter Pearl Lusta", code: "#FFFDF4" },
  { name: "Quarter Silver Sand", code: "#D3D0CA" },
  { name: "Quarter Spanish White", code: "#F7F2E1" },
  { name: "Quarter Tasman", code: "#D8DCD5" },
  { name: "Quarterback", code: "#282B3C" },
  { name: "Quartile", code: "#4CBB17" },
  { name: "Quartz", code: "#51484E" },
  { name: "Quartz 2", code: "#FFE4E1" },
  { name: "Quartz Amertrine", code: "#DED1E0" },
  { name: "Quartz Blush", code: "#E5B8B2" },
  { name: "Quartz Green", code: "#6E7C45" },
  { name: "Quartz Ochre", code: "#AA8A58" },
  { name: "Quartz Pink", code: "#BCA3AA" },
  { name: "Quartz Rose", code: "#E7BFB3" },
  { name: "Quartz Stone (Behr)", code: "#E9E7E3" },
  { name: "Quartz Stone (Benjamin Moore)", code: "#CEE7DB" },
  { name: "Quartz Violet", code: "#B5A2BC" },
  { name: "Quasar", code: "#A17D60" },
  { name: "Quayside", code: "#424F71" },
  { name: "Quebec Blue", code: "#59666F" },
  { name: "Quebec Calm", code: "#F6DDE5" },
  { name: "Queen Anne's Lace (Behr)", code: "#E3E5DF" },
  { name: "Queen Anne's Lace (PPG)", code: "#F3ECDD" },
  { name: "Queen Anne's Lace (Sherwin Williams)", code: "#EEEBD5" },
  { name: "Queen Blue", code: "#436B95" },
  { name: "Queen Coral (Fuller O'Brien)", code: "#F0C6B5" },
  { name: "Queen Coral (PPG)", code: "#DD7174" },
  { name: "Queen Mintey", code: "#3EB489" },
  { name: "Queen Pink", code: "#E8CCD7" },
  { name: "Queenly", code: "#D3ABCD" },
  { name: "Queenly Laugh", code: "#FAEBD1" },
  { name: "Queen's Tart", code: "#D0BAC6" },
  { name: "Queen's Violet (Behr)", code: "#CAB7C3" },
  { name: "Queen's Violet (Ralph Lauren)", code: "#2D3255" },
  { name: "Queen's Wreath (General Paint)", code: "#3F4B71" },
  { name: "Queen's Wreath (Matthews Paint)", code: "#788196" },
  { name: "Queen's Teal (Matthews Paint)", code: "#007E74" },
  { name: "Queen's Silver", code: "#A6A6A6" },
  { name: "Quicksand", code: "#BD978E" },
  { name: "Quicksilver (CS)", code: "#889A97" },
  { name: "Quicksilver (PPG)", code: "#909DA5" },
  { name: "Quiet Earth", code: "#8C6A4E" },
  { name: "Quiet Moment", code: "#94ADB0" },
  { name: "Quiet Nest", code: "#CFE1CC" },
  { name: "Quiet on the Set", code: "#E3E1DF" },
  { name: "Quiet Refuge", code: "#B79C98" },
  { name: "Quiet Shore", code: "#F4E8D4" },
  { name: "Quiet Storm", code: "#185166" },
  { name: "Quiet Teal", code: "#AABAB2" },
  { name: "Quiet Times", code: "#B7BBB7" },
  { name: "Quiet Veranda", code: "#EED3A8" },
  { name: "Quiet Whisper", code: "#F2F2E8" },
  { name: "Quiet Willow Metal", code: "#8B8B82" },
  { name: "Quiet Willow Vinyl", code: "#81837B" },
  { name: "Quietude (Behr)", code: "#E6E8E7" },
  { name: "Quietude (Sherwin Williams)", code: "#AAB9B1" },
  { name: "Quill Gray", code: "#D6D6D1" },
  { name: "Quilted", code: "#D7D9D2" },
  { name: "Quilted Bag", code: "#D29565" },
  { name: "Quilted Gold", code: "#EBC469" },
  { name: "Quilted Heart", code: "#CE98B3" },
  { name: "Quilter's Thread", code: "#E7DCCC" },
  { name: "Quinacridone Magenta", code: "#8E3A59" },
  { name: "Quinacridone Red Violet", code: "#740055" },
  { name: "Quinacridone Rose Violet", code: "#8E304B" },
  { name: "Quince", code: "#EFB85B" },
  { name: "Quince Apple", code: "#EED67D" },
  { name: "Quince Berry", code: "#946A89" },
  { name: "Quince Blossom", code: "#D79381" },
  { name: "Quince Cream", code: "#EECB8A" },
  { name: "Quince Gold", code: "#F6CC86" },
  { name: "Quince Green", code: "#8DC27F" },
  { name: "Quince Harvest", code: "#E9DD86" },
  { name: "Quince Jelly", code: "#F4CDAB" },
  { name: "Quince Yellow", code: "#F6DFA3" },
  { name: "Quincy", code: "#623F2D" },
  { name: "Quincy Granite", code: "#B2B2AD" },
  { name: "Quirky Gold", code: "#A4773D" },
  { name: "Quite Lilac", code: "#9791C7" },
  { name: "Quiver Tan", code: "#8F7F6A" },
  { name: "QuoJax Blue", code: "#053A6C" },
  { name: "Quondong", code: "#A45F29" },
];

const letterP = [
  { name: "Paarl", code: "#A65529" },
  { name: "Pablo", code: "#776F61" },
  { name: "Pacific Blue", code: "#009DC4" },
  { name: "Pacifika", code: "#778120" },
  { name: "Pacman", code: "#FFCC00" },
  { name: "Paco", code: "#411F10" },
  { name: "Padua", code: "#ADE6C4" },
  { name: "Painted Park", code: "#90C090" },
  { name: "Pakistan Green", code: "#006600" },
  { name: "Palatinate Blue", code: "#273BE2" },
  { name: "Palatinate Purple", code: "#682860" },
  { name: "Pale Aqua", code: "#BCD4E6" },
  { name: "Pale Blue", code: "#AFEEEE" },
  { name: "Pale Canary", code: "#FFFF99" },
  { name: "Pale Gold", code: "#E6BE8A" },
  { name: "Pale Green", code: "#98FB98" },
  { name: "Pale Leaf", code: "#C0D3B9" },
  { name: "Pale Magenta", code: "#F984E5" },
  { name: "Pale Oyster", code: "#988D77" },
  { name: "Pale Prim", code: "#FDFEB8" },
  { name: "Pale Red", code: "#EC5A5A" },
  { name: "Pale Rose", code: "#FFE1F2" },
  { name: "Pale Silver", code: "#C9C0BB" },
  { name: "Pale Sky", code: "#6E7783" },
  { name: "Pale Slate", code: "#C3BFC1" },
  { name: "Pale Spring Bud", code: "#ECEBBD" },
  { name: "Pale Taupe", code: "#BC987E" },
  { name: "Pale Violet", code: "#CC99FF" },
  { name: "Pale Yellow", code: "#E6D69B" },
  { name: "Palladium", code: "#79846A" },
  { name: "Palm Green", code: "#09230F" },
  { name: "Palm Leaf", code: "#6F9940" },
  { name: "Pampas", code: "#F4F2EE" },
  { name: "Panache", code: "#EAF6EE" },
  { name: "Pancho", code: "#EDCDA8" },
  { name: "Pansy Lavender", code: "#7E648B" },
  { name: "Pansy Purple", code: "#78184A" },
  { name: "Paolo Veronese Green", code: "#009B7D" },
  { name: "Papaya", code: "#F7A100" },
  { name: "Paper", code: "#FEF8EC" },
  { name: "Paprika", code: "#8D0226" },
  { name: "Paradise", code: "#009DE2" },
  { name: "Paradise Pink", code: "#E63E62" },
  { name: "Paradiso", code: "#317D82" },
  { name: "Parchment", code: "#F1E9D2" },
  { name: "Paris Blue", code: "#192169" },
  { name: "Paris Daisy", code: "#FFF46E" },
  { name: "Paris Green", code: "#50C878" },
  { name: "Paris White", code: "#CADCD4" },
  { name: "Parrot", code: "#E91B27" },
  { name: "Parsley", code: "#134F19" },
  { name: "Passion Fruit Juice", code: "#838518" },
  { name: "Pastel Blue", code: "#AEC6CF" },
  { name: "Pastel Brown", code: "#836953" },
  { name: "Pastel Gray", code: "#CFCFC4" },
  { name: "Pastel Green", code: "#77DD77" },
  { name: "Pastel Magenta", code: "#F49AC2" },
  { name: "Pastel Orange", code: "#FFB347" },
  { name: "Pastel Pink", code: "#FFD1DC" },
  { name: "Pastel Purple", code: "#B39EB5" },
  { name: "Pastel Red", code: "#FF6961" },
  { name: "Pastel Violet", code: "#CB99C9" },
  { name: "Pastel Yellow", code: "#FDFD96" },
  { name: "Patina", code: "#639A8F" },
  { name: "Patriarch", code: "#800080" },
  { name: "Patrick", code: "#F88870" },
  { name: "Paua", code: "#260368" },
  { name: "Pavlova", code: "#D7C498" },
  { name: "Payne", code: "#40404F" },
  { name: "Pea", code: "#99BD4B" },
  { name: "Peach", code: "#FFCBA4" },
  { name: "Peacock", code: "#23B3E7" },
  { name: "Peanut", code: "#782F16" },
  { name: "Pear", code: "#D1E231" },
  { name: "Pearl", code: "#EAE0C8" },
  { name: "Pearl Aqua", code: "#88D8C0" },
  { name: "Pearl Blue", code: "#5A6F9C" },
  { name: "Pearl Bush", code: "#E8E0D5" },
  { name: "Pearl Gold", code: "#D9BF62" },
  { name: "Pearl Green", code: "#7BC621" },
  { name: "Pearl Lusta", code: "#FCF4DC" },
  { name: "Pearl Pink", code: "#BDA2B5" },
  { name: "Pearl Red", code: "#9F8C90" },
  { name: "Pearl Silver", code: "#A9AAA5" },
  { name: "Pearl Sparkle", code: "#FBFAF5" },
  { name: "Pearl White", code: "#F7F7F7" },
  { name: "Pearl Yellow", code: "#EEEBEB" },
  { name: "Peat", code: "#716B56" },
  { name: "Pebble Blue", code: "#4D7CCC" },
  { name: "Pelorous", code: "#3EABBF" },
  { name: "Pencil Lead", code: "#282828" },
  { name: "Peony Pink", code: "#E74173" },
  { name: "Peppercorn", code: "#291F21" },
  { name: "Peppermint", code: "#379503" },
  { name: "Pepperoni", code: "#D33B24" },
  { name: "Perano", code: "#A9BEF2" },
  { name: "Perfume", code: "#D0BEF8" },
  { name: "Peridot", code: "#E6E200" },
  { name: "Periglacial Blue", code: "#ACB6B2" },
  { name: "Periwinkle", code: "#CCCCFF" },
  { name: "Permanent Brown Madder", code: "#AC2A2C" },
  { name: "Persian Blue", code: "#1C39BB" },
  { name: "Persimmon", code: "#EC5800" },
  { name: "Personal", code: "#2E3538" },
  { name: "Peru", code: "#CD853F" },
  { name: "Peru Tan", code: "#7F3A02" },
  { name: "Pesto", code: "#7C7631" },
  { name: "Petal Pink", code: "#E5ADC8" },
  { name: "Petite Orchid", code: "#DB9690" },
  { name: "Petrol Blue", code: "#037387" },
  { name: "Pewter", code: "#96A8A1" },
  { name: "Pharlap", code: "#A3807B" },
  { name: "Pheo", code: "#CCA59E" },
  { name: "Philippine Blue", code: "#0038A7" },
  { name: "Philippine Gold", code: "#B17304" },
  { name: "Phlox", code: "#DF00FF" },
  { name: "Phthalo Blue", code: "#000F89" },
  { name: "Phthalo Green", code: "#123524" },
  { name: "Picasso", code: "#FFF39D" },
  { name: "Pickle", code: "#998D1F" },
  { name: "Picton Blue", code: "#45B1E8" },
  { name: "Pictorial Carmine", code: "#C30B4E" },
  { name: "Pig", code: "#F8BFB4" },
  { name: "Pigeon Post", code: "#AFBDD9" },
  { name: "Pigment Indigo", code: "#4B0082" },
  { name: "Pikachu Yellow", code: "#F0E943" },
  { name: "Pine Tree", code: "#171F04" },
  { name: "Pineapple", code: "#FCF477" },
  { name: "Pink", code: "#D74894" },
  { name: "Pink Chiffon", code: "#FCE1E8" },
  { name: "Pink Flamingo", code: "#FF66FF" },
  { name: "Pink Flare", code: "#E1C0C8" },
  { name: "Pink Lace", code: "#FFDDF4" },
  { name: "Pink Lady", code: "#FFF1D8" },
  { name: "Pink Pearl", code: "#E7ACCF" },
  { name: "Pink Raspberry", code: "#980036" },
  { name: "Pink Salmon", code: "#FF91A4" },
  { name: "Pink Sherbet", code: "#F78FA7" },
  { name: "Pink Swan", code: "#BEB5B7" },
  { name: "Piper", code: "#C96323" },
  { name: "Pirate Gold", code: "#BA7F03" },
  { name: "Pistachio", code: "#93C572" },
  { name: "Pixie Green", code: "#C0D8B6" },
  { name: "Pizza", code: "#C99415" },
  { name: "Platinum", code: "#E5E4E2" },
  { name: "Playskool", code: "#E51837" },
  { name: "Plover", code: "#C9B9AB" },
  { name: "Plum", code: "#8E4585" },
  { name: "Plump Purple", code: "#5946B2" },
  { name: "Pohutukawa", code: "#8F021C" },
  { name: "Polar", code: "#E5F9F6" },
  { name: "Polished Pine", code: "#5DA493" },
  { name: "Polo Blue", code: "#8DA8CC" },
  { name: "Pomegranate", code: "#F34723" },
  { name: "Pompadour", code: "#660045" },
  { name: "Poodleskirt Pink", code: "#FABFD1" },
  { name: "Poppy", code: "#FF5733" },
  { name: "Popstar", code: "#BE4F62" },
  { name: "Porcelain", code: "#EFF2F3" },
  { name: "Porsche", code: "#EAAE69" },
  { name: "Portafino", code: "#FFFFB4" },
  { name: "Portage", code: "#8B9FEE" },
  { name: "Portica", code: "#F9E663" },
  { name: "Pot Pourri", code: "#F5E7E2" },
  { name: "Potters Clay", code: "#8C5738" },
  { name: "Powder Blue", code: "#B0E0E6" },
  { name: "Powerhouse", code: "#0FABDA" },
  { name: "Prairie Sand", code: "#9A3820" },
  { name: "Prelude", code: "#D0C0E5" },
  { name: "Prim", code: "#F0E2EC" },
  { name: "Primrose", code: "#E28EA8" },
  { name: "Princess Perfume", code: "#FF85CF" },
  { name: "Provincial Pink", code: "#FEF5F1" },
  { name: "Prune", code: "#701C1C" },
  { name: "Prussian Blue", code: "#003153" },
  { name: "Puce", code: "#CC8899" },
  { name: "Pueblo", code: "#7D2C14" },
  { name: "Puerto Rico", code: "#3FC1AA" },
  { name: "Pullman Brown", code: "#644117" },
  { name: "Pullman Green", code: "#3B331C" },
  { name: "Pumice", code: "#C2CAC4" },
  { name: "Pumpkin", code: "#FF7518" },
  { name: "Punch", code: "#DC4333" },
  { name: "Purple", code: "#9F00C5" },
  { name: "Purple Blue", code: "#9873DC" },
  { name: "Purple Cabbage", code: "#3A144F" },
  { name: "Purple Cow", code: "#9A76B6" },
  { name: "Purple Mountain Majesty", code: "#9678B6" },
  { name: "Purple Navy", code: "#4E5180" },
  { name: "Purple Taupe", code: "#50404D" },
  { name: "Purpure", code: "#89395E" },
  { name: "Purwa", code: "#9BE1FF" },
  { name: "Putty", code: "#E7CD8C" },
];

const letterO = [
  { name: "Oak", code: "#4F2412" },
  { name: "Oak (CS)", code: "#78512D" },
  { name: "Oak Brown", code: "#B46834" },
  { name: "Oasis", code: "#FEEFCE" },
  { name: "Obelisk", code: "#617274" },
  { name: "Observatory", code: "#02866F" },
  { name: "Obsidian", code: "#353A3E" },
  { name: "Obsidian 2", code: "#0F0F16" },
  { name: "Obsidian 3", code: "#341B17" },
  { name: "Ocean", code: "#0076B8" },
  { name: "Ocean Blue", code: "#138FCF" },
  { name: "Ocean Blue Pearl", code: "#4F42B5" },
  { name: "Ocean Boat Blue", code: "#0077BE" },
  { name: "Ocean Dark Blue", code: "#004765" },
  { name: "Ocean Green", code: "#41AA78" },
  { name: "Ocean Green Pearl", code: "#48BF91" },
  { name: "Ocean Light Blue", code: "#33B5C2" },
  { name: "Ochre", code: "#CC7722" },
  { name: "Odyssey", code: "#4F6D69" },
  { name: "Off Green", code: "#E6F8F3" },
  { name: "Off Green 2", code: "#DFF0E2" },
  { name: "Off Piste", code: "#AFACA0" },
  { name: "Off Road", code: "#DEAA88" },
  { name: "Off White", code: "#F8F0E3" },
  { name: "Off White Pearl", code: "#CBC2B9" },
  { name: "Off White Yellow", code: "#FFFEF8" },
  { name: "Off Yellow", code: "#FEF9E3" },
  { name: "Office Green", code: "#008000" },
  { name: "Ogre", code: "#C9D21D" },
  { name: "Ogre Odor", code: "#FD5240" },
  { name: "Oh Behave", code: "#BE523F" },
  { name: "Oil", code: "#281E15" },
  { name: "Oiled Cedar", code: "#66362D" },
  { name: "Oilskin", code: "#555349" },
  { name: "Okey Donkey", code: "#BCA184" },
  { name: "Old Brick", code: "#901E1E" },
  { name: "Old Burgundy", code: "#43302E" },
  { name: "Old Canvas", code: "#C1A370" },
  { name: "Old Copper", code: "#724A2F" },
  { name: "Old Gold", code: "#CFB53B" },
  { name: "Old Heliotrope", code: "#563C5C" },
  { name: "Old Lace", code: "#FDF5E6" },
  { name: "Old Lavender", code: "#796878" },
  { name: "Old Mauve", code: "#673147" },
  { name: "Old Moss Green", code: "#867E36" },
  { name: "Old Rose", code: "#C08081" },
  { name: "Old Silver", code: "#848482" },
  { name: "Olive", code: "#808000" },
  { name: "Olive Drab", code: "#6B8E23" },
  { name: "Olive Drab 2", code: "#3C341F" },
  { name: "Olive Green", code: "#B5B35C" },
  { name: "Olive Green (CS)", code: "#353F2A" },
  { name: "Olive Green (Ĉ)", code: "#BAB86C" },
  { name: "Olive Haze", code: "#8B8470" },
  { name: "Olive Haze (CS)", code: "#888064" },
  { name: "Olive Skin", code: "#D48D3D" },
  { name: "Olivetone", code: "#716E10" },
  { name: "Olivine", code: "#9AB973" },
  { name: "Onahau", code: "#CDF4FF" },
  { name: "Onion", code: "#2F270E" },
  { name: "Onion Purple", code: "#602B35" },
  { name: "Onion Yellow", code: "#EA9B50" },
  { name: "Onyx", code: "#353839" },
  { name: "Ooh La La", code: "#A088A6" },
  { name: "Oopsy Daisy", code: "#FFD67B" },
  { name: "Opal", code: "#A9C6C2" },
  { name: "Opera Mauve", code: "#B784A7" },
  { name: "Opium", code: "#8E6F70" },
  { name: "Opium Red", code: "#F04F57" },
  { name: "Opium Tar", code: "#131F09" },
  { name: "Optimist", code: "#2B688D" },
  { name: "Oracle", code: "#377475" },
  { name: "Oracle Blue", code: "#395555" },
  { name: "Orange", code: "#FF7F00" },
  { name: "Orange 2", code: "#FB9902" },
  { name: "Orange 3", code: "#FFA500" },
  { name: "Orange 4", code: "#FF681F" },
  { name: "Orange 5", code: "#FF8866" },
  { name: "Orange (Ĉ)", code: "#FF7538" },
  { name: "Orange (Crayola)", code: "#FF5800" },
  { name: "Orange Juice", code: "#FBB519" },
  { name: "Orange Peel", code: "#FF9F00" },
  { name: "Orange Peel 2", code: "#FFA000" },
  { name: "Orange Red", code: "#FF4500" },
  { name: "Orange Red (Ĉ)", code: "#FF2B2B" },
  { name: "Orange Roughy", code: "#C45719" },
  { name: "Orange Roughy Red", code: "#A85335" },
  { name: "Orange Soda", code: "#FA5B3D" },
  { name: "Orange White", code: "#FEFCED" },
  { name: "Orange White (CS)", code: "#EAE3CD" },
  { name: "Orange Yellow (Ĉ)", code: "#F8D568" },
  { name: "Orangey Red", code: "#FF3F00" },
  { name: "Orangey Yellow", code: "#FFBF00" },
  { name: "Orbit", code: "#874748" },
  { name: "Orchid", code: "#DA70D6" },
  { name: "Orchid (Ĉ)", code: "#E6A8D7" },
  { name: "Orchid (Ĉ) 2", code: "#BC6CAC" },
  { name: "Orchid (Ĉ) 3", code: "#CC00FF" },
  { name: "Orchid Pearl", code: "#7B4259" },
  { name: "Orchid Pink", code: "#F2BDCD" },
  { name: "Orchid White", code: "#FFFDF3" },
  { name: "Oregano", code: "#787444" },
  { name: "Oregano Green", code: "#4F7949" },
  { name: "Oregon", code: "#9B4703" },
  { name: "Oregon Brown", code: "#B16C39" },
  { name: "Orient", code: "#255B77" },
  { name: "Oriental Blue", code: "#355D9A" },
  { name: "Oriental Green", code: "#158265" },
  { name: "Oriental Pink", code: "#C69191" },
  { name: "Orinoco", code: "#F3FBD4" },
  { name: "Orinoco Gray", code: "#D2D3B3" },
  { name: "Orioles Orange", code: "#FB4F14" },
  { name: "Orpiment", code: "#EEBD34" },
  { name: "Oscar Award", code: "#C1B46E" },
  { name: "Oslo Gray", code: "#878D91" },
  { name: "Otter", code: "#8F7B70" },
  { name: "Otter Brown", code: "#654321" },
  { name: "Ottoman", code: "#E9F8ED" },
  { name: "Ottoman Gray", code: "#D2DBCB" },
  { name: "OU Crimson Red", code: "#990000" },
  { name: "Outback", code: "#95826C" },
  { name: "Outer Space", code: "#414A4C" },
  { name: "Outer Space 2", code: "#2D383A" },
  { name: "Outer Space (CS)", code: "#1F263B" },
  { name: "Outrageous Orange", code: "#FF6E4A" },
  { name: "Outrageous Orange 2", code: "#FF6037" },
  { name: "Oxblood", code: "#91573F" },
  { name: "Oxford Blue", code: "#002147" },
  { name: "Oxford Blue 2", code: "#384555" },
  { name: "Oxford Dark Blue", code: "#28353A" },
  { name: "Oxley", code: "#779E86" },
  { name: "Oxygen", code: "#BBC6D5" },
  { name: "Oxymoron", code: "#9CBFE3" },
  { name: "Oyster", code: "#D7C9B1" },
  { name: "Oyster Bay", code: "#DAFAFF" },
  { name: "Oyster Pink", code: "#E9CECD" },
  { name: "Oyster Pink (CS)", code: "#D4B5B0" },
  { name: "Ozone", code: "#47634B" },
];

const letterN = [
  { name: "Nadeshiko Pink", code: "#F6ADC6" },
  { name: "Nala", code: "#412F28" },
  { name: "Namakabe-iro", code: "#785E49" },
  { name: "Nandor", code: "#4B5D52" },
  { name: "Nanohanacha", code: "#E3B130" },
  { name: "Napa", code: "#ACA494" },
  { name: "Napa Red", code: "#7B4A45" },
  { name: "Naphthol Red", code: "#BE2333" },
  { name: "Napier Green", code: "#2A8000" },
  { name: "Naples Yellow", code: "#FADA5E" },
  { name: "Narvik", code: "#EDF9F1" },
  { name: "Narshi Pear Beige", code: "#EDD4B1" },
  { name: "Nataneyu-iro", code: "#A17917" },
  { name: "Nato Blue", code: "#153043" },
  { name: "Natural", code: "#A2A4A1" },
  { name: "Natural (CS)", code: "#885931" },
  { name: "Natural Grey", code: "#8B8680" },
  { name: "Natural Indigo", code: "#003740" },
  { name: "Natural Rice Beige", code: "#DCC39F" },
  { name: "Natural Silk Grey", code: "#D3C5C0" },
  { name: "Natural White", code: "#FBEDE5" },
  { name: "Navajo White", code: "#FFDEAD" },
  { name: "Navarone", code: "#B9A584" },
  { name: "Navy", code: "#000080" },
  { name: "Navy Black", code: "#263032" },
  { name: "Navy Blue", code: "#1974D2" },
  { name: "Navy Purple", code: "#9457EB" },
  { name: "Nebula", code: "#CBDBD6" },
  { name: "Nebula 2", code: "#C92442" },
  { name: "Nectar Red", code: "#7F4C64" },
  { name: "Negroni", code: "#FFE2C5" },
  { name: "Nelson Red", code: "#4F2525" },
  { name: "Nemo", code: "#B1B9D3" },
  { name: "Neon", code: "#41B972" },
  { name: "Neon Blue", code: "#0E9DEB" },
  { name: "Neon Blue 2", code: "#1B03A3" },
  { name: "Neon Brown", code: "#C3732A" },
  { name: "Neon Carrot", code: "#FFA343" },
  { name: "Neon Carrot 2", code: "#FF9933" },
  { name: "Neon Chartreuse", code: "#D5CF31" },
  { name: "Neon Coral", code: "#D65538" },
  { name: "Neon Cyan", code: "#00FEFC" },
  { name: "Neon Fuchsia", code: "#FE4164" },
  { name: "Neon Gold", code: "#CFAA01" },
  { name: "Neon Green", code: "#39FF14" },
  { name: "Neon Hot Pink", code: "#F43E79" },
  { name: "Neon Lime Green", code: "#82D059" },
  { name: "Neon Magenta Pink", code: "#C5488A" },
  { name: "Neon Orange", code: "#FF8E01" },
  { name: "Neon Pink", code: "#FF19B5" },
  { name: "Neon Pink 2", code: "#FE347E" },
  { name: "Neon Purple", code: "#733290" },
  { name: "Neon Red", code: "#CF2727" },
  { name: "Neon Red 2", code: "#FF1818" },
  { name: "Neon Scarlet", code: "#FF2603" },
  { name: "Neon Silver", code: "#CCCCCC" },
  { name: "Neon Tangerine", code: "#F6890A" },
  { name: "Neon Yellow", code: "#F0EF01" },
  { name: "Nepal", code: "#8EABC1" },
  { name: "Neptune", code: "#7CB7BB" },
  { name: "Neptune Blue", code: "#598DE3" },
  { name: "Nero", code: "#140600" },
  { name: "Nero Grey", code: "#252525" },
  { name: "Nest Egg", code: "#4D453A" },
  { name: "Nettle Green", code: "#364C2E" },
  { name: "Neutral Bay", code: "#858D99" },
  { name: "Neutral Gray", code: "#85807D" },
  { name: "Neutral Green", code: "#AAA583" },
  { name: "Neva", code: "#CC6D6D" },
  { name: "Nevada", code: "#646E75" },
  { name: "New Amber", code: "#6D3B24" },
  { name: "New Car", code: "#214FC6" },
  { name: "New Denim Blue", code: "#394149" },
  { name: "New Green", code: "#B5AC31" },
  { name: "New Orleans", code: "#F3D69D" },
  { name: "New Yellow", code: "#E8C247" },
  { name: "New York Pink", code: "#D7837F" },
  { name: "Niagara", code: "#06A189" },
  { name: "Nickel", code: "#727472" },
  { name: "Nickel Ore Green", code: "#537E7E" },
  { name: "Night Blue", code: "#2F2A5A" },
  { name: "Night Brown", code: "#44281B" },
  { name: "Night Mauve", code: "#5D3B41" },
  { name: "Night Moves", code: "#454C73" },
  { name: "Night Red", code: "#3C2727" },
  { name: "Night Rider", code: "#1F120F" },
  { name: "Night Shadz", code: "#AA375A" },
  { name: "Nightclub", code: "#6A1F44" },
  { name: "Nightshade Violet", code: "#A383AC" },
  { name: "Nikau", code: "#2A4032" },
  { name: "Nile Blue", code: "#193751" },
  { name: "Nile Green", code: "#A9AD99" },
  { name: "Nilotes", code: "#2A2E30" },
  { name: "Nisemurasaki", code: "#43242A" },
  { name: "Nite Life", code: "#1D2134" },
  { name: "Nitro", code: "#978395" },
  { name: "Nobel", code: "#B7B1B1" },
  { name: "Nobel Blue", code: "#697991" },
  { name: "Nobel Grey", code: "#73777F" },
  { name: "Nomad", code: "#BAB1A2" },
  { name: "Nomad 2", code: "#BDAC90" },
  { name: "Nomad Grey", code: "#7E736F" },
  { name: "Non-Photo Blue", code: "#A4DDED" },
  { name: "Noosa", code: "#B78038" },
  { name: "Nordic", code: "#1D393C" },
  { name: "Nordland Light Blue", code: "#96AEC5" },
  { name: "Nori Seaweed Green", code: "#464826" },
  { name: "North Grey", code: "#6A7777" },
  { name: "North Texas Green", code: "#059033" },
  { name: "North Light Grey", code: "#A7AEB4" },
  { name: "Norway", code: "#A8BD9F" },
  { name: "Norwegian Blue", code: "#586483" },
  { name: "Norwester", code: "#48798A" },
  { name: "Noshimehana-iro", code: "#344D56" },
  { name: "Notch Brown", code: "#BC9E82" },
  { name: "November Green", code: "#767764" },
  { name: "Nugget", code: "#C59922" },
  { name: "Nullabor", code: "#907C64" },
  { name: "Nut Brown", code: "#5A3A29" },
  { name: "Nutmeg", code: "#81422C" },
  { name: "Nutria Fur Brown", code: "#514035" },
  { name: "Nyanza", code: "#E9FFDB" },
];
