const letterZ = [
  { name: "Z-Zip", code: "#CBC5B6" },
  { name: "Zachary", code: "#D3A18E" },
  { name: "Zacho Blue", code: "#8FBDD2" },
  { name: "Zadar", code: "#85AAAB" },
  { name: "Zaddick", code: "#8CBEDD" },
  { name: "Zaffer", code: "#29AEB4" },
  { name: "Zaffre", code: "#0014A8" },
  { name: "Zaffre (Samson)", code: "#2D5455" },
  { name: "Zagreb LP-300", code: "#E8DEB0" },
  { name: "Zahara Brown", code: "#77523B" },
  { name: "Zahria", code: "#FFE8C2" },
  { name: "Zaire", code: "#354949" },
  { name: "Zambesi", code: "#303B34" },
  { name: "Zambeze Plains", code: "#49473E" },
  { name: "Zambezi", code: "#685558" },
  { name: "Zambia", code: "#FF9215" },
  { name: "Zamboni", code: "#ECF1EF" },
  { name: "Zanadu", code: "#96B9D9" },
  { name: "Zanah", code: "#DAECD6" },
  { name: "Zane Gray", code: "#5F676E" },
  { name: "Zany Lime", code: "#E8B849" },
  { name: "Zany Pink", code: "#E37284" },
  { name: "Zanzibar", code: "#A7867B" },
  { name: "Zanzibar Brown", code: "#5C453F" },
  { name: "Zanzibar Coast", code: "#6E413C" },
  { name: "Zanzibar Gold", code: "#B58548" },
  { name: "Zanzibar Retreat", code: "#D0AE00" },
  { name: "Zanzibar Spice", code: "#8E7364" },
  { name: "Zappa", code: "#8A8E7D" },
  { name: "Zappo", code: "#C4C0E2" },
  { name: "Zara", code: "#B48784" },
  { name: "Zay Day", code: "#DBD5C2" },
  { name: "Zealand Green", code: "#8DD59F" },
  { name: "Zealander Pine", code: "#DBEEDA" },
  { name: "Zealous", code: "#5AC9CB" },
  { name: "Zealot", code: "#007473" },
  { name: "Zebra Agate", code: "#907366" },
  { name: "Zebra Finch", code: "#CEC5BA" },
  { name: "Zebra Grass", code: "#9C9C82" },
  { name: "Zebra Print Dress", code: "#A38A83" },
  { name: "Zebrano", code: "#BC875D" },
  { name: "Zebulon", code: "#378F85" },
  { name: "Zelia", code: "#D5C0C8" },
  { name: "Zellwood", code: "#764C39" },
  { name: "Zemo's Way", code: "#967667" },
  { name: "Zen", code: "#D2D0AE" },
  { name: "Zen Blue", code: "#A7BBD0" },
  { name: "Zen Commandment", code: "#D5D3C3" },
  { name: "Zen Essence", code: "#C7BEA7" },
  { name: "Zen Garden", code: "#C7CFA2" },
  { name: "Zen Retreat", code: "#5A5A59" },
  { name: "Zenda", code: "#5C5D6B" },
  { name: "Zenful", code: "#DDDACC" },
  { name: "Zenith", code: "#95B9E1" },
  { name: "Zentury Brown", code: "#A14F34" },
  { name: "Zepher", code: "#87967B" },
  { name: "Zephyr", code: "#CE94B5" },
  { name: "Zephyr Blue", code: "#CFDFE6" },
  { name: "Zephyr Green", code: "#83AC82" },
  { name: "Zephyr Hills", code: "#D8D5CC" },
  { name: "Zeppelin", code: "#382A34" },
  { name: "Zermatt White", code: "#DFDBD1" },
  { name: "Zero", code: "#FFDAE2" },
  { name: "Zero Gravity", code: "#BFC4C4" },
  { name: "Zest", code: "#E5841B" },
  { name: "Zest (Eddie Bauer)", code: "#FBDC9A" },
  { name: "Zest (Martha Stewart)", code: "#D47A2A" },
  { name: "Zestful", code: "#94B67F" },
  { name: "Zesty (ICI)", code: "#E6D66D" },
  { name: "Zesty (True Value)", code: "#BA4D3C" },
  { name: "Zesty Apple", code: "#8FA15C" },
  { name: "Zesty Custard", code: "#FFEA8E" },
  { name: "Zesty Lilac", code: "#D7CDE7" },
  { name: "Zesty Lime", code: "#9DA61A" },
  { name: "Zeus", code: "#292319" },
  { name: "Zeus (Ace)", code: "#9E8665" },
  { name: "Zeus Shadow", code: "#855466" },
  { name: "Zeus Temple", code: "#659ACE" },
  { name: "Zibibbo", code: "#51242B" },
  { name: "Ziggurat", code: "#BFDBE2" },
  { name: "Zigzag", code: "#B77149" },
  { name: "Zimbabwe Plains", code: "#888C84" },
  { name: "Zimidar", code: "#645688" },
  { name: "Zin Cluster", code: "#463A39" },
  { name: "Zinc", code: "#919798" },
  { name: "Zinc Blue", code: "#869890" },
  { name: "Zinc Green", code: "#376A64" },
  { name: "Zinc Pink", code: "#F2D7DD" },
  { name: "Zinc White", code: "#E1DBD0" },
  { name: "Zinc-ed", code: "#68706E" },
  { name: "Zinfandel (ICI)", code: "#D5C0B6" },
  { name: "Zing", code: "#E4CB72" },
  { name: "Zinger", code: "#873D42" },
  { name: "Zingy!", code: "#E2CC5E" },
  { name: "Zinnia", code: "#9C6560" },
  { name: "Zinnia Bloom", code: "#C07CA5" },
  { name: "Zinnia Gold", code: "#FFCE76" },
  { name: "Zinnia Scarlet", code: "#FF8696" },
  { name: "Zinnia Yellow", code: "#FFC000" },
  { name: "Zinnwaldite", code: "#EBC2AF" },
  { name: "Zinnwaldite Brown", code: "#2C1608" },
  { name: "Zip Line", code: "#81A599" },
  { name: "Zipline Green", code: "#7A7E63" },
  { name: "Zippered Gray", code: "#B0B5B9" },
  { name: "Zippidy Doo Dah", code: "#E3E6BF" },
  { name: "Zippy Gold", code: "#FAB836" },
  { name: "Zippy Lavender", code: "#C3A1AD" },
  { name: "Zircon", code: "#F4F8FF" },
  { name: "Zirconia Teal", code: "#197576" },
  { name: "Zither", code: "#755A87" },
  { name: "Zoboba", code: "#CC9966" },
  { name: "Zodiac", code: "#413A5D" },
  { name: "Zodiac Blue", code: "#37849E" },
  { name: "Zodiac Gray", code: "#857D7F" },
  { name: "Zodiac Night (ICI)", code: "#006E65" },
  { name: "Zoe", code: "#5C2C3C" },
  { name: "Zoey Island", code: "#C086B0" },
  { name: "Zokine", code: "#43523C" },
  { name: "Zombie", code: "#E4D69B" },
  { name: "Zombie Green", code: "#879E4E" },
  { name: "Zomp", code: "#39A78E" },
  { name: "Zonda Grey", code: "#797372" },
  { name: "Zone grey", code: "#767E80" },
  { name: "Zoom", code: "#47B1B7" },
  { name: "Zora", code: "#FFCA42" },
  { name: "Zobra", code: "#A59B91" },
  { name: "Zoraya Blue", code: "#BCD1D1" },
  { name: "Zorro", code: "#2D3033" },
  { name: "Zucchini (Dulux)", code: "#D3D3BC" },
  { name: "Zucchini Flower", code: "#E79F4D" },
  { name: "Zuccini", code: "#044022" },
  { name: "Zuider Zee", code: "#72C1C4" },
  { name: "Zuli", code: "#656264" },
  { name: "Zulu", code: "#585156" },
  { name: "Zumthor", code: "#EDF6FF" },
  { name: "Zuni Mist", code: "#E1F1E7" },
  { name: "Zuni Turquoise", code: "#06AD8B" },
  { name: "Zunisha", code: "#899BA9" },
  { name: "Zunza", code: "#BFD1BC" },
  { name: "Zurich White", code: "#E7E2DA" },
  { name: "Zutem", code: "#D4AA25" },
];

const letterY = [
  { name: "Yabbada bbadoo", code: "#008B97" },
  { name: "Yachting", code: "#2A5A6E" },
  { name: "Yacht Club Lounge", code: "#597B8C" },
  { name: "Yachting Cat", code: "#3D526A" },
  { name: "Yachtsman", code: "#AAB3B2" },
  { name: "Yaffle Green", code: "#D4CD7C" },
  { name: "Yahoo", code: "#E9D5CC" },
  { name: "Yahoo Gold", code: "#EBB742" },
  { name: "Yak (Siko)", code: "#564337" },
  { name: "Yak Skin", code: "#D5BFB4" },
  { name: "Yale", code: "#80BBDD" },
  { name: "Yale Blue", code: "#0F4D92" },
  { name: "Yam", code: "#CC6600" },
  { name: "Yam (Pantone)", code: "#D2853D" },
  { name: "Yama", code: "#95AEA1" },
  { name: "Yama Light", code: "#48BFA8" },
  { name: "Yamabuki-iro", code: "#FFA400" },
  { name: "Yamabukicha", code: "#CB7E1F" },
  { name: "Yams", code: "#E08A4F" },
  { name: "Yanagicha", code: "#9C8A4D" },
  { name: "Yanagi nezumi", code: "#817B69" },
  { name: "Yanagi susutake", code: "#4D4B3A" },
  { name: "Yanagizome", code: "#8C9E5E" },
  { name: "Yanez", code: "#9A8873" },
  { name: "Yankee", code: "#A1703F" },
  { name: "Yankee Doodle", code: "#4D5D6C" },
  { name: "Yankees Blue", code: "#1C2841" },
  { name: "Yaquil Trail", code: "#C48178" },
  { name: "Yarborough Yellow", code: "#F6DC79" },
  { name: "Yardbird", code: "#DCE7E9" },
  { name: "Yardline", code: "#60BB75" },
  { name: "Yare", code: "#6A81AC" },
  { name: "Yarmouth Gray", code: "#8C8D8D" },
  { name: "Yarmouth Oyster", code: "#DBCCB4" },
  { name: "Yarn (Magnolia)", code: "#CECBC3" },
  { name: "Yarn (Kilz)", code: "#D2CDC4" },
  { name: "Yarrow Blossom", code: "#E8C089" },
  { name: "Yarrow Point", code: "#DCA25C" },
  { name: "Yarrow White", code: "#F3E1BE" },
  { name: "Yasna", code: "#544A50" },
  { name: "Yazoo City Yellow", code: "#FFDE5A" },
  { name: "Yeah Baby", code: "#B3E1EA" },
  { name: "Yearling", code: "#A9896F" },
  { name: "Yearling Peach", code: "#F9CC8C" },
  { name: "Yearning", code: "#CDE8FF" },
  { name: "Yeehaa", code: "#006C98" },
  { name: "Yellow", code: "#FFFF00" },
  { name: "Yellow (Ĉ)", code: "#FCE883" },
  { name: "Yellow (Munsell)", code: "#EFCC00" },
  { name: "Yellow (NCS)", code: "#FFD300" },
  { name: "Yellow (Pantone)", code: "#FEDF00" },
  { name: "Yellow (Process)", code: "#FFEF00" },
  { name: "Yellow (RYB)", code: "#FEFE33" },
  { name: "Yellow Beige", code: "#E3C08D" },
  { name: "Yellow Bouquet", code: "#EFC98F" },
  { name: "Yellow Brick Road", code: "#FFDE81" },
  { name: "Yellow Brown", code: "#BFA785" },
  { name: "Yellow Duckling", code: "#FBE9B5" },
  { name: "Yellow Fauna", code: "#E1CE94" },
  { name: "Yellow Fervor", code: "#FFC04F" },
  { name: "Yellow Grass", code: "#D8D89E" },
  { name: "Yellow Green", code: "#C5E17A" },
  { name: "Yellow green (RAL)", code: "#48A43F" },
  { name: "Yellow Grey", code: "#939176" },
  { name: "Yellow Jacket", code: "#FBC923" },
  { name: "Yellow Jessamine", code: "#FCE8BF" },
  { name: "Yellow Kerchief", code: "#EFC239" },
  { name: "Yellow Metal", code: "#716338" },
  { name: "Yellow Ochre", code: "#C6AE4E" },
  { name: "Yellow Olive", code: "#444337" },
  { name: "Yellow Orange (RAL)", code: "#FFAE42" },
  { name: "Yellow Orange", code: "#DD7907" },
  { name: "Yellow Rose", code: "#FFF000" },
  { name: "Yellow Sea", code: "#FEA904" },
  { name: "Yellow Stone", code: "#F0D390" },
  { name: "Yellow Submarine", code: "#E8D233" },
  { name: "Yellow Sunshine", code: "#FFF700" },
  { name: "Yellow Yarn", code: "#F9EBB7" },
  { name: "Yellow-Green", code: "#9ACD32" },
  { name: "Yellowbelly", code: "#FBCB72" },
  { name: "Yellowish Green", code: "#7FBF00" },
  { name: "Yellowstone", code: "#9A7452" },
  { name: "Yellowstone Gorge", code: "#C0A786" },
  { name: "Yellowtail", code: "#F7E7B4" },
  { name: "Yen", code: "#333333" },
  { name: "Yen Blue", code: "#000033" },
  { name: "Yen Green", code: "#003300" },
  { name: "Yen Magenta", code: "#330033" },
  { name: "Yen Red", code: "#330000" },
  { name: "Yen Yellow", code: "#333300" },
  { name: "Yen Mickey!", code: "#516F45" },
  { name: "Yesterday", code: "#EFEEEC" },
  { name: "Yesterday's Roses", code: "#D0BCC3" },
  { name: "Yew", code: "#475954" },
  { name: "Yew Green (Benjamin Moore)", code: "#D0C300" },
  { name: "Yew Green (Fuller Obrien)", code: "#ABAD91" },
  { name: "Yield", code: "#FFC22C" },
  { name: "Yin Yang", code: "#6483A4" },
  { name: "Ying Yang", code: "#DADCBE" },
  { name: "Yo-Yo", code: "#EC8A4A" },
  { name: "Yoga Strength", code: "#DBE0C8" },
  { name: "Yolk Yellow", code: "#E4A84C" },
  { name: "York Town", code: "#879AC5" },
  { name: "Yorkshire Teal", code: "#507372" },
  { name: "Yosemite Campfire", code: "#ED4C44" },
  { name: "Yosemite Springs", code: "#B3D6D5" },
  { name: "You Look Mauve-lous", code: "#B0A9AE" },
  { name: "Young Mermaid", code: "#7B7D5F" },
  { name: "Young Shoot", code: "#FFFFB2" },
  { name: "Your Highness", code: "#B0AEC0" },
  { name: "Your Pink", code: "#FFC3C0" },
  { name: "Your Sanctuary", code: "#D9CDC9" },
  { name: "Your Shadow", code: "#717C8E" },
  { name: "Yours Truly", code: "#F1D4CE" },
  { name: "Youth White", code: "#AACDB3" },
  { name: "Yucatan", code: "#00A0C7" },
  { name: "Yucca", code: "#68786B" },
  { name: "Yucca White", code: "#EDEBD4" },
  { name: "Yukon Gold", code: "#7B6608" },
  { name: "Yukon Gold (Do It Best)", code: "#ECD6AB" },
  { name: "Yukon Sky", code: "#94B2BB" },
  { name: "Yuletime", code: "#95CE96" },
  { name: "Yum Yum Yellow", code: "#F8DF89" },
  { name: "Yuma", code: "#CEC291" },
  { name: "Yuma Gold", code: "#FFC972" },
  { name: "Yuma Sand", code: "#FBF0CF" },
  { name: "Yuma Plummy", code: "#9F7980" },
];
