const shadesOfRed = [
  { name: "Imperial Red", code: "#ED2939", color: "#FFFFFF" },
  { name: "Scarlet", code: "#FF2400", color: "#FFFFFF" },
  { name: "Indian Red", code: "#CD5C5C", color: "#FFFFFF" },
  { name: "Barn Red", code: "#7C0A02", color: "#FFFFFF" },
  { name: "Chili Red", code: "#C21807", color: "#FFFFFF" },
  { name: "Ruby", code: "#E0115F", color: "#FFFFFF" },
  { name: "Maroon", code: "#800000", color: "#FFFFFF" },
  { name: "Fire Brick", code: "#B22222", color: "#FFFFFF" },
  { name: "Redwood", code: "#A45A52", color: "#FFFFFF" },
  { name: "Carmine", code: "#960018", color: "#FFFFFF" },
  { name: "Desire", code: "#EA3C53", color: "#000000" },
  { name: "Vermilion", code: "#7E191B", color: "#FFFFFF" },
  { name: "Raspberry", code: "#D21F3C", color: "#FFFFFF" },
  { name: "Candy Apple", code: "#FF0800", color: "#FFFFFF" },
  { name: "Persian", code: "#CA3433", color: "#FFFFFF" },
  { name: "Hibiscus", code: "#B43757", color: "#FFFFFF" },
  { name: "US Flag", code: "#BF0A30", color: "#FFFFFF" },
  { name: "Ferrari", code: "#FF2800", color: "#FFFFFF" },
  { name: "Sangria", code: "#5E1914", color: "#FFFFFF" },
  { name: "Mahogany", code: "#420D09", color: "#FFFFFF" },
  { name: "Burgundy", code: "#8D021F", color: "#FFFFFF" },
  { name: "Crimson", code: "#B80F0A", color: "#FFFFFF" },
  { name: "Rust", code: "#933A16", color: "#FFFFFF" },
  { name: "Light Salmon", code: "#FFA07A", color: "#000000" },
  { name: "Salmon", code: "#FA8072", color: "#000000" },
  { name: "Dark Salmon", code: "#E9967A", color: "#000000" },
  { name: "Light Coral", code: "#F08080", color: "#000000" },
  { name: "Red", code: "#FF0000", color: "#FFFFFF" },
  { name: "Dark Red", code: "#8B0000", color: "#FFFFFF" },
  { name: "Tomato", code: "#FF6347", color: "#000000" },
  { name: "Orange Red", code: "#FF4500", color: "#FFFFFF" },
  { name: "Pale Violet Red", code: "#DB7093", color: "#000000" },
  { name: "Light Brick", code: "#FB607F", color: "#000000" },
  { name: "Brick", code: "#7E2811", color: "#FFFFFF" },
  { name: "Prismatic Red", code: "#D03D33", color: "#FFFFFF" },
  { name: "Prismatic Legacy", code: "#BA1607", color: "#FFFFFF" },
  { name: "Prismatic Vermilion Renewal", code: "#CA0123", color: "#FFFFFF" },
  { name: "Prismatic Reflection's Shade", code: "#FF3C28", color: "#FFFFFF" },
  { name: "49ers Red", code: "#AA0000", color: "#FFFFFF" },
  { name: "AZ Cardinals Red", code: "#BD2031", color: "#FFFFFF" },
  { name: "Airbnb Red", code: "#FF5A5F", color: "#000000" },
  { name: "Ajax Red", code: "#D2122E", color: "#FFFFFF" },
  { name: "Alabama Crimson", code: "#9E1B32", color: "#FFFFFF" },
  { name: "Alizarin Crimson", code: "#E32636", color: "#FFFFFF" },
  { name: "Amaranth Red", code: "#F4364C", color: "#FFFFFF" },
  { name: "American Rose", code: "#FF033E", color: "#000000" },
  { name: "Angels Red", code: "#BA0021", color: "#FFFFFF" },
  { name: "Almost Apricot Red", code: "#E5B39B", color: "#000000" },
  { name: "Arsenal Red", code: "#DB0007", color: "#FFFFFF" },
  { name: "Auburn Red", code: "#A52A2A", color: "#FFFFFF" },
  { name: "BU Scarlet", code: "#CC0000", color: "#FFFFFF" },
  { name: "Bills Red", code: "#C60C30", color: "#FFFFFF" },
  { name: "Bittersweet Shimmer Red", code: "#BF4F51", color: "#FFFFFF" },
  { name: "Blood Red", code: "#660000", color: "#FFFFFF" },
  { name: "CG Red", code: "#E03C31", color: "#FFFFFF" },
  { name: "Cadmium Red", code: "#E30022", color: "#FFFFFF" },
  { name: "Cardinal Red", code: "#C41E3A", color: "#FFFFFF" },
  { name: "Carnelian Red", code: "#B31B1B", color: "#FFFFFF" },
  { name: "Cerise Red", code: "#DE3163", color: "#FFFFFF" },
  { name: "Chiefs Red", code: "#E31837", color: "#FFFFFF" },
  { name: "Chocolate Cosmos Red", code: "#58111A", color: "#FFFFFF" },
  { name: "Cincinnati Red", code: "#C6011F", color: "#FFFFFF" },
  { name: "Cinnabar Red", code: "#E44D2E", color: "#FFFFFF" },
  { name: "Coke Red", code: "#F40009", color: "#FFFFFF" },
  { name: "Coquelicot Red", code: "#FF3800", color: "#FFFFFF" },
  { name: "Coral Red", code: "#FF7F50", color: "#000000" },
  { name: "Cordovan Red", code: "#893F45", color: "#FFFFFF" },
  { name: "Crayola Red", code: "#EE204D", color: "#FFFFFF" },
  { name: "Electric Crimson", code: "#FF003F", color: "#FFFFFF" },
  { name: "English Red", code: "#AB4B52", color: "#FFFFFF" },
  { name: "Falcons Red", code: "#A71930", color: "#FFFFFF" },
  { name: "Falu Red", code: "#801818", color: "#FFFFFF" },
  { name: "Fire Engine Red", code: "#CE2029", color: "#FFFFFF" },
  { name: "Flame Red", code: "#E25822", color: "#FFFFFF" },
  { name: "Folly Red", code: "#FF004F", color: "#FFFFFF" },
  { name: "French Puce Red", code: "#4E1609", color: "#FFFFFF" },
  { name: "Fuchsia", code: "#FF00FF", color: "#FFFFFF" },
  { name: "Fuzzy Wuzzy Red", code: "#CC6666", color: "#FFFFFF" },
  { name: "Garnet Red", code: "#733635", color: "#FFFFFF" },
  { name: "Harvard Crimson", code: "#A51C30", color: "#FFFFFF" },
  { name: "Hollywood Cerise Red", code: "#F400A1", color: "#FFFFFF" },
  { name: "Husker Red", code: "#E41C38", color: "#FFFFFF" },
  { name: "Japanese Carmine", code: "#9D2933", color: "#FFFFFF" },
  { name: "Jasper Red", code: "#D73B3E", color: "#FFFFFF" },
  { name: "Jelly Bean Red", code: "#DA614E", color: "#FFFFFF" },
  { name: "Kenyan Copper Red", code: "#7C1C05", color: "#FFFFFF" },
  { name: "Lava Red", code: "#CF1020", color: "#FFFFFF" },
  { name: "Liverpool Red", code: "#C8102E", color: "#FFFFFF" },
  { name: "Lust Red", code: "#E62020", color: "#FFFFFF" },
  { name: "MIT Red", code: "#A31F34", color: "#FFFFFF" },
  { name: "Madder Red", code: "#A50021", color: "#FFFFFF" },
  { name: "Pigment Magenta", code: "#FF0090", color: "#FFFFFF" },
  { name: "Manchester United Red", code: "#DA291C", color: "#FFFFFF" },
  { name: "Medium Violet Red", code: "#C71585", color: "#FFFFFF" },
  { name: "Munsell Red", code: "#F2003C", color: "#FFFFFF" },
  { name: "NCS Red", code: "#C40233", color: "#FFFFFF" },
  { name: "Nationals Red", code: "#AB0003", color: "#FFFFFF" },
  { name: "Oklahoma Crimson", code: "#841617", color: "#FFFFFF" },
  { name: "Oxblood Red", code: "#800020", color: "#FFFFFF" },
  { name: "Pastel Red", code: "#FF6961", color: "#FFFFFF" },
  { name: "Penn Red", code: "#990000", color: "#FFFFFF" },
  { name: "Persian Rose Red", code: "#FE28A2", color: "#FFFFFF" },
  { name: "Phillies Red", code: "#E81828", color: "#FFFFFF" },
  { name: "Pigment Red", code: "#ED1C24", color: "#FFFFFF" },
  { name: "Pinterest Red", code: "#E60023", color: "#FFFFFF" },
  { name: "Popstar Red", code: "#BE4F62", color: "#FFFFFF" },
  { name: "Portland Orange Red", code: "#FF5A36", color: "#000000" },
  { name: "Prune Red", code: "#701C1C", color: "#FFFFFF" },
  { name: "Radical Red", code: "#FF355E", color: "#000000" },
  { name: "Red Devil", code: "#860111", color: "#FFFFFF" },
  { name: "Red Sox", code: "#BD3039", color: "#FFFFFF" },
  { name: "Rose Red", code: "#C21E56", color: "#FFFFFF" },
  { name: "Rosewood Red", code: "#65000B", color: "#FFFFFF" },
  { name: "Rufous Red", code: "#A81C07", color: "#FFFFFF" },
  { name: "Russet Red", code: "#80461B", color: "#FFFFFF" },
  { name: "Rusty Red", code: "#DA2C43", color: "#FFFFFF" },
  { name: "Sanguine Red", code: "#BC3F4A", color: "#FFFFFF" },
  { name: "Spanish Red", code: "#E60026", color: "#FFFFFF" },
  { name: "Tango Red", code: "#E4717A", color: "#FFFFFF" },
  { name: "Tawny Red", code: "#CD5700", color: "#FFFFFF" },
  { name: "Tea Rose Red", code: "#F88379", color: "#FFFFFF" },
  { name: "Terracotta Red", code: "#E2725B", color: "#FFFFFF" },
  { name: "Tractor Red", code: "#FD0E35", color: "#FFFFFF" },
  { name: "Turkey Red", code: "#A91101", color: "#FFFFFF" },
  { name: "Tuscan Red", code: "#7C3030", color: "#FFFFFF" },
  { name: "Upsdell Red", code: "#AE2029", color: "#FFFFFF" },
  { name: "Venetian Red", code: "#C80815", color: "#FFFFFF" },
  { name: "Virgin Lust Red", code: "#E4181E", color: "#FFFFFF" },
  { name: "WIne Red", code: "#722F37", color: "#FFFFFF" },
  { name: "Light Red Ochre", code: "#E97451", color: "#000000" },
  { name: "Medium Vermillion", code: "#D9603B", color: "#FFFFFF" },
  { name: "UP Maroon", code: "#7B1113", color: "#FFFFFF" },
  { name: "Outrageous Orange Red", code: "#FF6E4A", color: "#FFFFFF" },
  { name: "Utah Crimson", code: "#D3003F", color: "#FFFFFF" },
];

const shadesOfBlack = [
  { name: "Abbey", code: "#494F55", color: "#FFFFFF" },
  { name: "Ash Grey", code: "#666362", color: "#FFFFFF" },
  { name: "Asphalt", code: "#0C0404", color: "#FFFFFF" },
  { name: "Black", code: "#000000", color: "#FFFFFF" },
  { name: "Black Bean", code: "#3D0C02", color: "#FFFFFF" },
  { name: "Black Cat", code: "#413839", color: "#FFFFFF" },
  { name: "Black Cow", code: "#4C4646", color: "#FFFFFF" },
  { name: "Black Eel", code: "#463E3F", color: "#FFFFFF" },
  { name: "Black Olive", code: "#3B3C36", color: "#FFFFFF" },
  { name: "Charcoal", code: "#36454F", color: "#FFFFFF" },
  { name: "Charleston Green", code: "#232B2B", color: "#FFFFFF" },
  { name: "Dark Jungle Green", code: "#1A2421", color: "#FFFFFF" },
  { name: "Davy's Gray", code: "#555555", color: "#FFFFFF" },
  { name: "Dim Gray", code: "#696969", color: "#FFFFFF" },
  { name: "Ebony", code: "#555D50", color: "#FFFFFF" },
  { name: "Eerie Black", code: "#1B1B1B", color: "#FFFFFF" },
  { name: "Granite", code: "#676767", color: "#FFFFFF" },
  { name: "Gray", code: "#808080", color: "#FFFFFF" },
  { name: "Gray Cloud", code: "#B6B6B4", color: "#FFFFFF" },
  { name: "Gray Wolf", code: "#504A4B", color: "#FFFFFF" },
  { name: "Gunmetal", code: "#2C3539", color: "#FFFFFF" },
  { name: "Iridium", code: "#3D3C3A", color: "#FFFFFF" },
  { name: "Jet", code: "#343434", color: "#FFFFFF" },
  { name: "Licorice", code: "#1A1110", color: "#FFFFFF" },
  { name: "Midnight", code: "#2B1B17", color: "#FFFFFF" },
  { name: "Night", code: "#0C090A", color: "#FFFFFF" },
  { name: "Oil", code: "#3B3131", color: "#FFFFFF" },
  { name: "Old Burgundy", code: "#43302E", color: "#FFFFFF" },
  { name: "Onyx", code: "#353839", color: "#FFFFFF" },
  { name: "Outer Space", code: "#414A4C", color: "#FFFFFF" },
  { name: "Raisin Black", code: "#242124", color: "#FFFFFF" },
  { name: "Smoky Black", code: "#100C08", color: "#FFFFFF" },
  { name: "Taupe", code: "#483C32", color: "#FFFFFF" },
  { name: "Vampire Gray", code: "#565051", color: "#FFFFFF" },
  { name: "Black Leather Jacket", code: "#253529", color: "#FFFFFF" },
  { name: "Cafe Americano", code: "#362819", color: "#FFFFFF" },
  { name: "Blackberry", code: "#3A3A38", color: "#FFFFFF" },
  { name: "Lamp Black", code: "#2E473B", color: "#FFFFFF" },
  { name: "Army Uniform", code: "#353F3E", color: "#FFFFFF" },
  { name: "Slate", code: "#26282A", color: "#FFFFFF" },
  { name: "Pitch Black", code: "#27251F", color: "#FFFFFF" },
  { name: "Spider", code: "#040200", color: "#FFFFFF" },
  { name: "metal", code: "#0E0C0A", color: "#FFFFFF" },
  { name: "Grease", code: "#080806", color: "#FFFFFF" },
  { name: "Crow", code: "#0D0907", color: "#FFFFFF" },
  { name: "Black Rock", code: "#010127", color: "#FFFFFF" },
  { name: "Basalt Black", code: "#4D423E", color: "#FFFFFF" },
  { name: "Neutral Black", code: "#0B0B0B", color: "#FFFFFF" },
  { name: "Black Denim", code: "#191C27", color: "#FFFFFF" },
  { name: "Vampire Black", code: "#0F0404", color: "#FFFFFF" },
  { name: "Cool Black", code: "#151922", color: "#FFFFFF" },
  { name: "Panda Black", code: "#3C4748", color: "#FFFFFF" },
  { name: "Frost Black", code: "#191C20", color: "#FFFFFF" },
  { name: "Ink Black(RAL)", code: "#212122", color: "#FFFFFF" },
  { name: "Raven", code: "#050301", color: "#FFFFFF" },
  { name: "leather", code: "#0B0705", color: "#FFFFFF" },
  { name: "Sable", code: "#060606", color: "#FFFFFF" },
  { name: "Power Black", code: "#0E0C01", color: "#FFFFFF" },
  { name: "Soot", code: "#160D08", color: "#FFFFFF" },
  { name: "Jade", code: "#000302", color: "#FFFFFF" },
  { name: "True Black", code: "#0A0B0B", color: "#FFFFFF" },
  { name: "Premium Black", code: "#100E09", color: "#FFFFFF" },
  { name: "Obsidian", code: "#020403", color: "#FFFFFF" },
  { name: "Black Grain", code: "#2C2C2A", color: "#FFFFFF" },
  { name: "Black Magic", code: "#0B0510", color: "#FFFFFF" },
  { name: "Iron Black", code: "#343432", color: "#FFFFFF" },
  { name: "Rich Black(FOGRA29)", code: "#010B13", color: "#FFFFFF" },
  { name: "Warm Black", code: "#004242", color: "#FFFFFF" },
  { name: "Black Coral", code: "#54626F", color: "#FFFFFF" },
  { name: "Black Shadows", code: "#BFAFB2", color: "#FFFFFF" },
  { name: "Black Raspberry", code: "#451425", color: "#FFFFFF" },
  { name: "Kombu Green", code: "#354230", color: "#FFFFFF" },
  { name: "Zinnwaldite Brown", code: "#2C1608", color: "#FFFFFF" },
  { name: "Dark Slate Gray", code: "#2F4F4F", color: "#FFFFFF" },
  { name: "Dark Charcoal", code: "#333333", color: "#FFFFFF" },
  { name: "Russian Violet", code: "#32174D", color: "#FFFFFF" },
  { name: "Olive Drab #7", code: "#3C341F", color: "#FFFFFF" },
  { name: "Dark Sienna", code: "#3C1414", color: "#FFFFFF" },
  { name: "Alien Black", code: "#1A2228", color: "#FFFFFF" },
  { name: "Black Chocolate", code: "#1B1811", color: "#FFFFFF" },
  { name: "Blue Charcoal", code: "#262B2F", color: "#FFFFFF" },
  { name: "Gothic Grape", code: "#120321", color: "#FFFFFF" },
  { name: "Metropolis", code: "#1A1A1A", color: "#FFFFFF" },
  { name: "Night Shadow", code: "#1C1C1C", color: "#FFFFFF" },
  { name: "Off Black", code: "#595652", color: "#FFFFFF" },
  { name: "Dark Raisin", code: "#1A0F0F", color: "#FFFFFF" },
  { name: "Tea Bag", code: "#161311", color: "#FFFFFF" },
  { name: "Electric Black", code: "#292929", color: "#FFFFFF" },
  { name: "Tech Black", code: "#0D0E0E", color: "#FFFFFF" },
  { name: "Dull Black", code: "#161616", color: "#FFFFFF" },
  { name: "Dark Black", code: "#010203", color: "#FFFFFF" },
  { name: "Natural Black", code: "#07000B", color: "#FFFFFF" },
  { name: "Retro Black", code: "#1F201F", color: "#FFFFFF" },
  { name: "Black Green(RAL)", code: "#303D3A", color: "#FFFFFF" },
  { name: "Deep Black", code: "#050203", color: "#FFFFFF" },
  { name: "Refresh Black", code: "#111212", color: "#FFFFFF" },
  { name: "Rustic Black", code: "#1B1A16", color: "#FFFFFF" },
  { name: "Rose Ebony", code: "#674846", color: "#FFFFFF" },
  { name: "Liver", code: "#534B4F", color: "#FFFFFF" },
  { name: "Purple Taupe", code: "#50404D", color: "#FFFFFF" },
  { name: "Black Pearl", code: "#0E161A", color: "#FFFFFF" },
  { name: "Black Russian", code: "#24252B", color: "#FFFFFF" },
  { name: "Aesthetic Black", code: "#1C1C1E", color: "#FFFFFF" },
  { name: "Signal Black(RAL)", code: "#2B2B2C", color: "#FFFFFF" },
  { name: "Cafe Noir", code: "#4B3621", color: "#FFFFFF" },
  { name: "Luxury Black", code: "#060D0D", color: "#FFFFFF" },
  { name: "Bright Black", code: "#222024", color: "#FFFFFF" },
  { name: "Black Blue(RAL)", code: "#1A1E28", color: "#FFFFFF" },
  { name: "Glossy Black", code: "#252324", color: "#FFFFFF" },
  { name: "Ivory Black", code: "#231F20", color: "#FFFFFF" },
  { name: "Pastel Black", code: "#1D1C1A", color: "#FFFFFF" },
  { name: "Fashion Black", code: "#060403", color: "#FFFFFF" },
  { name: "Graphite Black(RAL)", code: "#27292B", color: "#FFFFFF" },
  { name: "Black Gray", code: "#303234", color: "#FFFFFF" },
  { name: "Black Hole", code: "#060605", color: "#FFFFFF" },
  { name: "Kokushoku", code: "#171412", color: "#FFFFFF" },
  { name: "Kurotobi", code: "#351E1C", color: "#FFFFFF" },
  { name: "Void", code: "#010207", color: "#FFFFFF" },
  { name: "Wet Suit", code: "#080706", color: "#FFFFFF" },
  { name: "Yacht Club Black", code: "#222627", color: "#FFFFFF" },
  { name: "Young Night", code: "#232323", color: "#FFFFFF" },
  { name: "Blackstrap Molasses", code: "#2B2523", color: "#FFFFFF" },
  { name: "Carbon Black", code: "#0C0A00", color: "#FFFFFF" },
  { name: "Cynical Black", code: "#171717", color: "#FFFFFF" },
  { name: "Black Plum", code: "#362B32", color: "#FFFFFF" },
  { name: "Reversed Gray", code: "#080808", color: "#FFFFFF" },
  { name: "Stout", code: "#0F0B0A", color: "#FFFFFF" },
  { name: "Tornado Cloud", code: "#121213", color: "#FFFFFF" },
  { name: "Walnut Hull", code: "#1B1813", color: "#FFFFFF" },
  { name: "Tap Shoe", code: "#2A2B2D", color: "#FFFFFF" },
  { name: "Woodsmoke", code: "#2B3230", color: "#FFFFFF" },
  { name: "Black Red", code: "#3D2022", color: "#FFFFFF" },
  { name: "Wind Cave", code: "#1F2024", color: "#FFFFFF" },
  { name: "Heavy gray", code: "#050505", color: "#FFFFFF" },
];

const shadesOfBlue = [
  { name: "Turquoise", code: "#40E0D0", color: "#000000" },
  { name: "Celeste", code: "#B2FFFF", color: "#000000" },
  { name: "Light Turquoise", code: "#AFEEEE", color: "#000000" },
  { name: "Turquoise Blue", code: "#00FFEF", color: "#000000" },
  { name: "Medium Turquoise", code: "#48D1CC", color: "#000000" },
  { name: "Dark Turquoise", code: "#00CED1", color: "#000000" },
  { name: "Bright Turquoise", code: "#08E8DE", color: "#000000" },
  { name: "Powder Blue", code: "#B0E0E6", color: "#000000" },
  { name: "Sky Blue", code: "#ADD8E6", color: "#000000" },
  { name: "Electric Blue", code: "#7DF9FF", color: "#000000" },
  { name: "Air Force Blue(RAF)", code: "#5D8AA8", color: "#FFFFFF" },
  { name: "Air Force Blue(USAF)", code: "#00308F", color: "#FFFFFF" },
  { name: "US Air Force Academy Blue", code: "#004F98", color: "#FFFFFF" },
  { name: "Beau Blue", code: "#BCD4E6", color: "#000000" },
  { name: "Baby Blue", code: "#89CFF0", color: "#000000" },
  { name: "Baby Blue Eyes", code: "#A1CAF1", color: "#000000" },
  { name: "Littile Boy Blue", code: "#6CA0DC", color: "#000000" },
  { name: "Tiffany Blue", code: "#81D8D0", color: "#000000" },
  { name: "Steel Blue", code: "#4682B4", color: "#FFFFFF" },
  { name: "Carolina Blue", code: "#4B9CD3", color: "#FFFFFF" },
  { name: "Turkish Blue", code: "#4F97A3", color: "#FFFFFF" },
  { name: "Maya Blue", code: "#73C2FB", color: "#000000" },
  { name: "Teal", code: "#008080", color: "#FFFFFF" },
  { name: "Independence Blue", code: "#4C516D", color: "#FFFFFF" },
  { name: "Cornflower Blue", code: "#6495ED", color: "#FFFFFF" },
  { name: "Sapphire Blue", code: "#0F52BA", color: "#FFFFFF" },
  { name: "Madium Sapphire", code: "#2D5DA1", color: "#FFFFFF" },
  { name: "B'dazzled Blue", code: "#2E5894", color: "#FFFFFF" },
  { name: "Blue Sapphire", code: "#126180", color: "#FFFFFF" },
  { name: "Dark Sapphire", code: "#082567", color: "#FFFFFF" },
  { name: "Azure", code: "#007FFF", color: "#FFFFFF" },
  { name: "Egyptian Blue", code: "#1034A6", color: "#FFFFFF" },
  { name: "Yale Blue", code: "#00356B", color: "#FFFFFF" },
  { name: "Navy Blue", code: "#000080", color: "#FFFFFF" },
  { name: "Prussian Blue", code: "#003153", color: "#FFFFFF" },
  { name: "Space Cadet", code: "#1D2951", color: "#FFFFFF" },
  { name: "Royal Blue", code: "#002366", color: "#FFFFFF" },
  { name: "Queen Blue", code: "#436B95", color: "#FFFFFF" },
  { name: "Imperial Blue", code: "#005A92", color: "#FFFFFF" },
  { name: "Periwinkle", code: "#CCCCFF", color: "#000000" },
  { name: "Morning Blue", code: "#8DA399", color: "#000000" },
  { name: "Uranian Blue", code: "#AFDBF5", color: "#000000" },
  { name: "Fluroscent Blue", code: "#15F4EE", color: "#000000" },
  { name: "Ruddy Blue", code: "#76ABDF", color: "#000000" },
  { name: "Admiral Blue", code: "#2C3863", color: "#FFFFFF" },
  { name: "Aegean Blue", code: "#4E6E81", color: "#FFFFFF" },
  { name: "Aero Blue", code: "#C9FFE5", color: "#000000" },
  { name: "Air Superiority Blue", code: "#72A0C1", color: "#000000" },
  { name: "Alice Blue", code: "#FOF8FF", color: "#000000" },
  { name: "Aqua Blue", code: "#0AFFFF", color: "#000000" },
  { name: "Aquamarine Blue", code: "#6BCAE2", color: "#000000" },
  { name: "Arctic Blue", code: "#C6E6FB", color: "#000000" },
  { name: "Argentina Blue", code: "#6CB4EE", color: "#000000" },
  { name: "Astros Navy", code: "#002D62", color: "#FFFFFF" },
  { name: "Bayern Blue", code: "#0066B2", color: "#FFFFFF" },
  { name: "Berry Blue", code: "#4F86F7", color: "#FFFFFF" },
  { name: "Blue", code: "#0000FF", color: "#FFFFFF" },
  { name: "Blue Yonder", code: "#5072A7", color: "#FFFFFF" },
  { name: "Bleu De France Blue", code: "#318CE7", color: "#000000" },
  { name: "Blue-Gray", code: "#6699CC", color: "#000000" },
  { name: "Boeing Blue", code: "#0039A6", color: "#FFFFFF" },
  { name: "Braves Navy", code: "#13274F", color: "#FFFFFF" },
  { name: "Brewers Blue", code: "#0A2351", color: "#FFFFFF" },
  { name: "Byzantine Blue", code: "#3457D5", color: "#FFFFFF" },
  { name: "Cambridge Blue", code: "#A3C1AD", color: "#000000" },
  { name: "Capri Blue", code: "#00BFFF", color: "#000000" },
  { name: "Cerulean Blue", code: "#2A52BE", color: "#FFFFFF" },
  { name: "Chelsea Blue", code: "#034694", color: "#FFFFFF" },
  { name: "Chlorine Blue", code: "#0CAFFF", color: "#000000" },
  { name: "Cobalt Blue", code: "#0047AB", color: "#FFFFFF" },
  { name: "College Navy", code: "#002244", color: "#FFFFFF" },
  { name: "Columbia Blue", code: "#B9D9EB", color: "#FFFFFF" },
  { name: "Crayola Blue", code: "#1F75FE", color: "#000000" },
  { name: "Cyan Blue", code: "#00FFFF", color: "#000000" },
  { name: "Dallas Cowboys Blue", code: "#041E42", color: "#FFFFFF" },
  { name: "Dark Blue", code: "#00008B", color: "#FFFFFF" },
  { name: "Delft Blue", code: "#1F305E", color: "#FFFFFF" },
  { name: "Dell Blue", code: "#0076CE", color: "#FFFFFF" },
  { name: "Denim Blue", code: "#1560BD", color: "#FFFFFF" },
  { name: "Dodgers Blue", code: "#005A9C", color: "#FFFFFF" },
  { name: "Dolphins Aqua", code: "#008E97", color: "#FFFFFF" },
  { name: "Duck Blue", code: "#007791", color: "#FFFFFF" },
  { name: "Duke Blue", code: "#012169", color: "#FFFFFF" },
  { name: "Electric Indigo", code: "#6F00FF", color: "#FFFFFF" },
  { name: "Everton Blue", code: "#003399", color: "#FFFFFF" },
  { name: "Facebook Blue", code: "#1877F2", color: "#FFFFFF" },
  { name: "Ford Blue", code: "#2C3968", color: "#FFFFFF" },
  { name: "General Motors Blue", code: "#073980", color: "#FFFFFF" },
  { name: "Glaucous Blue", code: "#6082B6", color: "#000000" },
  { name: "IBM Blue", code: "#0530AD", color: "#FFFFFF" },
  { name: "Ice Blue", code: "#99FFFF", color: "#000000" },
  { name: "Indigo Blue", code: "#3F00FF", color: "#FFFFFF" },
  { name: "Indigo Dye Blue", code: "#00416A", color: "#FFFFFF" },
  { name: "Intel Blue", code: "#0071C5", color: "#FFFFFF" },
  { name: "International Klein Blue", code: "#002FA7", color: "#FFFFFF" },
  { name: "Iris Blue", code: "#5A4FCF", color: "#FFFFFF" },
  { name: "KC Royals Blue", code: "#004687", color: "#FFFFFF" },
  { name: "Lapis Blue", code: "#26619C", color: "#FFFFFF" },
  { name: "Liberty Blue", code: "#545AA7", color: "#FFFFFF" },
  { name: "Lowes Blue", code: "#004792", color: "#FFFFFF" },
  { name: "Magic Blue", code: "#0077C0", color: "#FFFFFF" },
  { name: "Majorelle Blue", code: "#6050DC", color: "#FFFFFF" },
  { name: "Marian Blue", code: "#E1EBEE", color: "#000000" },
  { name: "Mavericks Blue", code: "#00538C", color: "#FFFFFF" },
  { name: "Medium Blue", code: "#0000CD", color: "#FFFFFF" },
  { name: "Medium Slate Blue", code: "#7B68EE", color: "#FFFFFF" },
  { name: "Millennium Blue", code: "#002244", color: "#FFFFFF" },
  { name: "Munsell Blue", code: "#0093AF", color: "#FFFFFF" },
  { name: "Neon Blue", code: "#4D4DFF", color: "#FFFFFF" },
  { name: "Non-Photo Blue", code: "#A4DDED", color: "#000000" },
  { name: "Ocean Blue", code: "#009DC4", color: "#000000" },
  { name: "Oxford Blue", code: "#002147", color: "#FFFFFF" },
  { name: "PSG Blue", code: "#004170", color: "#FFFFFF" },
  { name: "Pacific Blue", code: "#1CA9C9", color: "#000000" },
  { name: "Pantone Blue", code: "#0018A8", color: "#FFFFFF" },
  { name: "Peacock Blue", code: "#005F69", color: "#FFFFFF" },
  { name: "Penn Blue", code: "#011F5B", color: "#FFFFFF" },
  { name: "Persian Blue", code: "#1C39BB", color: "#FFFFFF" },
  { name: "Phthalo Blue", code: "#000F89", color: "#FFFFFF" },
  { name: "Picotee Blue", code: "#2E2787", color: "#FFFFFF" },
  { name: "Polynesian Blue", code: "#224C98", color: "#FFFFFF" },
  { name: "Resolution Blue", code: "#002387", color: "#FFFFFF" },
  { name: "Robin Egg Blue", code: "#00CCCC", color: "#000000" },
  { name: "Savoy Blue", code: "#4B61D1", color: "#FFFFFF" },
  { name: "Slate Blue", code: "#6A5ACD", color: "#FFFFFF" },
  { name: "Spanish Blue", code: "#0070BB", color: "#FFFFFF" },
  { name: "Sprush Blue", code: "#617178", color: "#FFFFFF" },
  { name: "Stone Blue", code: "#819EA8", color: "#000000" },
  { name: "Tottenham Navy", code: "#132257", color: "#FFFFFF" },
  { name: "True Blue", code: "#2D68C4", color: "#FFFFFF" },
  { name: "Tufts Blue", code: "#3E8EDE", color: "#000000" },
  { name: "Twitter Blue", code: "#1DA1F2", color: "#000000" },
  { name: "UCLA Blue", code: "#2774AE", color: "#FFFFFF" },
  { name: "Ultramarine Blue", code: "#120A8F", color: "#FFFFFF" },
  { name: "Voilet Blue", code: "#324AB2", color: "#FFFFFF" },
  { name: "Visa Blue", code: "#1A1F71", color: "#FFFFFF" },
  { name: "Vivid Sky Blue", code: "#00CCFF", color: "#000000" },
  { name: "Warrios Blue", code: "#1D428A", color: "#FFFFFF" },
  { name: "Yankees Blue", code: "#0C2340", color: "#FFFFFF" },
  { name: "YInMn Blue", code: "#2E5090", color: "#FFFFFF" },
  { name: "Steel Blue", code: "#4682B4", color: "#FFFFFF" },
  { name: "Alaskan Blue", code: "#6DA9D2", color: "#000000" },
  { name: "Tall Ships Blue", code: "#0E81B9", color: "#FFFFFF" },
];

const shadesOfWhite = [
  { name: "White", code: "#FFFFFF", color: "#FFFFFF" },
  { name: "Ghost White", code: "#F8F8FF", color: "#FFFFFF" },
  { name: "White Smoke", code: "#F5F5F5", color: "#FFFFFF" },
  { name: "Baby Powder", code: "#FEFEFA", color: "#FFFFFF" },
  { name: "Snow", code: "#F5FEFD", color: "#FFFFFF" },
  { name: "Ivory", code: "#FFFFF0", color: "#FFFFFF" },
  { name: "Floral White", code: "#FFFAF0", color: "#FFFFFF" },
  { name: "Seashell", code: "#FFF5EE", color: "#FFFFFF" },
  { name: "Cornsilk", code: "#FFF8DC", color: "#FFFFFF" },
  { name: "Old Lace", code: "#FDF5E6", color: "#FFFFFF" },
  { name: "Cream", code: "#FFFDD0", color: "#FFFFFF" },
  { name: "Beige", code: "#F5F5DC", color: "#FFFFFF" },
  { name: "Parchment", code: "#F1E9D2", color: "#FFFFFF" },
  { name: "Antique White", code: "#FAEBD7", color: "#FFFFFF" },
  { name: "Champagne", code: "#F7E7CE", color: "#FFFFFF" },
  { name: "Eggshell", code: "#F0EAD6", color: "#FFFFFF" },
  { name: "Dutch White", code: "#EFDFBB", color: "#FFFFFF" },
  { name: "Bone", code: "#E3DAC9", color: "#FFFFFF" },
  { name: "Vanilla", code: "#F3E5AB", color: "#FFFFFF" },
  { name: "Flax", code: "#EEDC82", color: "#FFFFFF" },
  { name: "Navajo White", code: "#FFDEAD", color: "#FFFFFF" },
  { name: "Alabaster", code: "#EDEAE0", color: "#FFFFFF" },
  { name: "Chiffon", code: "#FFFACD", color: "#FFFFFF" },
  { name: "Unresolved Problem", code: "#F3F2ED", color: "#FFFFFF" },
  { name: "Old Wood", code: "#F0EEE4", color: "#FFFFFF" },
  { name: "Rose White", code: "#FFFAFA", color: "#FFFFFF" },
  { name: "Vista White", code: "#FDFCFA", color: "#FFFFFF" },
  { name: "Link White", code: "#ECF3F9", color: "#FFFFFF" },
  { name: "Spring", code: "#F3F0E8", color: "#FFFFFF" },
  { name: "Snow Drift", code: "#F8FBF8", color: "#FFFFFF" },
  { name: "Peppermint", code: "#F1F9EC", color: "#FFFFFF" },
  { name: "Merino", code: "#F2EBDD", color: "#FFFFFF" },
  { name: "Half and Half", code: "#FFFFE4", color: "#FFFFFF" },
  { name: "Island Spice", code: "#FFFCEC", color: "#FFFFFF" },
  { name: "Soft Peach", code: "#F6F1F4", color: "#FFFFFF" },
  { name: "Harp", code: "#EBF5F0", color: "#FFFFFF" },
  { name: "Titan White", code: "#EEEEFF", color: "#FFFFFF" },
  { name: "Audience Anger", code: "#EAF4FC", color: "#FFFFFF" },
  { name: "Orange White", code: "#F8F9F5", color: "#FFFFFF" },
  { name: "Cough Mixture", code: "#F6F4F1", color: "#FFFFFF" },
  { name: "Albescent White", code: "#F3DECA", color: "#FFFFFF" },
  { name: "Coconut", code: "#FFF1E6", color: "#FFFFFF" },
  { name: "Pink Salt", code: "#F8EEEC", color: "#FFFFFF" },
  { name: "Frost", code: "#FCFBFC", color: "#FFFFFF" },
  { name: "Linen", code: "#F3EAD3", color: "#FFFFFF" },
  { name: "Rice", code: "#FAF5EF", color: "#FFFFFF" },
  { name: "Daisy", code: "#FAFAFA", color: "#FFFFFF" },
  { name: "Powder", code: "#FBFCFA", color: "#FFFFFF" },
  { name: "Pearl", code: "#FBFCF8", color: "#FFFFFF" },
  { name: "Paris White", code: "#C2D8D3", color: "#FFFFFF" },
  { name: "Cup Cake", code: "#EBF6F7", color: "#FFFFFF" },
  { name: "White Dove", code: "#F0EFE7", color: "#FFFFFF" },
  { name: "White Whisper", code: "#EAE8E1", color: "#FFFFFF" },
  { name: "Lexicon", code: "#E7EAEA", color: "#FFFFFF" },
  { name: "Greek Villa", code: "#F0EBE3", color: "#FFFFFF" },
  { name: "White Diamond", code: "#E7E8E2", color: "#FFFFFF" },
  { name: "Decorator's White", code: "#ECEFEC", color: "#FFFFFF" },
  { name: "Winter White", code: "#DFDFD5", color: "#FFFFFF" },
  { name: "Spatial White", code: "#DEDDDB", color: "#FFFFFF" },
  { name: "Hog Bristle Quarter", code: "#EBE4D8", color: "#FFFFFF" },
  { name: "Simply White", code: "#EFEDE3", color: "#FFFFFF" },
  { name: "Oyster White", code: "#E3DFD2", color: "#FFFFFF" },
  { name: "White On White", code: "#EDEFEF", color: "#FFFFFF" },
  { name: "Lexicon Quarter", code: "#F2F2F1", color: "#FFFFFF" },
  { name: "Alice Blue", code: "#F0F8FF", color: "#FFFFFF" },
  { name: "Honeydew", code: "#F0FFF0", color: "#FFFFFF" },
  { name: "Mint Cream", code: "#F5FFFA", color: "#FFFFFF" },
  { name: "Milk", code: "#FDFFF5", color: "#FFFFFF" },
  { name: "Pomelo White", code: "#F9FFE3", color: "#FFFFFF" },
  { name: "Anti-Flash White", code: "#F2F3F4", color: "#FFFFFF" },
  { name: "Magnolia", code: "#F8F4FF", color: "#FFFFFF" },
  { name: "Azure", code: "#F0FFFF", color: "#FFFFFF" },
  { name: "Huntington White", code: "#F1F0E5", color: "#FFFFFF" },
  { name: "Acadia White", code: "#F4EFE3", color: "#FFFFFF" },
  { name: "Gainsboro", code: "#DCDCDC", color: "#FFFFFF" },
  { name: "Mercury", code: "#E7E7E7", color: "#FFFFFF" },
  { name: "Lavender Blush", code: "#FFF0F5", color: "#FFFFFF" },
  { name: "Isabelline", code: "#F4F0EC", color: "#FFFFFF" },
  { name: "Bubbles", code: "#E7FEFF", color: "#FFFFFF" },
  { name: "Glitter", code: "#E6E8FA", color: "#FFFFFF" },
  { name: "Platinum", code: "#E5E4E2", color: "#FFFFFF" },
  { name: "Cosmic Latte", code: "#FFF8E7", color: "#FFFFFF" },
  { name: "Blanched Almond", code: "#FFEBCD", color: "#FFFFFF" },
  { name: "Light Yellow", code: "#FFFFE0", color: "#FFFFFF" },
  { name: "Natural White", code: "#EEECE6", color: "#FFFFFF" },
  { name: "Vivid White", code: "#F8F8F4", color: "#FFFFFF" },
  { name: "White Wisp", code: "#E9E9E4", color: "#FFFFFF" },
  { name: "Azureish White", code: "#DBE9F4", color: "#FFFFFF" },
  { name: "Timberwolf", code: "#DBD7D2", color: "#FFFFFF" },
  { name: "Papaya Whip", code: "#FFEFD5", color: "#FFFFFF" },
  { name: "Antique White USA", code: "#EEEAE1", color: "#FFFFFF" },
  { name: "Cola", code: "#F9EDEB", color: "#FFFFFF" },
  { name: "Atrium White", code: "#F1EEE4", color: "#FFFFFF" },
  { name: "Cascading White", code: "#F7F5F6", color: "#FFFFFF" },
  { name: "Cotton Ball", code: "#F2F7FD", color: "#FFFFFF" },
  { name: "Photon White", code: "#F8F8E8", color: "#FFFFFF" },
  { name: "White Heat", code: "#FDF9EF", color: "#FFFFFF" },
  { name: "Whitewash", code: "#FEFFFC", color: "#FFFFFF" },
  { name: "Shadow White", code: "#EEF1EA", color: "#FFFFFF" },
  { name: "Abbey White", code: "#EBE5D0", color: "#FFFFFF" },
  { name: "Acoustic White", code: "#EFECE1", color: "#FFFFFF" },
  { name: "Aircraft White", code: "#EDF2F8", color: "#FFFFFF" },
  { name: "Ceramic", code: "#FCFFF9", color: "#FFFFFF" },
  { name: "Coconut Butter", code: "#F2EFE1", color: "#FFFFFF" },
  { name: "Abstract White", code: "#EDE9DD", color: "#FFFFFF" },
  { name: "Bright White", code: "#F4F5F0", color: "#FFFFFF" },
  { name: "Broken White", code: "#EEEBE3", color: "#FFFFFF" },
  { name: "Brilliant White", code: "#EDF1FE", color: "#FFFFFF" },
  { name: "Commercial White", code: "#EDECE6", color: "#FFFFFF" },
  { name: "Feather White", code: "#E7EAE5", color: "#FFFFFF" },
  { name: "Swan White", code: "#FCFCFC", color: "#FFFFFF" },
  { name: "Polar Bear", code: "#EAE9E0", color: "#FFFFFF" },
  { name: "Paper White", code: "#F7FCFE", color: "#FFFFFF" },
  { name: "Pacific Pearl", code: "#E8EAE6", color: "#FFFFFF" },
  { name: "Night White", code: "#E1E1DD", color: "#FFFFFF" },
  { name: "Delicate White", code: "#F1F2EE", color: "#FFFFFF" },
  { name: "Cococnut White", code: "#E9EDF6", color: "#FFFFFF" },
  { name: "Cake Batter", code: "#F0EDDB", color: "#FFFFFF" },
  { name: "White Sand", code: "#ECE9E4", color: "#FFFFFF" },
  { name: "Stone White", code: "#FBF6F0", color: "#FFFFFF" },
  { name: "White Chocolate", code: "#EDE6D6", color: "#FFFFFF" },
  { name: "Retro White", code: "#EDEAE2", color: "#FFFFFF" },
];

const shadesOfPink = [
  { name: "Pink", code: "#F699CD", color: "#FFFFFF" },
  { name: "Dust Rose", code: "#C9A9A6", color: "#FFFFFF" },
  { name: "Millennial Pink", code: "#F3CFC6", color: "#FFFFFF" },
  { name: "Pink Orange", code: "#F89880", color: "#FFFFFF" },
  { name: "Thistle", code: "#D8BFD8", color: "#FFFFFF" },
  { name: "Ballet Slipper", code: "#F79AC0", color: "#FFFFFF" },
  { name: "Watermelon", code: "#FC6C85", color: "#FFFFFF" },
  { name: "Flamingo", code: "#FC8EAC", color: "#000000" },
  { name: "Coral", code: "#F88379", color: "#FFFFFF" },
  { name: "Rose", code: "#F33A6A", color: "#FFFFFF" },
  { name: "Salmon", code: "#FF9999", color: "#000000" },
  { name: "Pastel Pink", code: "#FFD1DC", color: "#000000" },
  { name: "Light Pink", code: "#FFB6C1", color: "#000000" },
  { name: "Cherry Blossom", code: "#FFB7C5", color: "#000000" },
  { name: "Bubblegum", code: "#FFC1CC", color: "#000000" },
  { name: "Baby Pink", code: "#F4C2C2", color: "#000000" },
  { name: "Dark Pink", code: "#E75480", color: "#FFFFFF" },
  { name: "Bright Pink", code: "#FF007F", color: "#FFFFFF" },
  { name: "Rouge", code: "#A94064", color: "#FFFFFF" },
  { name: "Neon Pink", code: "#FF6EC7", color: "#FFFFFF" },
  { name: "Blush", code: "#DE5D83", color: "#FFFFFF" },
  { name: "Fuchsia", code: "#C154C1", color: "#FFFFFF" },
  { name: "Mauve", code: "#E0B0FF", color: "#000000" },
  { name: "Orchid", code: "#DA70D6", color: "#FFFFFF" },
  { name: "Magenta", code: "#FF00FF", color: "#000000" },
  { name: "Hot Pink", code: "#FF69B4", color: "#FFFFFF" },
  { name: "Carnation", code: "#FFA6C9", color: "#000000" },
  { name: "Tulip Pink", code: "#FF8E8E", color: "#000000" },
  { name: "Tea Rose", code: "#F4C2C2", color: "#000000" },
  { name: "Cotton Candy", code: "#FFBCD9", color: "#000000" },
  { name: "Cameo Pink", code: "#EFBBCC", color: "#000000" },
  { name: "French Pink", code: "#F64A8A", color: "#FFFFFF" },
  { name: "Strawberry", code: "#E8888A", color: "#FFFFFF" },
  { name: "Persian Pink", code: "#F77FBE", color: "#FFFFFF" },
  { name: "New York Pink", code: "#DD8374", color: "#FFFFFF" },
  { name: "Indian Red", code: "#CD5C5C", color: "#FFFFFF" },
  { name: "Munsell Red", code: "#F2003C", color: "#FFFFFF" },
  { name: "Cardinal", code: "#C41E3A", color: "#FFFFFF" },
  { name: "Crayola Red", code: "#EE204D", color: "#FFFFFF" },
  { name: "Crimson", code: "#DC143C", color: "#FFFFFF" },
  { name: "Ruby", code: "#E0115F", color: "#FFFFFF" },
  { name: "Redwood", code: "#A45A52", color: "#FFFFFF" },
  { name: "Rusty Red", code: "#DA2C43", color: "#FFFFFF" },
  { name: "Amaranth", code: "#E52B50", color: "#FFFFFF" },
  { name: "Bright Maroon", code: "#C32148", color: "#FFFFFF" },
  { name: "Burnt Sienna", code: "#E97471", color: "#FFFFFF" },
  { name: "Candy Pink", code: "#E4717A", color: "#FFFFFF" },
  { name: "Cherry Pink", code: "#DE3163", color: "#FFFFFF" },
  { name: "Chestnut", code: "#CD5C5C", color: "#FFFFFF" },
  { name: "Dark Coral", code: "#CD5B45", color: "#FFFFFF" },
  { name: "Dark Pastel Red", code: "#C23B22", color: "#FFFFFF" },
  { name: "Dark Terra Cotta", code: "#CC4E5C", color: "#FFFFFF" },
  { name: "Dark Salmon", code: "#E9967A", color: "#FFFFFF" },
  { name: "Lemonade", code: "#F2DBE7", color: "#000000" },
  { name: "Peach", code: "#FAD1AF", color: "#000000" },
  { name: "Crepe", code: "#F89883", color: "#000000" },
  { name: "Piggy Pink", code: "#FDDDE6", color: "#000000" },
  { name: "Deep Pink", code: "#FF1493", color: "#FFFFFF" },
  { name: "Dust Storm", code: "#E5CCC9", color: "#000000" },
  { name: "Nadeshiko Pink", code: "#F6ADC6", color: "#000000" },
  { name: "Rose Quartz", code: "#AA98A9", color: "#FFFFFF" },
  { name: "Wild Strawberry", code: "#FF43A4", color: "#FFFFFF" },
  { name: "Razzmatazz", code: "#E3256B", color: "#FFFFFF" },
  { name: "Rose Taupe", code: "#905D5D", color: "#FFFFFF" },
  { name: "Rubine Red", code: "#D10056", color: "#FFFFFF" },
  { name: "Hollywood Cerise", code: "#F400A1", color: "#FFFFFF" },
  { name: "Mexican Pink", code: "#E4007C", color: "#FFFFFF" },
  { name: "Steel Pink", code: "#CC3366", color: "#FFFFFF" },
  { name: "Rose Gold", code: "#B76E79", color: "#FFFFFF" },
  { name: "Rose Bonbon", code: "#F9429E", color: "#FFFFFF" },
  { name: "Barbie Pink", code: "#E0218A", color: "#FFFFFF" },
  { name: "Mulberry", code: "C54B8C", color: "#000000" },
  { name: "Razzle Dazzle Rose", code: "#FF33CC", color: "#FFFFFF" },
  { name: "Fandango", code: "#B53389", color: "#FFFFFF" },
  { name: "Puce", code: "#CC8899", color: "#FFFFFF" },
  { name: "Old Rose", code: "#C08081", color: "#FFFFFF" },
  { name: "Rosewood", code: "#9E4244", color: "#FFFFFF" },
  { name: "Taffy", code: "#FA86C4", color: "#000000" },
  { name: "Turkish Rose", code: "#B57281", color: "#FFFFFF" },
  { name: "Punch", code: "#F25278", color: "#FFFFFF" },
  { name: "Paradise Pink", code: "#E63E62", color: "#FFFFFF" },
  { name: "Raspberry Rose", code: "#B3446C", color: "#FFFFFF" },
  { name: "Light Crimson", code: "#F56991", color: "#000000" },
  { name: "Pink Sherbet", code: "#F78FA7", color: "#000000" },
  { name: "Tickle me Pink", code: "#FC89AC", color: "#000000" },
  { name: "Thulian Pink", code: "#DE6FA1", color: "#FFFFFF" },
  { name: "Brilliant Rose", code: "#FF55A3", color: "#FFFFFF" },
  { name: "Lace", code: "#FFD8F0", color: "#000000" },
  { name: "Smitten", code: "#C84186", color: "#FFFFFF" },
  { name: "Your", code: "#FFC0C0", color: "#000000" },
  { name: "Careys", code: "#D8A8A8", color: "#000000" },
  { name: "Oyster", code: "#F0D8D8", color: "#000000" },
  { name: "Shimmering Blush", code: "#D98695", color: "#FFFFFF" },
  { name: "Sea", code: "#F09090", color: "#000000" },
  { name: "Brink", code: "#FF6090", color: "#FFFFFF" },
  { name: "Hippie", code: "#A84860", color: "#FFFFFF" },
  { name: "Light Deep Pink", code: "#FF5CCD", color: "#FFFFFF" },
  { name: "Wild Orchid", code: "#D470A2", color: "#FFFFFF" },
  { name: "Cerise Pink", code: "#EC3B83", color: "#FFFFFF" },
  { name: "Shocking Pink", code: "#FC0FC0", color: "#FFFFFF" },
  { name: "Hit", code: "#FFA878", color: "#000000" },
  { name: "lady", code: "#F0C0A8", color: "#000000" },
  { name: "Neon Fuchsia", code: "#FE4164", color: "#FFFFFF" },
  { name: "Ultra Pink", code: "#FF6FFF", color: "#000000" },
  { name: "Schauss Pink", code: "#FF91AF", color: "#000000" },
  { name: "Ruddy Pink", code: "#E18E96", color: "#000000" },
  { name: "Pink Pearl", code: "#E7ACCF", color: "#000000" },
  { name: "Lavender Rose", code: "#FBA0E3", color: "#000000" },
  { name: "Shampoo", code: "#FFCFF1", color: "#000000" },
  { name: "Spanish Pink", code: "#F7BFBE", color: "#000000" },
  { name: "Valentine Pink", code: "#E6A6BE", color: "#000000" },
  { name: "Silvery Pink", code: "#DCB5B4", color: "#000000" },
  { name: "Melon", code: "#F7BCAC", color: "#000000" },
  { name: "Milano", code: "#D95D67", color: "#FFFFFF" },
  { name: "Sweet Pink", code: "#EE918D", color: "#000000" },
  { name: "Knockout Pink", code: "#FF3EA5", color: "#FFFFFF" },
  { name: "Grapefruit Pink", code: "#E0707C", color: "#FFFFFF" },
  { name: "Champagne Pink", code: "#F6E1D3", color: "#000000" },
  { name: "Lip Pink", code: "#DBAC98", color: "#000000" },
  { name: "Passion Pink", code: "#CE74A7", color: "#FFFFFF" },
  { name: "Nude Pink", code: "#DDC0B4", color: "#000000" },
  { name: "Rosy Pink", code: "#FF66CC", color: "#000000" },
  { name: "Gold Pink", code: "#E6C7C2", color: "#000000" },
  { name: "Misty Rose", code: "#FFE4E1", color: "#000000" },
  { name: "Mauvelous", code: "#EF98AA", color: "#000000" },
  { name: "Light Blush", code: "#F1ABB9", color: "#000000" },
  { name: "Copper Rose", code: "#996666", color: "#FFFFFF" },
  { name: "Raspberry Glace", code: "#915F6D", color: "#FFFFFF" },
  { name: "Debian Red", code: "#D70A53", color: "#FFFFFF" },
  { name: "Ruber", code: "#CE4676", color: "#FFFFFF" },
  { name: "Vanilla Ice", code: "#F38FA9", color: "#000000" },
  { name: "Light Hot Pink", code: "#FFB3DE", color: "#000000" },
  { name: "Super Pink", code: "#CF6BA9", color: "#FFFFFF" },
  { name: "China Rose", code: "#A8516E", color: "#FFFFFF" },
  { name: "Deep Pruce", code: "#A95C68", color: "#FFFFFF" },
  { name: "French Fuchsia", code: "#FD3F92", color: "#FFFFFF" },
  { name: "Bisque", code: "#F2D2BD", color: "#000000" },
];

const shadesOfGreen = [
  { name: "Green", code: "#008000", color: "#FFFFFF" },
  { name: "Forest Green", code: "#0B6623", color: "#FFFFFF" },
  { name: "Juniper", code: "#3A5311", color: "#FFFFFF" },
  { name: "Parakeet", code: "#03C04A", color: "#FFFFFF" },
  { name: "Olive", code: "#708238", color: "#FFFFFF" },
  { name: "Basil", code: "#32612D", color: "#FFFFFF" },
  { name: "Pickle", code: "#597D35", color: "#FFFFFF" },
  { name: "Crocodile", code: "#607D3B", color: "#FFFFFF" },
  { name: "Seaweed", code: "#354A21", color: "#FFFFFF" },
  { name: "Aqua", code: "#00FFFF", color: "#000000" },
  { name: "Aquamarine", code: "#7FFFD4", color: "#000000" },
  { name: "Hunter Green", code: "#3F704D", color: "#FFFFFF" },
  { name: "Seafoam Green", code: "#9FE2BF", color: "#000000" },
  { name: "Artichoke Green", code: "#8F9779", color: "#000000" },
  { name: "Jungle Green", code: "#29AB87", color: "#FFFFFF" },
  { name: "Tropical Rainforest", code: "#00755E", color: "#FFFFFF" },
  { name: "Amazon", code: "#3B7A57", color: "#FFFFFF" },
  { name: "Deep Jungle Green", code: "#004B49", color: "#FFFFFF" },
  { name: "Medium Jungle Green", code: "#1C352D", color: "#FFFFFF" },
  { name: "Dark Jungle Green", code: "#1A2421", color: "#FFFFFF" },
  { name: "Moss Green", code: "#8A9A5B", color: "#FFFFFF" },
  { name: "Myrtle Green", code: "#317873", color: "#FFFFFF" },
  { name: "Pine Green", code: "#01796F", color: "#FFFFFF" },
  { name: "Persian Green", code: "#00A693", color: "#FFFFFF" },
  { name: "Emerald Green", code: "#50C878", color: "#000000" },
  { name: "Neon Green", code: "#39FF14", color: "#000000" },
  { name: "Sacramento Green", code: "#043927", color: "#FFFFFF" },
  { name: "Sea Green", code: "#2E8B57", color: "#FFFFFF" },
  { name: "Ocean Green", code: "#48B591", color: "#FFFFFF" },
  { name: "Sage Green", code: "#9DC183", color: "#000000" },
  { name: "Lime Green", code: "#C7EA46", color: "#000000" },
  { name: "Jade Green", code: "#00A86B", color: "#FFFFFF" },
  { name: "Fern Green", code: "#4F7942", color: "#FFFFFF" },
  { name: "Laurel Green", code: "#A9BA9D", color: "#000000" },
  { name: "Mint Green", code: "#98FB98", color: "#000000" },
  { name: "lincoln Green", code: "#478778", color: "#FFFFFF" },
  { name: "Tea Green", code: "#D0F0C0", color: "#000000" },
  { name: "Army Green", code: "#4B5320", color: "#FFFFFF" },
  { name: "Kelly Green", code: "#4CBB17", color: "#FFFFFF" },
  { name: "Russian Green", code: "#679267", color: "#FFFFFF" },
  { name: "Paris Green", code: "#50C878", color: "#000000" },
  { name: "Pakistan Green", code: "#006600", color: "#FFFFFF" },
  { name: "Midnight Green", code: "#004953", color: "#FFFFFF" },
  { name: "Indian Green", code: "#138808", color: "#FFFFFF" },
  { name: "Hunter Green", code: "#355E3B", color: "#FFFFFF" },
  { name: "Celadon", code: "#ACE1AF", color: "#000000" },
  { name: "Avocado", code: "#568203", color: "#FFFFFF" },
  { name: "Harlequin", code: "#3FFF00", color: "#000000" },
  { name: "Spring", code: "#00F0A8", color: "#000000" },
  { name: "Kaitoke", code: "#004830", color: "#FFFFFF" },
  { name: "Screamin' Green", code: "#76FF7A", color: "#000000" },
  { name: "Chateau", code: "#48A860", color: "#FFFFFF" },
  { name: "Dark Moss Green", code: "#4A5D23", color: "#FFFFFF" },
  { name: "Swamp", code: "#A8C090", color: "#000000" },
  { name: "Mantis", code: "#74C365", color: "#000000" },
  { name: "Fun", code: "#007848", color: "#FFFFFF" },
  { name: "Pantone Artichoke Green", code: "#4B6F44", color: "#FFFFFF" },
  { name: "Viridian", code: "#609078", color: "#FFFFFF" },
  { name: "Reseda Green", code: "#6C7C59", color: "#FFFFFF" },
  { name: "Chetwode", code: "#F0FFF0", color: "#000000" },
  { name: "Shamrock Green", code: "#009E60", color: "#FFFFFF" },
  { name: "Verdun", code: "#487800", color: "#FFFFFF" },
  { name: "Castleton Green", code: "#00563B", color: "#FFFFFF" },
  { name: "Gin", code: "#D8E4BC", color: "#000000" },
  { name: "Citrine", code: "#E4D00A", color: "#FFFFFF" },
  { name: "Granny Smith Apple", code: "#A8E4A0", color: "#000000" },
  { name: "Bitter Lime", code: "#BFFF00", color: "#000000" },
  { name: "Bright Mint", code: "#4FFFB0", color: "#000000" },
  { name: "Bottle Green", code: "#0064AE", color: "#FFFFFF" },
  { name: "Cadmium Green", code: "#006B3C", color: "#FFFFFF" },
  { name: "Camouflage Green", code: "#78866B", color: "#FFFFFF" },
  { name: "Pear", code: "#D1E231", color: "#000000" },
  { name: "Dollar Bill", code: "#85BB65", color: "#000000" },
  { name: "Inchworm", code: "#B2EC5D", color: "#000000" },
  { name: "Asparagus", code: "#87A96B", color: "#FFFFFF" },
  { name: "Caribbean Green", code: "#00CC99", color: "#FFFFFF" },
  { name: "GO Green", code: "#00AB66", color: "#FFFFFF" },
  { name: "Phthalo Green", code: "#123524", color: "#FFFFFF" },
  { name: "Napier Green", code: "#2A8000", color: "#FFFFFF" },
  { name: "Fledgrau", code: "#4D5D53", color: "#FFFFFF" },
  { name: "Green-Yellow", code: "#ADFF2F", color: "#000000" },
  { name: "Malachite", code: "#0BDA51", color: "#000000" },
  { name: "Rifle Green", code: "#444C38", color: "#FFFFFF" },
  { name: "Volt", code: "#CEFF00", color: "#000000" },
  { name: "British Racing Green", code: "#004225", color: "#FFFFFF" },
  { name: "Thyme", code: "#5EDC1F", color: "#000000" },
  { name: "Chartreuse", code: "#7FFF00", color: "#000000" },
  { name: "Corn Green", code: "#71A92C", color: "#FFFFFF" },
  { name: "Shrek Green", code: "#C4D300", color: "#000000" },
  { name: "Christmas Green", code: "#00873E", color: "#FFFFFF" },
  { name: "Irish Green", code: "#009A44", color: "#FFFFFF" },
  { name: "Road Sign Green", code: "#01735C", color: "#FFFFFF" },
  { name: "Lightsaber Green", code: "#2FF924", color: "#000000" },
  { name: "Girl Scout Green", code: "#00AE58", color: "#FFFFFF" },
  { name: "Tennis Court Green", code: "#6C935C", color: "#FFFFFF" },
  { name: "Spring Bud", code: "#A7FC00", color: "#000000" },
  { name: "Chinese Green", code: "#D0DB61", color: "#000000" },
  { name: "Arctic Lime", code: "#D0FF14", color: "#000000" },
  { name: "Nyanza", code: "#E9FFDB", color: "#000000" },
  { name: "Dark Lemon-Lime", code: "#76BA1B", color: "#FFFFFF" },
  { name: "Crayola Yellow-Green", code: "#ACDF87", color: "#000000" },
  { name: "Maximum Green", code: "#4C9A2A", color: "#FFFFFF" },
  { name: "Vivid Lime Green", code: "#A4DE02", color: "#000000" },
  { name: "Pistachio", code: "#93C572", color: "#000000" },
  { name: "Medium Spring Green", code: "#00FA9A", color: "#000000" },
  { name: "Sheen Green", code: "#8FD400", color: "#000000" },
  { name: "La Salle Green", code: "#087830", color: "#FFFFFF" },
  { name: "Spanish Viridian", code: "#007F5C", color: "#FFFFFF" },
  { name: "Dartmouth Green", code: "#00703C", color: "#FFFFFF" },
  { name: "Pine Needle", code: "#454D32", color: "#FFFFFF" },
  { name: "Olive Drab", code: "#6B8E23", color: "#FFFFFF" },
  { name: "Lawn Green", code: "#7CFC00", color: "#000000" },
  { name: "Xanadu", code: "#738678", color: "#FFFFFF" },
  { name: "Dark Olive Green", code: "#556B2F", color: "#FFFFFF" },
  { name: "Dark Sea Green", code: "#8FBC8F", color: "#000000" },
  { name: "Green (Munsell)", code: "#00A877", color: "#FFFFFF" },
  { name: "Mughal Green", code: "#306030", color: "#FFFFFF" },
  { name: "John Deere Green", code: "#367C2B", color: "#FFFFFF" },
  { name: "Office Green", code: "#008000", color: "#FFFFFF" },
  { name: "Light Green", code: "#90EE90", color: "#FFFFFF" },
  { name: "Dark Green", code: "#023020", color: "#FFFFFF" },
  { name: "Limerick", code: "#9DC209", color: "#000000" },
  { name: "Eucalyptus", code: "#5F8575", color: "#FFFFFF" },
  { name: "Maximum Green Yellow", code: "#D9E650", color: "#000000" },
  { name: "French Lime", code: "#9EFD38", color: "#000000" },
  { name: "Medium Spring Bud", code: "#C9DC87", color: "#000000" },
  { name: "UFO Green", code: "#3CD070", color: "#000000" },
  { name: "Acid Green", code: "#B0BF1A", color: "#000000" },
  { name: "Chlorophyll Green", code: "#4AFF00", color: "#000000" },
  { name: "Green Lizard", code: "#A7F432", color: "#000000" },
  { name: "Iguana Green", code: "#71BC78", color: "#000000" },
  { name: "Kombu Green", code: "#354230", color: "#FFFFFF" },
  { name: "Middle Green", code: "#4D8C57", color: "#FFFFFF" },
  { name: "Paolo Veronese Green", code: "#009B7D", color: "#FFFFFF" },
  { name: "Pullman Green", code: "#3B331C", color: "#FFFFFF" },
  { name: "Green Screen", code: "#00B140", color: "#FFFFFF" },
  { name: "Android Green", code: "#A4C639", color: "#000000" },
  { name: "Bitter Lemon", code: "#CAE00D", color: "#000000" },
  { name: "Wageninger Green", code: "#34B233", color: "#FFFFFF" },
  { name: "Sap Green", code: "#507D2A", color: "#FFFFFF" },
  { name: "Old Moss Green", code: "#867E36", color: "#FFFFFF" },
  { name: "Slimy Green", code: "#299617", color: "#FFFFFF" },
  { name: "Very Light Malachite Green", code: "#64E986", color: "#000000" },
  { name: "Dark Spring Green", code: "#177245", color: "#FFFFFF" },
  { name: "Guppie Green", code: "#00FF7F", color: "#000000" },
  { name: "Apple Green", code: "#8DB600", color: "#FFFFFF" },
  { name: "Deep Green", code: "#056608", color: "#FFFFFF" },
  { name: "Hooker's Green", code: "#49796B", color: "#FFFFFF" },
  { name: "Medium Sea Green", code: "#3CB371", color: "#FFFFFF" },
  { name: "Turquoise Green", code: "#A0D6B4", color: "#000000" },
];

const shadesOfGray = [
  { name: "Arsenic", code: "#3B444B", color: "#FFFFFF" },
  { name: "Lead", code: "#3F3F4E", color: "#FFFFFF" },
  { name: "Ash Gray", code: "#B2BEB5", color: "#000000" },
  { name: "Battleship Gray", code: "#848482", color: "#FFFFFF" },
  { name: "Black Coral", code: "#54626F", color: "#FFFFFF" },
  { name: "Blue Gray", code: "#98AFC7", color: "#000000" },
  { name: "Cadet Gray", code: "#91A3B0", color: "#000000" },
  { name: "Carbon Gray", code: "#625D5D", color: "#FFFFFF" },
  { name: "Charcoal", code: "#36454F", color: "#FFFFFF" },
  { name: "Granola", code: "#D6B85A", color: "#000000" },
  { name: "Oat", code: "#DFC98A", color: "#000000" },
  { name: "Cinereous", code: "#98817B", color: "#FFFFFF" },
  { name: "Cool Gray", code: "#9090C0", color: "#FFFFFF" },
  { name: "Dark Gray", code: "#A9A9A9", color: "#000000" },
  { name: "Davy's Gray", code: "#555555", color: "#FFFFFF" },
  { name: "Deep Space Sparkle", code: "#4A646C", color: "#FFFFFF" },
  { name: "Dim Gray", code: "#696969", color: "#FFFFFF" },
  { name: "Gainsboro", code: "#DCDCDC", color: "#000000" },
  { name: "Gray", code: "#808080", color: "#FFFFFF" },
  { name: "Gray Cloud", code: "#B6B6B4", color: "#000000" },
  { name: "Gray Dolphin", code: "#5C5858", color: "#FFFFFF" },
  { name: "Gray Goose", code: "#D1D0CE", color: "#000000" },
  { name: "Gray-Green", code: "#5E716A", color: "#FFFFFF" },
  { name: "Gray Wolf", code: "#504A4B", color: "#FFFFFF" },
  { name: "Glaucous", code: "#6082B6", color: "#FFFFFF" },
  { name: "Gunmetal", code: "#2A3439", color: "#FFFFFF" },
  { name: "Jet", code: "#343434", color: "#FFFFFF" },
  { name: "Jet Gray", code: "#616D7E", color: "#FFFFFF" },
  { name: "Light Gray", code: "#D3D3D3", color: "#000000" },
  { name: "Light Slate Gray", code: "#6D7B8D", color: "#FFFFFF" },
  { name: "Marengo", code: "#4C5866", color: "#FFFFFF" },
  { name: "Medium Gray", code: "#BEBEBE", color: "#000000" },
  { name: "Nevada", code: "#666A6D", color: "#FFFFFF" },
  { name: "Nickel", code: "#727472", color: "#FFFFFF" },
  { name: "Old Silver", code: "#848482", color: "#FFFFFF" },
  { name: "Outer Space", code: "#414A4C", color: "#FFFFFF" },
  { name: "Rocket Metallic", code: "#8A7F8D", color: "#FFFFFF" },
  { name: "Scorpion", code: "#5E5E5E", color: "#FFFFFF" },
  { name: "Silver", code: "#C0C0C0", color: "#000000" },
  { name: "Silver Chalice", code: "#ACACAC", color: "#FFFFFF" },
  { name: "Slate Blue", code: "#737CA1", color: "#FFFFFF" },
  { name: "Slate Gray", code: "#657383", color: "#FFFFFF" },
  { name: "Smoke", code: "#738276", color: "#FFFFFF" },
  { name: "Smokey Gray", code: "#726E6D", color: "#FFFFFF" },
  { name: "Sonic Gray", code: "#757575", color: "#FFFFFF" },
  { name: "Spanish Gray", code: "#989898", color: "#FFFFFF" },
  { name: "Stone Gray", code: "#928E85", color: "#FFFFFF" },
  { name: "Stormcloud", code: "#4F666A", color: "#FFFFFF" },
  { name: "Taupe Gray", code: "#8B8589", color: "#FFFFFF" },
  { name: "Timberwolf", code: "#DBD7D2", color: "#000000" },
  { name: "Payne's Gray", code: "#40404F", color: "#FFFFFF" },
  { name: "Pink Gray", code: "#E7DADA", color: "#000000" },
  { name: "Purple Gray", code: "#A7A6BA", color: "#FFFFFF" },
  { name: "Rose Quartz", code: "#AA98A9", color: "#FFFFFF" },
  { name: "Vampire Gray", code: "#565051", color: "#FFFFFF" },
  { name: "Bright Gray", code: "#E8E9EB", color: "#000000" },
  { name: "X11 Gray", code: "#BBBCB6", color: "#000000" },
  { name: "Dark Silver", code: "#746D69", color: "#FFFFFF" },
  { name: "Pastel Gray", code: "#CCCDC6", color: "#000000" },
  { name: "Dusty Gray", code: "#B29CA2", color: "#FFFFFF" },
  { name: "Misty Gray", code: "#BCC2C2", color: "#000000" },
  { name: "White Gray", code: "#F2F3F5", color: "#000000" },
  { name: "Vintage Gray", code: "#989692", color: "#FFFFFF" },
  { name: "Gentle Gray", code: "#DADADA", color: "#000000" },
  { name: "Zombie Gray", code: "#63645E", color: "#FFFFFF" },
  { name: "Lavender Gray", code: "#C4C3D0", color: "#000000" },
  { name: "Perfect Gray", code: "#A1A1A1", color: "#FFFFFF" },
  { name: "Graphite Gray", code: "#4B4E53", color: "#FFFFFF" },
  { name: "Rustic Gray", code: "#A6ABA5", color: "#000000" },
  { name: "Echo", code: "#898D86", color: "#FFFFFF" },
  { name: "Window Gray", code: "#989EA1", color: "#FFFFFF" },
  { name: "Silk Gray", code: "#B6B3A8", color: "#000000" },
  { name: "Light Gunmetal", code: "#344148", color: "#FFFFFF" },
  { name: "Silver Pink", code: "#C4AEAD", color: "#000000" },
  { name: "Matte Silver", code: "#A5A5A8", color: "#000000" },
  { name: "Rhythm", code: "#777696", color: "#FFFFFF" },
  { name: "Pure Silver", code: "#C3C7C7", color: "#000000" },
  { name: "Best Gray", code: "#969892", color: "#FFFFFF" },
  { name: "Agreeable Gray", code: "#D1CBC1", color: "#000000" },
  { name: "Oxford Gray", code: "#8391A1", color: "#FFFFFF" },
  { name: "Antique Pewter", code: "#808992", color: "#FFFFFF" },
  { name: "Warm Gray", code: "#6E6259", color: "#FFFFFF" },
  { name: "Sage Gray", code: "#B5BDA5", color: "#000000" },
  { name: "Dull Gray", code: "#8B837E", color: "#FFFFFF" },
  { name: "Rich Gray", code: "#1F2022", color: "#FFFFFF" },
  { name: "Ice Gray", code: "#BEC3C6", color: "#000000" },
  { name: "Gray CMYK", code: "#939598", color: "#000000" },
  { name: "Solid Gray", code: "#979797", color: "#000000" },
  { name: "Electric Gray", code: "#A5ADAD", color: "#000000" },
  { name: "Templetion Gray", code: "#788787", color: "#FFFFFF" },
  { name: "Chrome", code: "#DBE2E9", color: "#000000" },
  { name: "Sea Gray", code: "#9AA2A4", color: "#FFFFFF" },
  { name: "Glossy Gray", code: "#AFADA9", color: "#000000" },
  { name: "Anvil Gray", code: "#6B6B6B", color: "#FFFFFF" },
  { name: "Chameleon Gray", code: "#686965", color: "#FFFFFF" },
  { name: "Cement Gray", code: "#858A7E", color: "#FFFFFF" },
  { name: "Steel Gray", code: "#888B8D", color: "#FFFFFF" },
  { name: "Dorian Gray", code: "#ACA79E", color: "#000000" },
  { name: "Gun Smoke Gray", code: "#8A868E", color: "#FFFFFF" },
  { name: "Camouflage Gray", code: "#545851", color: "#FFFFFF" },
  { name: "Fashion Gray", code: "#8E8D8C", color: "#FFFFFF" },
  { name: "Neutral Gray", code: "#898E8C", color: "#FFFFFF" },
  { name: "Revere Pewter", code: "#CCC7B9", color: "#000000" },
  { name: "Olive Gray", code: "#A09F8D", color: "#FFFFFF" },
  { name: "Metallic Gray", code: "#A8A9AD", color: "#000000" },
  { name: "French Gray", code: "#B4B19A", color: "#000000" },
  { name: "Iron", code: "#A59C94", color: "#FFFFFF" },
  { name: "Pale Smoke", code: "#CAD4D1", color: "#000000" },
  { name: "Bone", code: "#D7D2CB", color: "#000000" },
  { name: "Heather", code: "#9AA297", color: "#FFFFFF" },
  { name: "True Silver", code: "#8A8D8F", color: "#FFFFFF" },
  { name: "Power Gray", code: "#707272", color: "#FFFFFF" },
  { name: "Storm Gray", code: "#B5BAB6", color: "#000000" },
  { name: "Ultimate Gray", code: "#939597", color: "#FFFFFF" },
  { name: "Rhino", code: "#B9BBB6", color: "#000000" },
  { name: "Harbor Gray", code: "#C7C6C1", color: "#000000" },
  { name: "Seal", code: "#818380", color: "#FFFFFF" },
  { name: "Anchor", code: "#3E424B", color: "#FFFFFF" },
  { name: "Abalone", code: "#D6CFC7", color: "#000000" },
  { name: "Fossil", code: "#787276", color: "#FFFFFF" },
  { name: "Mink", code: "#888078", color: "#FFFFFF" },
  { name: "Trout", code: "#979788", color: "#FFFFFF" },
  { name: "Thunder", code: "#BDB7AB", color: "#000000" },
  { name: "Shades On", code: "#606060", color: "#FFFFFF" },
  { name: "Lava", code: "#808588", color: "#FFFFFF" },
  { name: "Stone Eagle", code: "#D8D9DA", color: "#000000" },
  { name: "Ice Cube", code: "#E3E4E0", color: "#000000" },
  { name: "Porpoise", code: "#4D4D5C", color: "#FFFFFF" },
  { name: "Flint", code: "#7E7D9C", color: "#FFFFFF" },
  { name: "Dove", code: "#7C6E7F", color: "#FFFFFF" },
  { name: "Gray Owl", code: "#D5D5CD", color: "#000000" },
  { name: "Coin", code: "#9897A9", color: "#FFFFFF" },
  { name: "Fog", code: "#655967", color: "#FFFFFF" },
  { name: "Shadow", code: "#373737", color: "#FFFFFF" },
  { name: "Laid Back Gray", code: "#B4AFA9", color: "#000000" },
];

const shadesOfPurple = [
  { name: "True Purple", code: "#6A0DAD", color: "#FFFFFF" },
  { name: "Thistle", code: "#D8BFD8", color: "#000000" },
  { name: "Plum", code: "#DDA0DD", color: "#000000" },
  { name: "Violet", code: "#8F00FF", color: "#FFFFFF" },
  { name: "Orchid", code: "#DA70D6", color: "#000000" },
  { name: "Fuchsia", code: "#FF00FF", color: "#000000" },
  { name: "Medium Orchid", code: "#BA55D3", color: "#FFFFFF" },
  { name: "Medium Purple", code: "#9370DB", color: "#FFFFFF" },
  { name: "Blue Violet", code: "#8A2BE2", color: "#FFFFFF" },
  { name: "Dark Violet", code: "#9400D3", color: "#FFFFFF" },
  { name: "Dark Orchid", code: "#9932CC", color: "#FFFFFF" },
  { name: "Dark Magenta", code: "#8B008B", color: "#FFFFFF" },
  { name: "Indigo", code: "#4B0082", color: "#FFFFFF" },
  { name: "Veronica", code: "#A020F0", color: "#FFFFFF" },
  { name: "Pale Purple", code: "#FAE6FA", color: "#000000" },
  { name: "Mauve", code: "#D0B0FF", color: "#000000" },
  { name: "Heliotrope", code: "#DF73FF", color: "#000000" },
  { name: "Phlox", code: "#DF00FF", color: "#000000" },
  { name: "Purple Pizzazz", code: "#FE4EDA", color: "#000000" },
  { name: "Liserian Purple", code: "#DE6FA1", color: "#FFFFFF" },
  { name: "Mulberry", code: "#C54B8C", color: "#FFFFFF" },
  { name: "Pearly Purple", code: "#B768A2", color: "#FFFFFF" },
  { name: "Purpureus", code: "#9A4EAE", color: "#FFFFFF" },
  { name: "Northwestern Purple", code: "#4E2A84", color: "#FFFFFF" },
  { name: "KSU Purple", code: "#512888", color: "#FFFFFF" },
  { name: "Pomp and Power", code: "#86608E", color: "#FFFFFF" },
  { name: "Mardi Gras", code: "#880085", color: "#FFFFFF" },
  { name: "Eminence", code: "#6C3082", color: "#FFFFFF" },
  { name: "Pansy Purple", code: "#78184A", color: "#FFFFFF" },
  { name: "Palatinate", code: "#72246C", color: "#FFFFFF" },
  { name: "Dark Purple", code: "#301934", color: "#FFFFFF" },
  { name: "Byzantium", code: "#702963", color: "#FFFFFF" },
  { name: "African Violet", code: "#B284BE", color: "#FFFFFF" },
  { name: "Amethyst", code: "#9966CC", color: "#FFFFFF" },
  { name: "Chinese Violet", code: "#856088", color: "#FFFFFF" },
  { name: "English Violet", code: "#563C5C", color: "#FFFFFF" },
  { name: "Russian Violet", code: "#32174D", color: "#FFFFFF" },
  { name: "Fairy Tale", code: "#F2C1D1", color: "#000000" },
  { name: "Fandango", code: "#B55338", color: "#FFFFFF" },
  { name: "French Mauve", code: "#D473D4", color: "#000000" },
  { name: "Affair", code: "#6F4685", color: "#FFFFFF" },
  { name: "Boss's Jokes", code: "#B0306A", color: "#FFFFFF" },
  { name: "iris", code: "#9867C5", color: "#FFFFFF" },
  { name: "Long Distance", code: "#6F456E", color: "#FFFFFF" },
  { name: "Prince Charming", code: "#493F5E", color: "#FFFFFF" },
  { name: "Lipstick Stain", code: "#8E4785", color: "#FFFFFF" },
  { name: "Pompadour", code: "#770058", color: "#FFFFFF" },
  { name: "Grape Color", code: "#6F2DA8", color: "#FFFFFF" },
  { name: "Wine", code: "#2C041C", color: "#FFFFFF" },
  { name: "Pizza Edge", code: "#9A2CA0", color: "#FFFFFF" },
  { name: "Tyrian Purple", code: "#66023C", color: "#FFFFFF" },
  { name: "Ultra Violet", code: "#645394", color: "#FFFFFF" },
  { name: "Studio", code: "#7851A9", color: "#FFFFFF" },
  { name: "Electric Purple", code: "#BF00FF", color: "#FFFFFF" },
  { name: "Eggplant", code: "#311432", color: "#FFFFFF" },
  { name: "Periwinkle Purple", code: "#BE93E4", color: "#000000" },
  { name: "Sangria", code: "#4D0F28", color: "#FFFFFF" },
  { name: "Raisin", code: "#290916", color: "#FFFFFF" },
  { name: "Mountbatten Pink", code: "#997A8D", color: "#FFFFFF" },
  { name: "Fuchsia Blue", code: "#9C51B6", color: "#FFFFFF" },
  { name: "Good Tax", code: "#C9A0FF", color: "#000000" },
  { name: "Jam", code: "#67032F", color: "#FFFFFF" },
  { name: "Ripe Plum", code: "#410056", color: "#FFFFFF" },
  { name: "Heather", code: "#9E7BB5", color: "#FFFFFF" },
  { name: "Magenta Purple", code: "#A32CC4", color: "#FFFFFF" },
  { name: "Mountain's Majesty", code: "#9078C0", color: "#FFFFFF" },
  { name: "Old Lavender", code: "#796878", color: "#FFFFFF" },
  { name: "Rebecca Purple", code: "#663399", color: "#FFFFFF" },
  { name: "Razzmic Berry Purple", code: "#8D4E85", color: "#FFFFFF" },
  { name: "Wine Dregs Purple", code: "#673147", color: "#FFFFFF" },
  { name: "Regalia Purple", code: "#522D80", color: "#FFFFFF" },
  { name: "Twilight Lavender Purple", code: "#8A496B", color: "#FFFFFF" },
  { name: "Traditional Purple", code: "#8E4585", color: "#FFFFFF" },
  { name: "Spanish Violet Purple", code: "#4C2882", color: "#FFFFFF" },
  { name: "Imperial Purple", code: "#602F6B", color: "#FFFFFF" },
  { name: "Japanese Violet Purple", code: "#5B3256", color: "#FFFFFF" },
  { name: "Munshell Purple", code: "#9F00C5", color: "#FFFFFF" },
  { name: "Deep Ruby Purple", code: "#843F5B", color: "#FFFFFF" },
  { name: "Purple Heart", code: "#7442C8", color: "#FFFFFF" },
  { name: "Lavender Blush", code: "#FFF0F5", color: "#000000" },
  { name: "Early Bird", code: "#CEA2FD", color: "#000000" },
  { name: "Lilac", code: "#B65FCF", color: "#FFFFFF" },
  { name: "Purple Taupe", code: "#50404D", color: "#FFFFFF" },
  { name: "Cyber Grape Purple", code: "#58427C", color: "#FFFFFF" },
  { name: "Kingfisher Daisy", code: "#653780", color: "#FFFFFF" },
  { name: "Seance", code: "#61346B", color: "#FFFFFF" },
  { name: "Lavender Gray", code: "#B6B5D8", color: "#000000" },
  { name: "Hopbush", code: "#D05FAD", color: "#FFFFFF" },
  { name: "Tacao", code: "#6F3096", color: "#FFFFFF" },
  { name: "Brilliant Purple", code: "#D399E6", color: "#000000" },
  { name: "Murasaki Purple", code: "#4F284B", color: "#FFFFFF" },
  { name: "Blackish Purple", code: "#291E29", color: "#FFFFFF" },
  { name: "Lovely Purple", code: "#7F38EC", color: "#FFFFFF" },
  { name: "Vulgar Purple", code: "#3E2F84", color: "#FFFFFF" },
  { name: "FedEx Purple", code: "#660099", color: "#FFFFFF" },
  { name: "Carolina Plum", code: "#9B84A1", color: "#FFFFFF" },
  { name: "Kalamata", code: "#705160", color: "#FFFFFF" },
  { name: "Black Currant", code: "#540E32", color: "#FFFFFF" },
  { name: "Purple 4", code: "#551A8B", color: "#FFFFFF" },
  { name: "Strong Purple", code: "#876592", color: "#FFFFFF" },
  { name: "Pale Purple", code: "#AA98A9", color: "#000000" },
  { name: "Vivid Reddish Purple", code: "#870074", color: "#FFFFFF" },
  { name: "Medium Purple 3", code: "#8968CD", color: "#FFFFFF" },
  { name: "Middle Purple", code: "#D982B5", color: "#000000" },
  { name: "Cardinal", code: "#8A244E", color: "#FFFFFF" },
  { name: "Embassy Purple", code: "#3B343C", color: "#FFFFFF" },
  { name: "Lakers Purple", code: "#552582", color: "#FFFFFF" },
  { name: "Amaranth Purple", code: "#AB274F", color: "#FFFFFF" },
  { name: "Purple Navy", code: "#4E5180", color: "#FFFFFF" },
  { name: "Insolent Purple", code: "#682E3C", color: "#FFFFFF" },
  { name: "Smyrna Purple", code: "#A2627A", color: "#FFFFFF" },
  { name: "Little Princess", code: "#E9DCE5", color: "#000000" },
  { name: "Aesthetic Purple", code: "#502380", color: "#FFFFFF" },
  { name: "Kikyo-iru", code: "#5D3FCA", color: "#FFFFFF" },
  { name: "Metallic Purple", code: "#520E7D", color: "#FFFFFF" },
  { name: "Hot Purple", code: "#A420D0", color: "#FFFFFF" },
  { name: "Faded Purple", code: "#795F80", color: "#FFFFFF" },
  { name: "Mythical Purple", code: "#53277E", color: "#FFFFFF" },
  { name: "Languid Lavender", code: "#D6CADD", color: "#000000" },
  { name: "Mauveine", code: "#8D029B", color: "#FFFFFF" },
  { name: "Blue Lilac", code: "#7B679A", color: "#FFFFFF" },
  { name: "Dark Byzantium", code: "#5D3954", color: "#FFFFFF" },
  { name: "Luxury People", code: "#743089", color: "#FFFFFF" },
  { name: "Aztech Purple", code: "#893BFF", color: "#FFFFFF" },
  { name: "Baltimore Ravens Purple", code: "#280353", color: "#FFFFFF" },
  { name: "Deep Magenta", code: "#CC00CC", color: "#FFFFFF" },
  { name: "Deep Purple", code: "#524F81", color: "#FFFFFF" },
  { name: "Rustic Purple", code: "#593163", color: "#FFFFFF" },
  { name: "Sunset Purple", code: "#A865B5", color: "#FFFFFF" },
  { name: "Artist's Purple", code: "#C71585", color: "#FFFFFF" },
  { name: "Dull Purple", code: "#9861A5", color: "#FFFFFF" },
  { name: "Traffic Purple", code: "#913073", color: "#FFFFFF" },
  { name: "Matte Purple", code: "#392A48", color: "#FFFFFF" },
  { name: "Purple Violet", code: "#47243C", color: "#FFFFFF" },
  { name: "Purple CMYK", code: "#6A317F", color: "#FFFFFF" },
  { name: "Ocean Purple", code: "#6E2D91", color: "#FFFFFF" },
  { name: "Shiny Purple", code: "#B941FF", color: "#FFFFFF" },
  { name: "Autumn Purple", code: "#834468", color: "#FFFFFF" },
];

const shadesOfYellow = [
  { name: "Sunshine Yellow", code: "#FFFD37", color: "#FFFFFF" },
  { name: "Canary Yellow", code: "#FFEF00", color: "#FFFFFF" },
  { name: "Lemon Yellow", code: "#FDFF00", color: "#FFFFFF" },
  { name: "Goldenrod", code: "#DAA520", color: "#FFFFFF" },
  { name: "Saffron", code: "#F4C430", color: "#FFFFFF" },
  { name: "Hazelwood", code: "#C9BB8E", color: "#FFFFFF" },
  { name: "Citrine", code: "#E4D00A", color: "#FFFFFF" },
  { name: "Tombone", code: "#D2B55B", color: "#FFFFFF" },
  { name: "Light Yellow", code: "#FFFFE0", color: "#FFFFFF" },
  { name: "Lemon Chiffon", code: "#FFFACD", color: "#FFFFFF" },
  { name: "Flax", code: "#EEDC82", color: "#FFFFFF" },
  { name: "Light Goldenrod", code: "#FAFAD2", color: "#FFFFFF" },
  { name: "Pale Goldenrod", code: "#EEE8AA", color: "#FFFFFF" },
  { name: "Light Khaki", code: "#F0E68C", color: "#FFFFFF" },
  { name: "Clover Lime", code: "#FCE883", color: "#FFFFFF" },
  { name: "Xanthic", code: "#EEED09", color: "#FFFFFF" },
  { name: "Royal Yellow", code: "#FADA5E", color: "#FFFFFF" },
  { name: "Cream", code: "#FFFFCC", color: "#FFFFFF" },
  { name: "Gold", code: "#FFD700", color: "#FFFFFF" },
  { name: "Safety Yellow", code: "#EED202", color: "#FFFFFF" },
  { name: "Laguna", code: "#F8E473", color: "#FFFFFF" },
  { name: "Hunyadi Yellow", code: "#E8AC41", color: "#FFFFFF" },
  { name: "Bright Yellow", code: "#FFFD01", color: "#FFFFFF" },
  { name: "Greenish Yellow", code: "#EEEA62", color: "#FFFFFF" },
  { name: "Neon Yellow", code: "#CFFF04", color: "#FFFFFF" },
  { name: "Dark Yellow", code: "#D5B60A", color: "#FFFFFF" },
  { name: "Sand", code: "#E2CA76", color: "#FFFFFF" },
  { name: "Sunflower", code: "#FFDA03", color: "#FFFFFF" },
  { name: "Bumblebee", code: "#FCE205", color: "#FFFFFF" },
  { name: "Butter", code: "#FFFD74", color: "#FFFFFF" },
  { name: "Yellow Tan", code: "#FFE36E", color: "#FFFFFF" },
  { name: "Cyber Yellow", code: "#FFD300", color: "#FFFFFF" },
  { name: "Banana", code: "#FFE135", color: "#FFFFFF" },
  { name: "Tuscany", code: "#FCD12A", color: "#FFFFFF" },
  { name: "Honey", code: "#FFC30B", color: "#FFFFFF" },
  { name: "Dijon", code: "#C49102", color: "#FFFFFF" },
  { name: "Amber", code: "#FFBF00", color: "#FFFFFF" },
  { name: "Beige", code: "#F5F5DC", color: "#FFFFFF" },
  { name: "Mustard", code: "#FEDC56", color: "#FFFFFF" },
  { name: "Maximum Yellow", code: "#FAFA37", color: "#FFFFFF" },
  { name: "Mellow Yellow", code: "#F8DE7E", color: "#FFFFFF" },
  { name: "Unmellow Yellow", code: "#FFFF66", color: "#FFFFFF" },
  { name: "Lemon Curry", code: "#CCA01D", color: "#FFFFFF" },
  { name: "Moccasin", code: "#FFE4B5", color: "#FFFFFF" },
  { name: "Orange Yellow", code: "#FFAD01", color: "#FFFFFF" },
  { name: "Pastel Yellow", code: "#FFFE71", color: "#FFFFFF" },
  { name: "Taxi Cab Yellow", code: "#FDB813", color: "#FFFFFF" },
  { name: "Aureolin", code: "#FDEE00", color: "#FFFFFF" },
  { name: "Electric Yellow", code: "#FFFF33", color: "#FFFFFF" },
  { name: "Chartreuse", code: "#DFFF00", color: "#FFFFFF" },
  { name: "Titanium Yellow", code: "#EEE600", color: "#FFFFFF" },
  { name: "Mikado Yellow", code: "#FFC40C", color: "#FFFFFF" },
  { name: "Fluorescent Yellow", code: "#CCFF00", color: "#FFFFFF" },
  { name: "Arylide Yellow", code: "#E9D66B", color: "#FFFFFF" },
  { name: "Indian Yellow", code: "#E3A857", color: "#FFFFFF" },
  { name: "Durian Yellow", code: "#E1BD27", color: "#FFFFFF" },
  { name: "Minion Yellow", code: "#F5E050", color: "#FFFFFF" },
  { name: "Selective Yellow", code: "#FFBA00", color: "#FFFFFF" },
  { name: "Laser Lemon", code: "#FEFE22", color: "#FFFFFF" },
  { name: "Munsell Yellow", code: "#EFCC00", color: "#FFFFFF" },
  { name: "Yellow Rose", code: "#FFF000", color: "#FFFFFF" },
  { name: "Very Pale Yellow", code: "#FFFFBF", color: "#FFFFFF" },
  { name: "Earth Yellow", code: "#E1A95F", color: "#FFFFFF" },
  { name: "Yellow (Pantone)", code: "#FEDF00", color: "#FFFFFF" },
  { name: "Tangerine Yellow", code: "#FFCC00", color: "#FFFFFF" },
  { name: "Bronze Yellow", code: "#737000", color: "#FFFFFF" },
  { name: "Psychedelic Yellow", code: "#FFF53D", color: "#FFFFFF" },
  { name: "Maize Yellow (RAL)", code: "#DB9100", color: "#FFFFFF" },
  { name: "Muted Yellow", code: "#E0D268", color: "#FFFFFF" },
  { name: "Sulfur Yellow", code: "#E8DE35", color: "#FFFFFF" },
  { name: "Yellow jasmine", code: "#CEB00D", color: "#FFFFFF" },
  { name: "Dusty Yellow", code: "#D4CC9A", color: "#FFFFFF" },
  { name: "Yolk Yellow (Pantone)", code: "#E2B051", color: "#FFFFFF" },
  { name: "Light Chrome Yellow", code: "#FFCA37", color: "#FFFFFF" },
  { name: "Cadmium Yellow lemon", code: "#FFF23E", color: "#FFFFFF" },
  { name: "Vibrant Yellow", code: "#FFDA29", color: "#FFFFFF" },
  { name: "Yellow CMYK", code: "#FFFF00", color: "#FFFFFF" },
  { name: "Fire Yellow", code: "#FEDE17", color: "#FFFFFF" },
  { name: "Buff Yellow", code: "#F1BF70", color: "#FFFFFF" },
  { name: "Yellow Cream", code: "#EFDC75", color: "#FFFFFF" },
  { name: "Empire Yellow", code: "#F7D000", color: "#FFFFFF" },
  { name: "Zinc Yellow (RAL)", code: "#F2CB2E", color: "#FFFFFF" },
  { name: "Signal Yellow", code: "#F2A900", color: "#FFFFFF" },
  { name: "Matte Yellow", code: "#EDD94C", color: "#FFFFFF" },
  { name: "Aesthetic Yellow", code: "#EFD033", color: "#FFFFFF" },
  { name: "Rustic Yellow", code: "#E2C400", color: "#FFFFFF" },
  { name: "Pale Yellow", code: "#FFFFA7", color: "#FFFFFF" },
  { name: "Colza Yellow", code: "#EEB700", color: "#FFFFFF" },
  { name: "Transparent Yellow", code: "#F4ECC2", color: "#FFFFFF" },
  { name: "Blazing Yellow", code: "#FEE715", color: "#FFFFFF" },
  { name: "Tender Yellow", code: "#EDEEB7", color: "#FFFFFF" },
  { name: "Plae Lime Yellow", code: "#DFE69F", color: "#FFFFFF" },
  { name: "Vintage Yellow", code: "#CBA92B", color: "#FFFFFF" },
  { name: "Spectrum Yellow", code: "#FCE517", color: "#FFFFFF" },
  { name: "Retro Yellow", code: "#F0E27B", color: "#FFFFFF" },
  { name: "Old Yellow", code: "#C8AF55", color: "#FFFFFF" },
  { name: "Chinese Yellow", code: "#FFB200", color: "#FFFFFF" },
  { name: "Spanish Yellow", code: "#F9D73D", color: "#FFFFFF" },
  { name: "Refresh Yellow", code: "#FFE992", color: "#FFFFFF" },
  { name: "Sun Yellow (RAL)", code: "#EA9300", color: "#FFFFFF" },
  { name: "Baby Yellow", code: "#FCEF91", color: "#FFFFFF" },
  { name: "Dahila Yellow (RAL)", code: "#F39B1B", color: "#FFFFFF" },
  { name: "Broom Yellow", code: "#DBA400", color: "#FFFFFF" },
  { name: "Camouflage Yellow", code: "#978942", color: "#FFFFFF" },
  { name: "Trust Yellow", code: "#EEBE15", color: "#FFFFFF" },
  { name: "Warm Yellow", code: "#F4E98C", color: "#FFFFFF" },
  { name: "Vivid Yellow", code: "#FFE302", color: "#FFFFFF" },
  { name: "Turmeric", code: "#F0CA28", color: "#FFFFFF" },
  { name: "Sunglow", code: "#FFCC33", color: "#FFFFFF" },
  { name: "Light Saffron", code: "#FFE797", color: "#FFFFFF" },
  { name: "Radioactive", code: "#FAE500", color: "#FFFFFF" },
  { name: "Golden Poppy", code: "#FCC200", color: "#FFFFFF" },
  { name: "Real Gold", code: "#E2BF36", color: "#FFFFFF" },
  { name: "Glossy Gold", code: "#FAE481", color: "#FFFFFF" },
  { name: "Snapchat Yellow", code: "#FFFC00", color: "#FFFFFF" },
  { name: "Deep Chrome Yellow", code: "#FFB045", color: "#FFFFFF" },
  { name: "Melon Yellow", code: "#FF9C00", color: "#FFFFFF" },
  { name: "Bright Canary Yellow", code: "#FFE41E", color: "#FFFFFF" },
  { name: "Deep Napoli Yellow", code: "#FFCF99", color: "#FFFFFF" },
  { name: "Radiant Yellow", code: "#FC9E21", color: "#FFFFFF" },
  { name: "Daffodil Yellow", code: "#E28D00", color: "#FFFFFF" },
  { name: "Mineral Yellow", code: "#D39C43", color: "#FFFFFF" },
  { name: "Relax Yellow", code: "#F3E496", color: "#FFFFFF" },
  { name: "Rainbow Yellow", code: "#F5DE10", color: "#FFFFFF" },
  { name: "Deep Yellow", code: "#EACE09", color: "#FFFFFF" },
  { name: "Ochre Yellow", code: "#B5904B", color: "#FFFFFF" },
  { name: "Dull Yellow", code: "#DECA57", color: "#FFFFFF" },
  { name: "Hot Yellow", code: "#FFDA00", color: "#FFFFFF" },
  { name: "Traffic Yellow", code: "#EFB700", color: "#FFFFFF" },
  { name: "Yellow Orange", code: "#D56F00", color: "#FFFFFF" },
  { name: "Olive Yellow", code: "#9D8F65", color: "#FFFFFF" },
  { name: "Faded Yellow", code: "#ECE3A1", color: "#FFFFFF" },
  { name: "Solid Yellow", code: "#FFE81C", color: "#FFFFFF" },
  { name: "Golden Yellow", code: "#DD9F00", color: "#FFFFFF" },
  { name: "Corn", code: "#FBEC5D", color: "#FFFFFF" },
  { name: "Fawn", code: "#C8A951", color: "#FFFFFF" },
  { name: "Dandelion", code: "#F0E130", color: "#FFFFFF" },
  { name: "Icterine", code: "#FCF75E", color: "#FFFFFF" },
  { name: "Sandstorm", code: "#ECD540", color: "#FFFFFF" },
  { name: "Macaroon", code: "#F9E076", color: "#FFFFFF" },
  { name: "Urobilin", code: "#E1AD21", color: "#FFFFFF" },
  { name: "Satin Sheen Gold", code: "#CBA135", color: "#FFFFFF" },
  { name: "School Bus Yellow", code: "#FFD800", color: "#FFFFFF" },
  { name: "British Standard Yellow", code: "#EDC001", color: "#FFFFFF" },
  { name: "Mimosa", code: "#FFF4BC", color: "#FFFFFF" },
  { name: "Marigold", code: "#FCB810", color: "#FFFFFF" },
  { name: "Shortbread", code: "#FBE790", color: "#FFFFFF" },
  { name: "Buttermilk", code: "#FDEFB2", color: "#FFFFFF" },
  { name: "Daisy Yellow", code: "#F8DC75", color: "#FFFFFF" },
  { name: "Sepia", code: "#E3B778", color: "#FFFFFF" },
  { name: "Biscotti", code: "#E3C565", color: "#FFFFFF" },
  { name: "Parmesean", code: "#FDE992", color: "#FFFFFF" },
  { name: "Sandcastle", code: "#DAC17C", color: "#FFFFFF" },
  { name: "Sand", code: "#D8B863", color: "#FFFFFF" },
  { name: "Egg Nog", code: "#FAE29C", color: "#FFFFFF" },
  { name: "Suger Cookie", code: "#F3EAAF", color: "#FFFFFF" },
];

const shadesOfBrown = [
  { name: "Almond", code: "#EFDECD", color: "#000000" },
  { name: "Auburn", code: "#A52A2A", color: "#FFFFFF" },
  { name: "Beaver", code: "#9F8170", color: "#FFFFFF" },
  { name: "Beige", code: "#F5F5DC", color: "#000000" },
  { name: "Bisque", code: "#FFE4C4", color: "#000000" },
  { name: "Bistre", code: "#3D2B1F", color: "#FFFFFF" },
  { name: "Bole", code: "#79443B", color: "#FFFFFF" },
  { name: "Bone", code: "#E3DAC9", color: "#000000" },
  { name: "Brass", code: "#B5A642", color: "#FFFFFF" },
  { name: "Bronze", code: "#CD7F32", color: "#FFFFFF" },
  { name: "Brunt Umber", code: "#8A3324", color: "#FFFFFF" },
  { name: "Cafe Au Lait", code: "#A67B5B", color: "#FFFFFF" },
  { name: "Cafe Noir", code: "#4B3621", color: "#FFFFFF" },
  { name: "Champagne", code: "#FAD6A5", color: "#000000" },
  { name: "Cinnamon", code: "#D2691E", color: "#FFFFFF" },
  { name: "Coffee", code: "#6F4E37", color: "#FFFFFF" },
  { name: "Deep Coffee", code: "#704242", color: "#FFFFFF" },
  { name: "Copper", code: "#B87333", color: "#FFFFFF" },
  { name: "Dark Brown", code: "#654321", color: "#FFFFFF" },
  { name: "Taupe", code: "#483C32", color: "#FFFFFF" },
  { name: "Tan", code: "#D2B48C", color: "#000000" },
  { name: "Chestnut", code: "#CD5C5C", color: "#FFFFFF" },
  { name: "Sand", code: "#F6D780", color: "#000000" },
  { name: "Ecru", code: "#C2B280", color: "#000000" },
  { name: "Fawn", code: "#E5AA70", color: "#000000" },
  { name: "Ginger", code: "#B06500", color: "#FFFFFF" },
  { name: "Golden Brown", code: "#996515", color: "#FFFFFF" },
  { name: "Khaki", code: "#C3B091", color: "#000000" },
  { name: "Mahogany", code: "#C04000", color: "#FFFFFF" },
  { name: "Ochre", code: "#CC7722", color: "#FFFFFF" },
  { name: "Light Brown", code: "#B5651D", color: "#FFFFFF" },
  { name: "Saddle Brown", code: "#8B4513", color: "#FFFFFF" },
  { name: "Wheat", code: "#F5DEB3", color: "#000000" },
  { name: "Russet", code: "#80461B", color: "#FFFFFF" },
  { name: "Rust", code: "#B7410E", color: "#FFFFFF" },
  { name: "Sepia", code: "#704214", color: "#FFFFFF" },
  { name: "Sienna", code: "#A0522D", color: "#FFFFFF" },
  { name: "Antique Brass", code: "#CD9575", color: "#000000" },
  { name: "Burlywood", code: "#DEB887", color: "#000000" },
  { name: "Peru", code: "#CD853F", color: "#FFFFFF" },
  { name: "Tumbleweed", code: "#DEAA88", color: "#000000" },
  { name: "Dark Vanilla", code: "#D1BEA8", color: "#000000" },
  { name: "Tuscan Brown", code: "#6F4E37", color: "#FFFFFF" },
  { name: "Wood Brown", code: "#C19A6B", color: "#FFFFFF" },
  { name: "Deer", code: "#BA8759", color: "#FFFFFF" },
  { name: "Chamoisee", code: "#A0785A", color: "#FFFFFF" },
  { name: "Dirt", code: "#9B7653", color: "#FFFFFF" },
  { name: "Coconut", code: "#965A3E", color: "#FFFFFF" },
  { name: "Windsor Tan", code: "#A75502", color: "#FFFFFF" },
  { name: "Rufous", code: "#A81C07", color: "#FFFFFF" },
  { name: "Acorn", code: "#D7A98C", color: "#000000" },
  { name: "Ash Brown", code: "#98623C", color: "#FFFFFF" },
  { name: "Ash Gray", code: "#C1B5A9", color: "#000000" },
  { name: "Ash White", code: "#E9E4D4", color: "#000000" },
  { name: "Baked Bread", code: "#DACBA9", color: "#000000" },
  { name: "Baked Potato", code: "#B69E87", color: "#FFFFFF" },
  { name: "Bamboo", code: "#E3DEC6", color: "#000000" },
  { name: "Bark", code: "#996633", color: "#FFFFFF" },
  { name: "Beeswax", code: "#E9D7AB", color: "#000000" },
  { name: "Beige Linen", code: "#E2DAC6", color: "#000000" },
  { name: "Birdseed", code: "#E2C28E", color: "#000000" },
  { name: "Bitter Chocolate", code: "#9E5B40", color: "#FFFFFF" },
  { name: "Brandy", code: "#DCB68A", color: "#000000" },
  { name: "Brown Bear", code: "#7F6244", color: "#FFFFFF" },
  { name: "Brown Beige", code: "#CC8833", color: "#FFFFFF" },
  { name: "Brown Coffee", code: "#4A2C2A", color: "#FFFFFF" },
  { name: "Brown Gray", code: "#8D8468", color: "#FFFFFF" },
  { name: "Brown Metal", code: "#BBADA1", color: "#000000" },
  { name: "Brown Red", code: "#922B05", color: "#FFFFFF" },
  { name: "Brown Rust", code: "#AF593E", color: "#FFFFFF" },
  { name: "Brown Stone", code: "#593C39", color: "#FFFFFF" },
  { name: "Brown Sugar", code: "#A17249", color: "#FFFFFF" },
  { name: "Brownie", code: "#964B00", color: "#FFFFFF" },
  { name: "Brownish Gray", code: "#86775F", color: "#FFFFFF" },
  { name: "Brownish Red", code: "#9E3623", color: "#FFFFFF" },
  { name: "Burnt Almond", code: "#B0724A", color: "#FFFFFF" },
  { name: "Burnt Henna", code: "#7E392F", color: "#FFFFFF" },
  { name: "Butter Toast", code: "#D2AD84", color: "#000000" },
  { name: "Buttercream", code: "#EFE0CD", color: "#000000" },
  { name: "Butter Brown", code: "#F1EBDA", color: "#000000" },
  { name: "Camel", code: "#C69F59", color: "#000000" },
  { name: "Canadian Maple", code: "#CAB266", color: "#000000" },
  { name: "Canvas Brown", code: "#BB8855", color: "#FFFFFF" },
  { name: "Caramel", code: "#AF6F09", color: "#FFFFFF" },
  { name: "Caramel Apple", code: "#B87A59", color: "#FFFFFF" },
  { name: "Caramel Brown", code: "#BB8866", color: "#FFFFFF" },
  { name: "Cashmere", code: "#D1B299", color: "#000000" },
  { name: "Chai", code: "#B1832F", color: "#FFFFFF" },
  { name: "Chamomile", code: "#DAC395", color: "#000000" },
  { name: "Chicory", code: "#A78658", color: "#FFFFFF" },
  { name: "Chocolate", code: "#7B3F00", color: "#FFFFFF" },
  { name: "Cinnamon Toast", code: "#8D7D77", color: "#FFFFFF" },
  { name: "Citrus Brown", code: "#D7C275", color: "#000000" },
  { name: "Cotton", code: "#FAF4D4", color: "#000000" },
  { name: "Croissant", code: "#C4AB86", color: "#000000" },
  { name: "Dark Beige", code: "#AC9362", color: "#FFFFFF" },
  { name: "Dark Chestnut", code: "#986960", color: "#FFFFFF" },
  { name: "Dark Khaki", code: "#9B8F55", color: "#FFFFFF" },
  { name: "Dark Sand", code: "#9F7D4F", color: "#FFFFFF" },
  { name: "Dark Wood", code: "#855E42", color: "#FFFFFF" },
  { name: "Deep Brown", code: "#410200", color: "#FFFFFF" },
  { name: "Deep Taupe", code: "#7B6660", color: "#FFFFFF" },
  { name: "Desert Gray", code: "#B8A487", color: "#FFFFFF" },
  { name: "Dried Moss", code: "#CCB97E", color: "#000000" },
  { name: "Dull Brown", code: "#876E4B", color: "#FFFFFF" },
  { name: "Fall Harvest", code: "#A78A59", color: "#FFFFFF" },
  { name: "Feather Brown", code: "#B8AD9E", color: "#000000" },
  { name: "Firewood", code: "#CEBAA8", color: "#000000" },
  { name: "Fortune Cookie", code: "#E0C5A1", color: "#000000" },
  { name: "French Beige", code: "#A67B50", color: "#FFFFFF" },
  { name: "Ginger Ale", code: "#C9A86A", color: "#000000" },
  { name: "Golden Fog", code: "#F0EAD2", color: "#000000" },
  { name: "Gray Brown", code: "#7F7053", color: "#FFFFFF" },
  { name: "Grayish Brown", code: "#7A6A4F", color: "#FFFFFF" },
  { name: "Hardwood", code: "#937A62", color: "#FFFFFF" },
  { name: "Hawaiian Brown", code: "#99522C", color: "#FFFFFF" },
  { name: "Heavy Brown", code: "#73624A", color: "#FFFFFF" },
  { name: "Honey Brown", code: "#BA9238", color: "#FFFFFF" },
  { name: "Iced Coffee", code: "#B18F6A", color: "#FFFFFF" },
  { name: "Kobicha", code: "#6B4423", color: "#FFFFFF" },
  { name: "Lace", code: "#EAE3D2", color: "#000000" },
  { name: "Latte", code: "#C5A582", color: "#000000" },
  { name: "Light Taupe", code: "#B38B6D", color: "#FFFFFF" },
  { name: "Maple Sugar", code: "#C9A38D", color: "#000000" },
  { name: "Maple Syrup", code: "#BB9351", color: "#FFFFFF" },
  { name: "Mars Brown", code: "#AD6242", color: "#FFFFFF" },
  { name: "Medium Brown", code: "#7F5112", color: "#FFFFFF" },
  { name: "Mojava Desert", code: "#C7B595", color: "#000000" },
];

const shadesOfOrange = [
  { name: "Dark Orange", code: "#FF8C00", color: "#000000" },
  { name: "Vivid Orange", code: "#FF5E0E", color: "#FFFFFF" },
  { name: "Orange-Red", code: "#FF4500", color: "#FFFFFF" },
  { name: "Tomato", code: "#FF6347", color: "#000000" },
  { name: "Metallic Orange", code: "#E26310", color: "#FFFFFF" },
  { name: "Pumpkin", code: "#75761A", color: "#FFFFFF" },
  { name: "Smashed Pumpkin", code: "#FD673A", color: "#000000" },
  { name: "Yellow Orange", code: "#FFA836", color: "#000000" },
  { name: "Carrot Orange", code: "#ED9121", color: "#000000" },
  { name: "International Orange", code: "#FF4700", color: "#FFFFFF" },
  { name: "Spanish Orange", code: "#F06105", color: "#FFFFFF" },
  { name: "Tangarine", code: "#F78702", color: "#000000" },
  { name: "Princeton Orange", code: "#FF8F00", color: "#000000" },
  { name: "Orioles Orange", code: "#FB4F14", color: "#FFFFFF" },
  { name: "Deep Saffron", code: "#FFA52C", color: "#000000" },
  { name: "Alloy Orange", code: "#C35214", color: "#FFFFFF" },
  { name: "Halloween Orange", code: "#EE5921", color: "#FFFFFF" },
  { name: "Tangelo", code: "#FC4C02", color: "#FFFFFF" },
  { name: "Gamboge", code: "#E89611", color: "#000000" },
  { name: "Vermilion", code: "#D74826", color: "#FFFFFF" },
  { name: "Medium Vermilion", code: "#CF5B2E", color: "#FFFFFF" },
  { name: "Fulvous", code: "#E68000", color: "#000000" },
  { name: "Pastel Orange", code: "#FEBA4F", color: "#000000" },
  { name: "Flame", code: "#E34A27", color: "#FFFFFF" },
  { name: "Philippine Orange", code: "#F26E01", color: "#FFFFFF" },
  { name: "Beer Orange", code: "#F28F1C", color: "#000000" },
  { name: "Chinese Orange", code: "#EB6841", color: "#000000" },
  { name: "Jasper Orange", code: "#E89149", color: "#000000" },
  { name: "Royal Orange", code: "#FF9944", color: "#000000" },
  { name: "Coral", code: "#FF7F50", color: "#000000" },
  { name: "Dark Coral", code: "#D75341", color: "#FFFFFF" },
  { name: "Cadmium Orange", code: "#E6812F", color: "#000000" },
  { name: "Dark Pastel Red", code: "#C34723", color: "#FFFFFF" },
  { name: "Copper Red", code: "#D97448", color: "#000000" },
  { name: "University Of Tennessee Orange", code: "#F77F00", color: "#000000" },
  { name: "Rajah", code: "#FABA5F", color: "#000000" },
  { name: "Mango Tango", code: "#FB8842", color: "#000000" },
  { name: "Orange Peel", code: "#FF9F00", color: "#000000" },
  { name: "Vivid Tangelo", code: "#EC7625", color: "#FFFFFF" },
  { name: "Burnt Umber", code: "#8A3324", color: "#FFFFFF" },
  { name: "Papaya Whip", code: "#FFF1D7", color: "#000000" },
  { name: "Bittersweet", code: "#FE6F5E", color: "#000000" },
  { name: "Persimmon", code: "#EC5800", color: "#FFFFFF" },
  { name: "Persian Orange", code: "#D99058", color: "#000000" },
  { name: "Terracotta", code: "#E2725B", color: "#000000" },
  { name: "Apricot Orange", code: "#FBCEB1", color: "#000000" },
  { name: "Bronze Orange", code: "#CD7F32", color: "#FFFFFF" },
  { name: "Browns Orange", code: "#FF3C00", color: "#FFFFFF" },
  { name: "Buff Orange", code: "#F2CA85", color: "#000000" },
  { name: "Bumblebee Orange", code: "#FFC82A", color: "#000000" },
  { name: "Burnt Orange", code: "#CC5500", color: "#FFFFFF" },
  { name: "Butterscotch Orange", code: "#D99151", color: "#FFFFFF" },
  { name: "Cheese Orange", code: "#FFA600", color: "#000000" },
  { name: "Chocolate Orange", code: "#D2691E", color: "#FFFFFF" },
  { name: "Cider Orange", code: "#D8A175", color: "#000000" },
  { name: "Copper Orange", code: "#BB772E", color: "#FFFFFF" },
  { name: "Crayola Orange", code: "#FF7538", color: "#FFFFFF" },
  { name: "Desert Orange", code: "#ED8E4A", color: "#FFFFFF" },
  { name: "Desert Sand Orange", code: "#EDC9AF", color: "#000000" },
  { name: "Dragon Fire Orange", code: "#FD652D", color: "#FFFFFF" },
  { name: "Dull Orange", code: "#DB804E", color: "#FFFFFF" },
  { name: "Giants Orange", code: "#FE5A1D", color: "#FFFFFF" },
  { name: "Ginger Orange", code: "#B06500", color: "#FFFFFF" },
  { name: "Golden Gate Bridge Orange", code: "#CO362C", color: "#000000" },
  { name: "Goldenrod Orange", code: "#DAA520", color: "#FFFFFF" },
  { name: "Goldfish Orange", code: "#FF9913", color: "#000000" },
  { name: "Honey Orange", code: "#FFBD31", color: "#000000" },
  { name: "Hunyadi Orange", code: "#E8AC41", color: "#000000" },
  { name: "Koi Orange", code: "#D15837", color: "#FFFFFF" },
  { name: "Light Orange", code: "#FED8B1", color: "#000000" },
  { name: "Light Copper Orange", code: "#F6CBA0", color: "#000000" },
  { name: "Pumpkin Orange", code: "#FF7518", color: "#FFFFFF" },
  { name: "Dark Topaz Orange", code: "#EABD8C", color: "#000000" },
  { name: "Mahogany Orange", code: "#C04000", color: "#FFFFFF" },
  { name: "Marigold Orange", code: "#EAA221", color: "#FFFFFF" },
  { name: "Melon Orange", code: "#DF9166", color: "#FFFFFF" },
  { name: "Mimosa Orange", code: "#FFCA4B", color: "#000000" },
  { name: "Neon Orange", code: "#FFAD00", color: "#000000" },
  { name: "Ochre Orange", code: "#C99700", color: "#FFFFFF" },
  { name: "Orange Pale Orange", code: "#FFDFBF", color: "#000000" },
  { name: "Orange Paper Orange", code: "#FEE8D6", color: "#000000" },
  { name: "Orange Spice Orange", code: "#D76B00", color: "#FFFFFF" },
  { name: "Outrageous Orange", code: "#FF6E4A", color: "#FFFFFF" },
  { name: "Pantone Orange", code: "#FE5000", color: "#FFFFFF" },
  { name: "Peach Orange", code: "#FFCC99", color: "#000000" },
  { name: "Pepper Orange", code: "#E77D22", color: "#FFFFFF" },
  { name: "Red Fox Orange", code: "#985629", color: "#FFFFFF" },
  { name: "Rumba Orange", code: "#F06631", color: "#FFFFFF" },
  { name: "Safety Orange", code: "#FF6700", color: "#FFFFFF" },
  { name: "Safflower Orange", code: "#FDAE44", color: "#000000" },
  { name: "Salamander Orange", code: "#F05E23", color: "#FFFFFF" },
  { name: "Salmon Orange", code: "#FF8066", color: "#000000" },
  { name: "Squash Orange", code: "#E89362", color: "#000000" },
  { name: "Sunrise Orange", code: "#E67451", color: "#FFFFFF" },
  { name: "Sunset Orange", code: "#FD5E53", color: "#FFFFFF" },
  { name: "Syracuse Orange", code: "#D44500", color: "#FFFFFF" },
  { name: "Tawny Orange", code: "#B25A38", color: "#FFFFFF" },
  { name: "Tiger Orange", code: "#F96815", color: "#FFFFFF" },
  { name: "Tiger Eye Orange", code: "#E08D3C", color: "#FFFFFF" },
  { name: "Topaz Orange", code: "#FFC87C", color: "#000000" },
  { name: "Tree Sap Orange", code: "#CC7711", color: "#FFFFFF" },
  { name: "Web Orange", code: "#FFA500", color: "#000000" },
  { name: "West Side Orange", code: "#FF9916", color: "#000000" },
  { name: "Wheat Orange", code: "#F5DEB3", color: "#000000" },
  { name: "Xanthaous Orange", code: "#F1B42F", color: "#000000" },
  { name: "Yam Orange", code: "#E17E45", color: "#FFFFFF" },
  { name: "Mecca Orange", code: "#BD5745", color: "#FFFFFF" },
  { name: "Lava Orange", code: "#F76806", color: "#FFFFFF" },
  { name: "Dutch Orange", code: "#FF9B00", color: "#000000" },
  { name: "Amber", code: "#FFC600", color: "#000000" },
  { name: "Aesthetic Orange", code: "#F4AB6A", color: "#000000" },
  { name: "Hot Orange", code: "#FF6E00", color: "#FFFFFF" },
  { name: "Glossy Orange", code: "#E78400", color: "#FFFFFF" },
  { name: "Pure Orange", code: "#FF8000", color: "#FFFFFF" },
  { name: "Rustic Orange", code: "#D78C3D", color: "#FFFFFF" },
  { name: "Baby Orange", code: "#FCBE85", color: "#000000" },
  { name: "Irish Orange", code: "#F5883F", color: "#FFFFFF" },
  { name: "Marmalade", code: "#D16002", color: "#FFFFFF" },
  { name: "Vintage Orange", code: "#C9995D", color: "#FFFFFF" },
  { name: "Rust", code: "#B7410E", color: "#FFFFFF" },
  { name: "India Saffron", code: "#FF9933", color: "#000000" },
  { name: "Atomic Tangerine", code: "#FF9966", color: "#000000" },
  { name: "Red Orange", code: "#B6481C", color: "#FFFFFF" },
  { name: "Willpower Orange", code: "#FD5602", color: "#FFFFFF" },
  { name: "Dusty Orange", code: "#E27A53", color: "#000000" },
  { name: "Spring Orange", code: "#FD963D", color: "#000000" },
  { name: "Greek Orange", code: "#E06E04", color: "#FFFFFF" },
  { name: "Calm Orange", code: "#FAB972", color: "#000000" },
  { name: "Faded Orange", code: "#CD946A", color: "#FFFFFF" },
  { name: "Luminous Bright Orange", code: "#FFB700", color: "#000000" },
];
