const shadesOfRed = [
  { name: "Imperial Red", code: "#ED2939" },
  { name: "Scarlet", code: "#FF2400" },
  { name: "Indian Red", code: "#CD5C5C" },
  { name: "Barn Red", code: "#7C0A02" },
  { name: "Chili Red", code: "#C21807" },
  { name: "Ruby", code: "#E0115F" },
  { name: "Maroon", code: "#800000" },
  { name: "Fire Brick", code: "#B22222" },
  { name: "Redwood", code: "#A45A52" },
  { name: "Carmine", code: "#960018" },
  { name: "Desire", code: "#EA3C53" },
  { name: "Vermilion", code: "#7E191B" },
  { name: "Raspberry", code: "#D21F3C" },
  { name: "Candy Apple", code: "#FF0800" },
  { name: "Persian", code: "#CA3433" },
  { name: "Hibiscus", code: "#B43757" },
  { name: "US Flag", code: "#BF0A30" },
  { name: "Ferrari", code: "#FF2800" },
  { name: "Sangria", code: "#5E1914" },
  { name: "Mahogany", code: "#420D09" },
  { name: "Burgundy", code: "#8D021F" },
  { name: "Crimson", code: "#B80F0A" },
  { name: "Rust", code: "#933A16" },
  { name: "Light Salmon", code: "#FFA07A" },
  { name: "Salmon", code: "#FA8072" },
  { name: "Dark Salmon", code: "#E9967A" },
  { name: "Light Coral", code: "#F08080" },
  { name: "Red", code: "#FF0000" },
  { name: "Dark Red", code: "#8B0000" },
  { name: "Tomato", code: "#FF6347" },
  { name: "Orange Red", code: "#FF4500" },
  { name: "Pale Violet Red", code: "#DB7093" },
  { name: "Light Brick", code: "#FB607F" },
  { name: "Brick", code: "#7E2811" },
  { name: "Prismatic Red", code: "#D03D33" },
  { name: "Prismatic Legacy", code: "#BA1607" },
  { name: "Prismatic Vermilion Renewal", code: "#CA0123" },
  { name: "Prismatic Reflection's Shade", code: "#FF3C28" },
  { name: "49ers Red", code: "#AA0000" },
  { name: "AZ Cardinals Red", code: "#BD2031" },
  { name: "Airbnb Red", code: "#FF5A5F" },
  { name: "Ajax Red", code: "#D2122E" },
  { name: "Alabama Crimson", code: "#9E1B32" },
  { name: "Alizarin Crimson", code: "#E32636" },
  { name: "Amaranth Red", code: "#F4364C" },
  { name: "Americal Rose", code: "#FF033E" },
  { name: "Angels Red", code: "#BA0021" },
  { name: "Almost Apricot Red", code: "#E5B39B" },
  { name: "Arsenal Red", code: "#DB0007" },
  { name: "Auburn Red", code: "#A52A2A" },
  { name: "BU Scarlet", code: "#CC0000" },
  { name: "Bills Red", code: "#C60C30" },
  { name: "Bittersweet Shimmer Red", code: "#BF4F51" },
  { name: "Blood Red", code: "#660000" },
  { name: "CG Red", code: "#E03C31" },
  { name: "Cadmium Red", code: "#E30022" },
  { name: "Cardinal Red", code: "#C41E3A" },
  { name: "Carnelian Red", code: "#B31B1B" },
  { name: "Cerise Red", code: "#DE3163" },
  { name: "Chiefs Red", code: "#E31837" },
  { name: "Chocolate Cosmos Red", code: "#58111A" },
  { name: "Cincinnati Red", code: "#C6011F" },
  { name: "Cinnabar Red", code: "#E44D2E" },
  { name: "Coke Red", code: "#F40009" },
  { name: "Coquelicot Red", code: "#FF3800" },
  { name: "Coral Red", code: "#FF7F50" },
  { name: "Cordovan Red", code: "#893F45" },
  { name: "Crayola Red", code: "#EE204D" },
  { name: "Electric Crimson", code: "#FF003F" },
  { name: "English Red", code: "#AB4B52" },
  { name: "Falcons Red", code: "#A71930" },
  { name: "Falu Red", code: "#801818" },
  { name: "Fire Engine Red", code: "#CE2029" },
  { name: "Flame Red", code: "#E25822" },
  { name: "Folly Red", code: "#FF004F" },
  { name: "French Puce Red", code: "#4E1609" },
  { name: "Fuchsia", code: "#FF00FF" },
  { name: "Fuzzy Wuzzy Red", code: "#CC6666" },
  { name: "Garnet Red", code: "#733635" },
  { name: "Harvard Crimson", code: "#A51C30" },
  { name: "Hollywood Cerise Red", code: "#F400A1" },
  { name: "Husker Red", code: "#E41C38" },
  { name: "Japanese Carmine", code: "#9D2933" },
  { name: "Jasper Red", code: "#D73B3E" },
  { name: "Jelly Bean Red", code: "#DA614E" },
  { name: "Kenyan Copper Red", code: "#7C1C05" },
  { name: "Lava Red", code: "#CF1020" },
  { name: "Liverpool Red", code: "#C8102E" },
  { name: "Lust Red", code: "#E62020" },
  { name: "MIT Red", code: "#A31F34" },
  { name: "Madder Red", code: "#A50021" },
  { name: "Pigment Magenta", code: "#FF0090" },
  { name: "Manchester United Red", code: "#DA291C" },
  { name: "Medium Violet Red", code: "#C71585" },
  { name: "Munsell Red", code: "#F2003C" },
  { name: "NCS Red", code: "#C40233" },
  { name: "Nationals Red", code: "#AB0003" },
  { name: "Oklahoma Crimson", code: "#841617" },
  { name: "Oxblood Red", code: "#800020" },
  { name: "Pastel Red", code: "#FF6961" },
  { name: "Penn Red", code: "#990000" },
  { name: "Persian Rose Red", code: "#FE28A2" },
  { name: "Phillies Red", code: "#E81828" },
  { name: "Pigment Red", code: "#ED1C24" },
  { name: "Pinterest Red", code: "#E60023" },
  { name: "Popstar Red", code: "#BE4F62" },
  { name: "Portland Orange Red", code: "#FF5A36" },
  { name: "Prune Red", code: "#701C1C" },
  { name: "Radical Red", code: "#FF355E" },
  { name: "Red Devil", code: "#860111" },
  { name: "Red Sox", code: "#BD3039" },
  { name: "Rose Red", code: "#C21E56" },
  { name: "Rosewood Red", code: "#65000B" },
  { name: "Rufous Red", code: "#A81C07" },
  { name: "Russet Red", code: "#80461B" },
  { name: "Rusty Red", code: "#DA2C43" },
  { name: "Sanguine Red", code: "#BC3F4A" },
  { name: "Spanish Red", code: "#E60026" },
  { name: "Tango Red", code: "#E4717A" },
  { name: "Tawny Red", code: "#CD5700" },
  { name: "Tea Rose Red", code: "#F88379" },
  { name: "Terracotta Red", code: "#E2725B" },
  { name: "Tractor Red", code: "#FD0E35" },
  { name: "Turkey Red", code: "#A91101" },
  { name: "Tuscan Red", code: "#7C3030" },
  { name: "Upsdell Red", code: "#AE2029" },
  { name: "Venetian Red", code: "#C80815" },
  { name: "Virgin Lust Red", code: "#E4181E" },
  { name: "WIne Red", code: "#722F37" },
  { name: "Light Red Ochre", code: "#E97451" },
  { name: "Medium Vermillion", code: "#D9603B" },
  { name: "UP Maroon", code: "#7B1113" },
  { name: "Outrageous Orange Red", code: "#FF6E4A" },
  { name: "Utah Crimson", code: "#D3003F" },
];

const shadesOfBlack = [
  { name: "Abbey", code: "#494F55" },
  { name: "Ash Grey", code: "#666362" },
  { name: "Asphalt", code: "#0C0404" },
  { name: "Black", code: "#000000" },
  { name: "Black Bean", code: "#3D0C02" },
  { name: "Black Cat", code: "#413839" },
  { name: "Black Cow", code: "#4C4646" },
  { name: "Black Eel", code: "#463E3F" },
  { name: "Black Olive", code: "#3B3C36" },
  { name: "Charcoal", code: "#36454F" },
  { name: "Charleston Green", code: "#232B2B" },
  { name: "Dark Jungle Green", code: "#1A2421" },
  { name: "Davy's Gray", code: "#555555" },
  { name: "Dim Gray", code: "#696969" },
  { name: "Ebony", code: "#555D50" },
  { name: "Eerie Black", code: "#1B1B1B" },
  { name: "Granite", code: "#676767" },
  { name: "Gray", code: "#808080" },
  { name: "Gray Cloud", code: "#B6B6B4" },
  { name: "Gray Wolf", code: "#504A4B" },
  { name: "Gunmetal", code: "#2C3539" },
  { name: "Iridium", code: "#3D3C3A" },
  { name: "Jet", code: "#343434" },
  { name: "Licorice", code: "#1A1110" },
  { name: "Midnight", code: "#2B1B17" },
  { name: "Night", code: "#0C090A" },
  { name: "Oil", code: "#3B3131" },
  { name: "Old Burgundy", code: "#43302E" },
  { name: "Onyx", code: "#353839" },
  { name: "Outer Space", code: "#414A4C" },
  { name: "Raisin Black", code: "#242124" },
  { name: "Smoky Black", code: "#100C08" },
  { name: "Taupe", code: "#483C32" },
  { name: "Vampire Gray", code: "#565051" },
  { name: "Black Leather Jacket", code: "#253529" },
  { name: "Cafe Americano", code: "#362819" },
  { name: "Blackberry", code: "#3A3A38" },
  { name: "Lamp Black", code: "#2E473B" },
  { name: "Army Uniform", code: "#353F3E" },
  { name: "Slate", code: "#26282A" },
  { name: "Pitch Black", code: "#27251F" },
  { name: "Spider", code: "#040200" },
  { name: "metal", code: "#0E0C0A" },
  { name: "Grease", code: "#080806" },
  { name: "Crow", code: "#0D0907" },
  { name: "Black Rock", code: "#010127" },
  { name: "Basalt Black", code: "#4D423E" },
  { name: "Neutral Black", code: "#0B0B0B" },
  { name: "Black Denim", code: "#191C27" },
  { name: "Vampire Black", code: "#0F0404" },
  { name: "Cool Black", code: "#151922" },
  { name: "Panda Black", code: "#3C4748" },
  { name: "Frost Black", code: "#191C20" },
  { name: "Ink Black(RAL)", code: "#212122" },
  { name: "Raven", code: "#050301" },
  { name: "leather", code: "#0B0705" },
  { name: "Sable", code: "#060606" },
  { name: "Power Black", code: "#0E0C01" },
  { name: "Soot", code: "#160D08" },
  { name: "Jade", code: "#000302" },
  { name: "True Black", code: "#0A0B0B" },
  { name: "Premium Black", code: "#100E09" },
  { name: "Obsidian", code: "#020403" },
  { name: "Black Grain", code: "#2C2C2A" },
  { name: "Black Magic", code: "#0B0510" },
  { name: "Iron Black", code: "#343432" },
  { name: "Rich Black(FOGRA29)", code: "#010B13" },
  { name: "Warm Black", code: "#004242" },
  { name: "Black Coral", code: "#54626F" },
  { name: "Black Shadows", code: "#BFAFB2" },
  { name: "Black Raspberry", code: "#451425" },
  { name: "Kombu Green", code: "#354230" },
  { name: "Zinnwaldite Brown", code: "#2C1608" },
  { name: "Dark Slate Gray", code: "#2F4F4F" },
  { name: "Dark Charcoal", code: "#333333" },
  { name: "Russian Violet", code: "#32174D" },
  { name: "Olive Drab #7", code: "#3C341F" },
  { name: "Dark Sienna", code: "#3C1414" },
  { name: "Alien Black", code: "#1A2228" },
  { name: "Black Chocolate", code: "#1B1811" },
  { name: "Blue Charcoal", code: "#262B2F" },
  { name: "Gothic Grape", code: "#120321" },
  { name: "Metropolis", code: "#1A1A1A" },
  { name: "Night Shadow", code: "#1C1C1C" },
  { name: "Off Black", code: "#595652" },
  { name: "Dark Raisin", code: "#1A0F0F" },
  { name: "Tea Bag", code: "#161311" },
  { name: "Electric Black", code: "#292929" },
  { name: "Tech Black", code: "#0D0E0E" },
  { name: "Dull Black", code: "#161616" },
  { name: "Dark Black", code: "#010203" },
  { name: "Natural Black", code: "#07000B" },
  { name: "Retro Black", code: "#1F201F" },
  { name: "Black Green(RAL)", code: "#303D3A" },
  { name: "Deep Black", code: "#050203" },
  { name: "Refresh Black", code: "#111212" },
  { name: "Rustic Black", code: "#1B1A16" },
  { name: "Rose Ebony", code: "#674846" },
  { name: "Liver", code: "#534B4F" },
  { name: "Purple Taupe", code: "#50404D" },
  { name: "Black Pearl", code: "#0E161A" },
  { name: "Black Russian", code: "#24252B" },
  { name: "Aesthetic Black", code: "#1C1C1E" },
  { name: "Signal Black(RAL)", code: "#2B2B2C" },
  { name: "Cafe Noir", code: "#4B3621" },
  { name: "Luxury Black", code: "#060D0D" },
  { name: "Bright Black", code: "#222024" },
  { name: "Black Blue(RAL)", code: "#1A1E28" },
  { name: "Glossy Black", code: "#252324" },
  { name: "Ivory Black", code: "#231F20" },
  { name: "Pastel Black", code: "#1D1C1A" },
  { name: "Fashion Black", code: "#060403" },
  { name: "Graphite Black(RAL)", code: "#27292B" },
  { name: "Black Gray", code: "#303234" },
  { name: "Black Hole", code: "#060605" },
  { name: "Kokushoku", code: "#171412" },
  { name: "Kurotobi", code: "#351E1C" },
  { name: "Void", code: "#010207" },
  { name: "Wet Suit", code: "#080706" },
  { name: "Yacht Club Black", code: "#222627" },
  { name: "Young Night", code: "#232323" },
  { name: "Blackstrap Molasses", code: "#2B2523" },
  { name: "Carbon Black", code: "#0C0A00" },
  { name: "Cynical Black", code: "#171717" },
  { name: "Black Plum", code: "#362B32" },
  { name: "Reversed Gray", code: "#080808" },
  { name: "Stout", code: "#0F0B0A" },
  { name: "Tornado Cloud", code: "#121213" },
  { name: "Walnut Hull", code: "#1B1813" },
  { name: "Tap Shoe", code: "#2A2B2D" },
  { name: "Woodsmoke", code: "#2B3230" },
  { name: "Black Red", code: "#3D2022" },
  { name: "Wind Cave", code: "#1F2024" },
  { name: "Heavy gray", code: "#050505" },
];

const shadesOfBlue = [
  { name: "Turquoise", code: "#40E0D0" },
  { name: "Celeste", code: "#B2FFFF" },
  { name: "Light Turquoise", code: "#AFEEEE" },
  { name: "Turquoise Blue", code: "#00FFEF" },
  { name: "Medium Turquoise", code: "#48D1CC" },
  { name: "Dark Turquoise", code: "#00CED1" },
  { name: "Bright Turquoise", code: "#08E8DE" },
  { name: "Powder Blue", code: "#B0E0E6" },
  { name: "Sky Blue", code: "#ADD8E6" },
  { name: "Electric Blue", code: "#7DF9FF" },
  { name: "Air Force Blue(RAF)", code: "#5D8AA8" },
  { name: "Air Force Blue(USAF)", code: "#00308F" },
  { name: "US Air Force Academy Blue", code: "#004F98" },
  { name: "Beau Blue", code: "#BCD4E6" },
  { name: "Baby Blue", code: "#89CFF0" },
  { name: "Baby Blue Eyes", code: "#A1CAF1" },
  { name: "Littile Boy Blue", code: "#6CA0DC" },
  { name: "Tiffany Blue", code: "#81D8D0" },
  { name: "Steel Blue", code: "#4682B4" },
  { name: "Carolina Blue", code: "#4B9CD3" },
  { name: "Turkish Blue", code: "#4F97A3" },
  { name: "Maya Blue", code: "#73C2FB" },
  { name: "Teal", code: "#008080" },
  { name: "Independence Blue", code: "#4C516D" },
  { name: "Cornflower Blue", code: "#6495ED" },
  { name: "Sapphire Blue", code: "#0F52BA" },
  { name: "Madium Sapphire", code: "#2D5DA1" },
  { name: "B'dazzled Blue", code: "#2E5894" },
  { name: "Blue Sapphire", code: "#126180" },
  { name: "Dark Sapphire", code: "#082567" },
  { name: "Azure", code: "#007FFF" },
  { name: "Egyptian Blue", code: "#1034A6" },
  { name: "Yale Blue", code: "#00356B" },
  { name: "Navy Blue", code: "#000080" },
  { name: "Prussian Blue", code: "#003153" },
  { name: "Space Cadet", code: "#1D2951" },
  { name: "Royal Blue", code: "#002366" },
  { name: "Queen Blue", code: "#436B95" },
  { name: "Imperial Blue", code: "#005A92" },
  { name: "Periwinkle", code: "#CCCCFF" },
  { name: "Morning Blue", code: "#8DA399" },
  { name: "Uranian Blue", code: "#AFDBF5" },
  { name: "Fluroscent Blue", code: "#15F4EE" },
  { name: "Ruddy Blue", code: "#76ABDF" },
  { name: "Admiral Blue", code: "#2C3863" },
  { name: "Aegean Blue", code: "#4E6E81" },
  { name: "Aero Blue", code: "#C9FFE5" },
  { name: "Air Superiority Blue", code: "#72A0C1" },
  { name: "Alice Blue", code: "#FOF8FF" },
  { name: "Aqua Blue", code: "#0AFFFF" },
  { name: "Aquamarine Blue", code: "#6BCAE2" },
  { name: "Arctic Blue", code: "#C6E6FB" },
  { name: "Argentina Blue", code: "#6CB4EE" },
  { name: "Astros Navy", code: "#002D62" },
  { name: "Bayern Blue", code: "#0066B2" },
  { name: "Berry Blue", code: "#4F86F7" },
  { name: "Blue", code: "#0000FF" },
  { name: "Blue Yonder", code: "#5072A7" },
  { name: "Bleu De France Blue", code: "#318CE7" },
  { name: "Blue-Gray", code: "#6699CC" },
  { name: "Boeing Blue", code: "#0039A6" },
  { name: "Braves Navy", code: "#13274F" },
  { name: "Brewers Blue", code: "#0A2351" },
  { name: "Byzantine Blue", code: "#3457D5" },
  { name: "Cambridge Blue", code: "#A3C1AD" },
  { name: "Capri Blue", code: "#00BFFF" },
  { name: "Cerulean Blue", code: "#2A52BE" },
  { name: "Chelsea Blue", code: "#034694" },
  { name: "Chlorine Blue", code: "#0CAFFF" },
  { name: "Cobalt Blue", code: "#0047AB" },
  { name: "College Navy", code: "#002244" },
  { name: "Columbia Blue", code: "#B9D9EB" },
  { name: "Crayola Blue", code: "#1F75FE" },
  { name: "Cyan Blue", code: "#00FFFF" },
  { name: "Dallas Cowboys Blue", code: "#041E42" },
  { name: "Dark Blue", code: "#00008B" },
  { name: "Delft Blue", code: "#1F305E" },
  { name: "Dell Blue", code: "#0076CE" },
  { name: "Denim Blue", code: "#1560BD" },
  { name: "Dodgers Blue", code: "#005A9C" },
  { name: "Dolphins Aqua", code: "#008E97" },
  { name: "Duck Blue", code: "#007791" },
  { name: "Duke Blue", code: "#012169" },
  { name: "Electric Indigo", code: "#6F00FF" },
  { name: "Everton Blue", code: "#003399" },
  { name: "Facebook Blue", code: "#1877F2" },
  { name: "Ford Blue", code: "#2C3968" },
  { name: "General Motors Blue", code: "#073980" },
  { name: "Glaucous Blue", code: "#6082B6" },
  { name: "IBM Blue", code: "#0530AD" },
  { name: "Ice Blue", code: "#99FFFF" },
  { name: "Indigo Blue", code: "#3F00FF" },
  { name: "Indigo Dye Blue", code: "#00416A" },
  { name: "Intel Blue", code: "#0071C5" },
  { name: "International Klein Blue", code: "#002FA7" },
  { name: "Iris Blue", code: "#5A4FCF" },
  { name: "KC Royals Blue", code: "#004687" },
  { name: "Lapis Blue", code: "#26619C" },
  { name: "Liberty Blue", code: "#545AA7" },
  { name: "Lowes Blue", code: "#004792" },
  { name: "Magic Blue", code: "#0077C0" },
  { name: "Majorelle Blue", code: "#6050DC" },
  { name: "Marian Blue", code: "#E1EBEE" },
  { name: "Mavericks Blue", code: "#00538C" },
  { name: "Medium Blue", code: "#0000CD" },
  { name: "Medium Slate Blue", code: "#7B68EE" },
  { name: "Millennium Blue", code: "#002244" },
  { name: "Munsell Blue", code: "#0093AF" },
  { name: "Neon Blue", code: "#4D4DFF" },
  { name: "Non-Photo Blue", code: "#A4DDED" },
  { name: "Ocean Blue", code: "#009DC4" },
  { name: "Oxford Blue", code: "#002147" },
  { name: "PSG Blue", code: "#004170" },
  { name: "Pacific Blue", code: "#1CA9C9" },
  { name: "Pantone Blue", code: "#0018A8" },
  { name: "Peacock Blue", code: "#005F69" },
  { name: "Penn Blue", code: "#011F5B" },
  { name: "Persian Blue", code: "#1C39BB" },
  { name: "Phthalo Blue", code: "#000F89" },
  { name: "Picotee Blue", code: "#2E2787" },
  { name: "Polynesian Blue", code: "#224C98" },
  { name: "Resolution Blue", code: "#002387" },
  { name: "Robin Egg Blue", code: "#00CCCC" },
  { name: "Savoy Blue", code: "#4B61D1" },
  { name: "Slate Blue", code: "#6A5ACD" },
  { name: "Spanish Blue", code: "#0070BB" },
  { name: "Sprush Blue", code: "#617178" },
  { name: "Stone Blue", code: "#819EA8" },
  { name: "Tottenham Navy", code: "#132257" },
  { name: "True Blue", code: "#2D68C4" },
  { name: "Tufts Blue", code: "#3E8EDE" },
  { name: "Twitter Blue", code: "#1DA1F2" },
  { name: "UCLA Blue", code: "#2774AE" },
  { name: "Ultramarine Blue", code: "#120A8F" },
  { name: "Voilet Blue", code: "#324AB2" },
  { name: "Visa Blue", code: "#1A1F71" },
  { name: "Vivid Sky Blue", code: "#00CCFF" },
  { name: "Warrios Blue", code: "#1D428A" },
  { name: "Yankees Blue", code: "#0C2340" },
  { name: "YInMn Blue", code: "#2E5090" },
  { name: "Steel Blue", code: "#4682B4" },
  { name: "Alaskan Blue", code: "#6DA9D2" },
  { name: "Tall Ships Blue", code: "#0E81B9" },
];

const shadesOfWhite = [
  { name: "White", code: "#FFFFFF" },
  { name: "Ghost White", code: "#F8F8FF" },
  { name: "White Smoke", code: "#F5F5F5" },
  { name: "Baby Powder", code: "#FEFEFA" },
  { name: "Snow", code: "#F5FEFD" },
  { name: "Ivory", code: "#FFFFF0" },
  { name: "Floral White", code: "#FFFAF0" },
  { name: "Seashell", code: "#FFF5EE" },
  { name: "Cornsilk", code: "#FFF8DC" },
  { name: "Old Lace", code: "#FDF5E6" },
  { name: "Cream", code: "#FFFDD0" },
  { name: "Beige", code: "#F5F5DC" },
  { name: "Parchment", code: "#F1E9D2" },
  { name: "Antique White", code: "#FAEBD7" },
  { name: "Champagne", code: "#F7E7CE" },
  { name: "Eggshell", code: "#F0EAD6" },
  { name: "Dutch White", code: "#EFDFBB" },
  { name: "Bone", code: "#E3DAC9" },
  { name: "Vanilla", code: "#F3E5AB" },
  { name: "Flax", code: "#EEDC82" },
  { name: "Navajo White", code: "#FFDEAD" },
  { name: "Alabaster", code: "#EDEAE0" },
  { name: "Chiffon", code: "#FFFACD" },
  { name: "Unresolved Problem", code: "#F3F2ED" },
  { name: "Old Wood", code: "#F0EEE4" },
  { name: "Rose White", code: "#FFFAFA" },
  { name: "Vista White", code: "#FDFCFA" },
  { name: "Link White", code: "#ECF3F9" },
  { name: "Spring", code: "#F3F0E8" },
  { name: "Snow Drift", code: "#F8FBF8" },
  { name: "Peppermint", code: "#F1F9EC" },
  { name: "Merino", code: "#F2EBDD" },
  { name: "Half and Half", code: "#FFFFE4" },
  { name: "Island Spice", code: "#FFFCEC" },
  { name: "Soft Peach", code: "#F6F1F4" },
  { name: "Harp", code: "#EBF5F0" },
  { name: "Titan White", code: "#EEEEFF" },
  { name: "Audience Anger", code: "#EAF4FC" },
  { name: "Orange White", code: "#F8F9F5" },
  { name: "Cough Mixture", code: "#F6F4F1" },
  { name: "Albescent White", code: "#F3DECA" },
  { name: "Coconut", code: "#FFF1E6" },
  { name: "Pink Salt", code: "#F8EEEC" },
  { name: "Frost", code: "#FCFBFC" },
  { name: "Linen", code: "#F3EAD3" },
  { name: "Rice", code: "#FAF5EF" },
  { name: "Daisy", code: "#FAFAFA" },
  { name: "Powder", code: "#FBFCFA" },
  { name: "Pearl", code: "#FBFCF8" },
  { name: "Paris White", code: "#C2D8D3" },
  { name: "Cup Cake", code: "#EBF6F7" },
  { name: "White Dove", code: "#F0EFE7" },
  { name: "White Whisper", code: "#EAE8E1" },
  { name: "Lexicon", code: "#E7EAEA" },
  { name: "Greek Villa", code: "#F0EBE3" },
  { name: "White Diamond", code: "#E7E8E2" },
  { name: "Decorator's White", code: "#ECEFEC" },
  { name: "Winter White", code: "#DFDFD5" },
  { name: "Spatial White", code: "#DEDDDB" },
  { name: "Hog Bristle Quarter", code: "#EBE4D8" },
  { name: "Simply White", code: "#EFEDE3" },
  { name: "Oyster White", code: "#E3DFD2" },
  { name: "White On White", code: "#EDEFEF" },
  { name: "Lexicon Quarter", code: "#F2F2F1" },
  { name: "Alice Blue", code: "#F0F8FF" },
  { name: "Honeydew", code: "#F0FFF0" },
  { name: "Mint Cream", code: "#F5FFFA" },
  { name: "Milk", code: "#FDFFF5" },
  { name: "Pomelo White", code: "#F9FFE3" },
  { name: "Anti-Flash White", code: "#F2F3F4" },
  { name: "Magnolia", code: "#F8F4FF" },
  { name: "Azure", code: "#F0FFFF" },
  { name: "Huntington White", code: "#F1F0E5" },
  { name: "Acadia White", code: "#F4EFE3" },
  { name: "Gainsboro", code: "#DCDCDC" },
  { name: "Mercury", code: "#E7E7E7" },
  { name: "Lavender Blush", code: "#FFF0F5" },
  { name: "Isabelline", code: "#F4F0EC" },
  { name: "Bubbles", code: "#E7FEFF" },
  { name: "Glitter", code: "#E6E8FA" },
  { name: "Platinum", code: "#E5E4E2" },
  { name: "Cosmic Latte", code: "#FFF8E7" },
  { name: "Blanched Almond", code: "#FFEBCD" },
  { name: "Light Yellow", code: "#FFFFE0" },
  { name: "Natural White", code: "#EEECE6" },
  { name: "Vivid White", code: "#F8F8F4" },
  { name: "White Wisp", code: "#E9E9E4" },
  { name: "Azureish White", code: "#DBE9F4" },
  { name: "Timberwolf", code: "#DBD7D2" },
  { name: "Papaya Whip", code: "#FFEFD5" },
  { name: "Antique White USA", code: "#EEEAE1" },
  { name: "Cola", code: "#F9EDEB" },
  { name: "Atrium White", code: "#F1EEE4" },
  { name: "Cascading White", code: "#F7F5F6" },
  { name: "Cotton Ball", code: "#F2F7FD" },
  { name: "Photon White", code: "#F8F8E8" },
  { name: "White Heat", code: "#FDF9EF" },
  { name: "Whitewash", code: "#FEFFFC" },
  { name: "Shadow White", code: "#EEF1EA" },
  { name: "Abbey White", code: "#EBE5D0" },
  { name: "Acoustic White", code: "#EFECE1" },
  { name: "Aircraft White", code: "#EDF2F8" },
  { name: "Ceramic", code: "#FCFFF9" },
  { name: "Coconut Butter", code: "#F2EFE1" },
  { name: "Abstract White", code: "#EDE9DD" },
  { name: "Bright White", code: "#F4F5F0" },
  { name: "Broken White", code: "#EEEBE3" },
  { name: "Brilliant White", code: "#EDF1FE" },
  { name: "Commercial White", code: "#EDECE6" },
  { name: "Feather White", code: "#E7EAE5" },
  { name: "Swan White", code: "#FCFCFC" },
  { name: "Polar Bear", code: "#EAE9E0" },
  { name: "Paper White", code: "#F7FCFE" },
  { name: "Pacific Pearl", code: "#E8EAE6" },
  { name: "Night White", code: "#E1E1DD" },
  { name: "Delicate White", code: "#F1F2EE" },
  { name: "Cococnut White", code: "#E9EDF6" },
  { name: "Cake Batter", code: "#F0EDDB" },
  { name: "White Sand", code: "#ECE9E4" },
  { name: "Stone White", code: "#FBF6F0" },
  { name: "White Chocolate", code: "#EDE6D6" },
  { name: "Retro White", code: "#EDEAE2" },
];

const shadesOfPink = [
  { name: "Pink", code: "#F699CD" },
  { name: "Dust Rose", code: "#C9A9A6" },
  { name: "Millennial Pink", code: "#F3CFC6" },
  { name: "Pink Orange", code: "#F89880" },
  { name: "Thistle", code: "#D8BFD8" },
  { name: "Ballet Slipper", code: "#F79AC0" },
  { name: "Watermelon", code: "#FC6C85" },
  { name: "Flamingo", code: "#FC8EAC" },
  { name: "Coral", code: "#F88379" },
  { name: "Rose", code: "#F33A6A" },
  { name: "Salmon", code: "#FF9999" },
  { name: "Pastel Pink", code: "#FFD1DC" },
  { name: "Light Pink", code: "#FFB6C1" },
  { name: "Cherry Blossom", code: "#FFB7C5" },
  { name: "Bubblegum", code: "#FFC1CC" },
  { name: "Baby Pink", code: "#F4C2C2" },
  { name: "Dark Pink", code: "#E75480" },
  { name: "Bright Pink", code: "#FF007F" },
  { name: "Rouge", code: "#A94064" },
  { name: "Neon Pink", code: "#FF6EC7" },
  { name: "Blush", code: "#DE5D83" },
  { name: "Fuchsia", code: "#C154C1" },
  { name: "Mauve", code: "#E0B0FF" },
  { name: "Orchid", code: "#DA70D6" },
  { name: "Magenta", code: "#FF00FF" },
  { name: "Hot Pink", code: "#FF69B4" },
  { name: "Carnation", code: "#FFA6C9" },
  { name: "Tulip Pink", code: "#FF8E8E" },
  { name: "Tea Rose", code: "#F4C2C2" },
  { name: "Cotton Candy", code: "#FFBCD9" },
  { name: "Cameo Pink", code: "#EFBBCC" },
  { name: "French Pink", code: "#F64A8A" },
  { name: "Strawberry", code: "#E8888A" },
  { name: "Persian Pink", code: "#F77FBE" },
  { name: "New York Pink", code: "#DD8374" },
  { name: "Indian Red", code: "#CD5C5C" },
  { name: "Munsell Red", code: "#F2003C" },
  { name: "Cardinal", code: "#C41E3A" },
  { name: "Crayola Red", code: "#EE204D" },
  { name: "Crimson", code: "#DC143C" },
  { name: "Ruby", code: "#E0115F" },
  { name: "Redwood", code: "#A45A52" },
  { name: "Rusty Red", code: "#DA2C43" },
  { name: "Amaranth", code: "#E52B50" },
  { name: "Bright Maroon", code: "#C32148" },
  { name: "Burnt Sienna", code: "#E97471" },
  { name: "Candy Pink", code: "#E4717A" },
  { name: "Cherry Pink", code: "#DE3163" },
  { name: "Chestnut", code: "#CD5C5C" },
  { name: "Dark Coral", code: "#CD5B45" },
  { name: "Dark Pastel Red", code: "#C23B22" },
  { name: "Dark Terra Cotta", code: "#CC4E5C" },
  { name: "Dark Salmon", code: "#E9967A" },
  { name: "Lemonade", code: "#F2DBE7" },
  { name: "Peach", code: "#FAD1AF" },
  { name: "Crepe", code: "#F89883" },
  { name: "Piggy Pink", code: "#FDDDE6" },
  { name: "Deep Pink", code: "#FF1493" },
  { name: "Dust Storm", code: "#E5CCC9" },
  { name: "Nadeshiko Pink", code: "#F6ADC6" },
  { name: "Rose Quartz", code: "#AA98A9" },
  { name: "Wild Strawberry", code: "#FF43A4" },
  { name: "Razzmatazz", code: "#E3256B" },
  { name: "Rose Taupe", code: "#905D5D" },
  { name: "Rubine Red", code: "#D10056" },
  { name: "Hollywood Cerise", code: "#F400A1" },
  { name: "Mexican Pink", code: "#E4007C" },
  { name: "Steel Pink", code: "#CC3366" },
  { name: "Rose Gold", code: "#B76E79" },
  { name: "Rose Bonbon", code: "#F9429E" },
  { name: "Barbie Pink", code: "#E0218A" },
  { name: "Mulberry", code: "C54B8C" },
  { name: "Razzle Dazzle Rose", code: "#FF33CC" },
  { name: "Fandango", code: "#B53389" },
  { name: "Puce", code: "#CC8899" },
  { name: "Old Rose", code: "#C08081" },
  { name: "Rosewood", code: "#9E4244" },
  { name: "Taffy", code: "#FA86C4" },
  { name: "Turkish Rose", code: "#B57281" },
  { name: "Punch", code: "#F25278" },
  { name: "Paradise Pink", code: "#E63E62" },
  { name: "Raspberry Rose", code: "#B3446C" },
  { name: "Light Crimson", code: "#F56991" },
  { name: "Pink Sherbet", code: "#F78FA7" },
  { name: "Tickle me Pink", code: "#FC89AC" },
  { name: "Thulian Pink", code: "#DE6FA1" },
  { name: "Brilliant Rose", code: "#FF55A3" },
  { name: "Lace", code: "#FFD8F0" },
  { name: "Smitten", code: "#C84186" },
  { name: "Your", code: "#FFC0C0" },
  { name: "Careys", code: "#D8A8A8" },
  { name: "Oyster", code: "#F0D8D8" },
  { name: "Shimmering Blush", code: "#D98695" },
  { name: "Sea", code: "#F09090" },
  { name: "Brink", code: "#FF6090" },
  { name: "Hippie", code: "#A84860" },
  { name: "Light Deep Pink", code: "#FF5CCD" },
  { name: "Wild Orchid", code: "#D470A2" },
  { name: "Cerise Pink", code: "#EC3B83" },
  { name: "Shocking Pink", code: "#FC0FC0" },
  { name: "Hit", code: "#FFA878" },
  { name: "lady", code: "#F0C0A8" },
  { name: "Neon Fuchsia", code: "#FE4164" },
  { name: "Ultra Pink", code: "#FF6FFF" },
  { name: "Schauss Pink", code: "#FF91AF" },
  { name: "Ruddy Pink", code: "#E18E96" },
  { name: "Pink Pearl", code: "#E7ACCF" },
  { name: "lavender Rose", code: "#FBA0E3" },
  { name: "Shampoo", code: "#FFCFF1" },
  { name: "Spanish Pink", code: "#F7BFBE" },
  { name: "Valentine Pink", code: "#E6A6BE" },
  { name: "Silvery Pink", code: "#DCB5B4" },
  { name: "Melon", code: "#F7BCAC" },
  { name: "Milano", code: "#D95D67" },
  { name: "Sweet Pink", code: "#EE918D" },
  { name: "Knockout Pink", code: "#FF3EA5" },
  { name: "Grapefruit Pink", code: "#E0707C" },
  { name: "Champagne Pink", code: "#F6E1D3" },
  { name: "Lip Pink", code: "#DBAC98" },
  { name: "Passion Pink", code: "#CE74A7" },
  { name: "Nude Pink", code: "#DDC0B4" },
  { name: "Rosy Pink", code: "#FF66CC" },
  { name: "Gold Pink", code: "#E6C7C2" },
  { name: "Misty Rose", code: "#FFE4E1" },
  { name: "Mauvelous", code: "#EF98AA" },
  { name: "Light Blush", code: "#F1ABB9" },
  { name: "Copper Rose", code: "#996666" },
  { name: "Raspberry Glace", code: "#915F6D" },
  { name: "Debian Red", code: "#D70A53" },
  { name: "Ruber", code: "#CE4676" },
  { name: "Vanilla Ice", code: "#F38FA9" },
  { name: "Light Hot Pink", code: "#FFB3DE" },
  { name: "Super Pink", code: "#CF6BA9" },
  { name: "China Rose", code: "#A8516E" },
  { name: "Deep Pruce", code: "#A95C68" },
  { name: "French Fuchsia", code: "#FD3F92" },
  { name: "Bisque", code: "#F2D2BD" },
];

const shadesOfGreen = [
  { name: "Green", code: "#008000" },
  { name: "Forest Green", code: "#0B6623" },
  { name: "Juniper", code: "#3A5311" },
  { name: "Parakeet", code: "#03C04A" },
  { name: "Olive", code: "#708238" },
  { name: "Basil", code: "#32612D" },
  { name: "Pickle", code: "#597D35" },
  { name: "Crocodile", code: "#607D3B" },
  { name: "Seaweed", code: "#354A21" },
  { name: "Aqua", code: "#00FFFF" },
  { name: "Aquamarine", code: "#7FFFD4" },
  { name: "Hunter Green", code: "#3F704D" },
  { name: "Seafoam Green", code: "#9FE2BF" },
  { name: "Artichoke Green", code: "#8F9779" },
  { name: "Jungle Green", code: "#29AB87" },
  { name: "Tropical Rainforest", code: "#00755E" },
  { name: "Amazon", code: "#3B7A57" },
  { name: "Deep Jungle Green", code: "#004B49" },
  { name: "Medium Jungle Green", code: "#1C352D" },
  { name: "Dark Jungle Green", code: "#1A2421" },
  { name: "Moss Green", code: "#8A9A5B" },
  { name: "Myrtle Green", code: "#317873" },
  { name: "Pine Green", code: "#01796F" },
  { name: "Persian Green", code: "#00A693" },
  { name: "Emerald Green", code: "#50C878" },
  { name: "Neon Green", code: "#39FF14" },
  { name: "Sacramento Green", code: "#043927" },
  { name: "Sea Green", code: "#2E8B57" },
  { name: "Ocean Green", code: "#48B591" },
  { name: "Sage Green", code: "#9DC183" },
  { name: "Lime Green", code: "#C7EA46" },
  { name: "Jade Green", code: "#00A86B" },
  { name: "Fern Green", code: "#4F7942" },
  { name: "Laurel Green", code: "#A9BA9D" },
  { name: "Mint Green", code: "#98FB98" },
  { name: "lincoln Green", code: "#478778" },
  { name: "Tea Green", code: "#D0F0C0" },
  { name: "Army Green", code: "#4B5320" },
  { name: "Kelly Green", code: "#4CBB17" },
  { name: "Russian Green", code: "#679267" },
  { name: "Paris Green", code: "#50C878" },
  { name: "Pakistan Green", code: "#006600" },
  { name: "Midnight Green", code: "#004953" },
  { name: "Indian Green", code: "#138808" },
  { name: "Hunter Green", code: "#355E3B" },
  { name: "Celadon", code: "#ACE1AF" },
  { name: "Avocado", code: "#568203" },
  { name: "Harlequin", code: "#3FFF00" },
  { name: "Spring", code: "#00F0A8" },
  { name: "Kaitoke", code: "#004830" },
  { name: "Screamin' Green", code: "#76FF7A" },
  { name: "Chateau", code: "#48A860" },
  { name: "Dark Moss Green", code: "#4A5D23" },
  { name: "Swamp", code: "#A8C090" },
  { name: "Mantis", code: "#74C365" },
  { name: "Fun", code: "#007848" },
  { name: "Pantone Artichoke Green", code: "#4B6F44" },
  { name: "Viridian", code: "#609078" },
  { name: "Reseda Green", code: "#6C7C59" },
  { name: "Chetwode", code: "#F0FFF0" },
  { name: "Shamrock Green", code: "#009E60" },
  { name: "Verdun", code: "#487800" },
  { name: "Castleton Green", code: "#00563B" },
  { name: "Gin", code: "#D8E4BC" },
  { name: "Citrine", code: "#E4D00A" },
  { name: "Granny Smith Apple", code: "#A8E4A0" },
  { name: "Bitter Lime", code: "#BFFF00" },
  { name: "Bright Mint", code: "#4FFFB0" },
  { name: "Bottle Green", code: "#0064AE" },
  { name: "Cadmium Green", code: "#006B3C" },
  { name: "Camouflage Green", code: "#78866B" },
  { name: "Pear", code: "#D1E231" },
  { name: "Dollar Bill", code: "#85BB65" },
  { name: "Inchworm", code: "#B2EC5D" },
  { name: "Asparagus", code: "#87A96B" },
  { name: "Caribbean Green", code: "#00CC99" },
  { name: "GO Green", code: "#00AB66" },
  { name: "Phthalo Green", code: "#123524" },
  { name: "Napier Green", code: "#2A8000" },
  { name: "Fledgrau", code: "#4D5D53" },
  { name: "Green-Yellow", code: "#ADFF2F" },
  { name: "Malachite", code: "#0BDA51" },
  { name: "Rifle Green", code: "#444C38" },
  { name: "Volt", code: "#CEFF00" },
  { name: "British Racing Green", code: "#004225" },
  { name: "Thyme", code: "#5EDC1F" },
  { name: "Chartreuse", code: "#7FFF00" },
  { name: "Corn Green", code: "#71A92C" },
  { name: "Shrek Green", code: "#C4D300" },
  { name: "Christmas Green", code: "#00873E" },
  { name: "Irish Green", code: "#009A44" },
  { name: "Road Sign Green", code: "#01735C" },
  { name: "Lightsaber Green", code: "#2FF924" },
  { name: "Girl Scout Green", code: "#00AE58" },
  { name: "Tennis Court Green", code: "#6C935C" },
  { name: "Spring Bud", code: "#A7FC00" },
  { name: "Chinese Green", code: "#D0DB61" },
  { name: "Arctic Lime", code: "#D0FF14" },
  { name: "Nyanza", code: "#E9FFDB" },
  { name: "Dark Lemon-Lime", code: "#76BA1B" },
  { name: "Crayola Yellow-Green", code: "#ACDF87" },
  { name: "Maximum Green", code: "#4C9A2A" },
  { name: "Vivid Lime Green", code: "#A4DE02" },
  { name: "Pistachio", code: "#93C572" },
  { name: "Medium Spring Green", code: "#00FA9A" },
  { name: "Sheen Green", code: "#8FD400" },
  { name: "La Salle Green", code: "#087830" },
  { name: "Spanish Viridian", code: "#007F5C" },
  { name: "Dartmouth Green", code: "#00703C" },
  { name: "Pine Needle", code: "#454D32" },
  { name: "Olive Drab", code: "#6B8E23" },
  { name: "Grass Green", code: "#7CFC00" },
  { name: "Xanadu", code: "#738678" },
  { name: "Dark Olive Green", code: "#556B2F" },
  { name: "Dark Sea Green", code: "#8FBC8F" },
  { name: "Green (Munsell)", code: "#00A877" },
  { name: "Mughal Green", code: "#306030" },
  { name: "John Deere Green", code: "#367C2B" },
  { name: "Office Green", code: "#008000" },
  { name: "Light Green", code: "#90EE90" },
  { name: "Dark Green", code: "#023020" },
  { name: "Limerick", code: "#9DC209" },
  { name: "Eucalyptus", code: "#5F8575" },
  { name: "Maximum Green Yellow", code: "#D9E650" },
  { name: "French Lime", code: "#9EFD38" },
  { name: "Medium Spring Bud", code: "#C9DC87" },
  { name: "UFO Green", code: "#3CD070" },
  { name: "Acid Green", code: "#B0BF1A" },
  { name: "Chlorophyll Green", code: "#4AFF00" },
  { name: "Green Lizard", code: "#A7F432" },
  { name: "Iguana Green", code: "#71BC78" },
  { name: "Kombu Green", code: "#354230" },
  { name: "Middle Green", code: "#4D8C57" },
  { name: "Paolo Veronese Green", code: "#009B7D" },
  { name: "Pullman Green", code: "#3B331C" },
  { name: "Green Screen", code: "#00B140" },
  { name: "Android Green", code: "#A4C639" },
  { name: "Bitter Lemon", code: "#CAE00D" },
  { name: "Wageninger Green", code: "#34B233" },
  { name: "Sap Green", code: "#507D2A" },
  { name: "Old Moss Green", code: "#867E36" },
  { name: "Slimy Green", code: "#299617" },
  { name: "Very Light Malachite Green", code: "#64E986" },
  { name: "Dark Spring Green", code: "#177245" },
  { name: "Guppie Green", code: "#00FF7F" },
  { name: "Apple Green", code: "#8DB600" },
  { name: "Deep Green", code: "#056608" },
  { name: "Hooker's Green", code: "#49796B" },
  { name: "Medium Sea Green", code: "#3CB371" },
  { name: "Turquoise Green", code: "#A0D6B4" },
];

const shadesOfGray = [
  { name: "Arsenic", code: "#3B444B" },
  { name: "Lead", code: "#3F3F4E" },
  { name: "Ash Gray", code: "#B2BEB5" },
  { name: "Battleship Gray", code: "#848482" },
  { name: "Black Coral", code: "#54626F" },
  { name: "Blue Gray", code: "#98AFC7" },
  { name: "Cadet Gray", code: "#91A3B0" },
  { name: "Carbon Gray", code: "#625D5D" },
  { name: "Charcoal", code: "#36454F" },
  { name: "Granola", code: "#D6B85A" },
  { name: "Oat", code: "#DFC98A" },
  { name: "Cinereous", code: "#98817B" },
  { name: "Cool Gray", code: "#9090C0" },
  { name: "Dark Gray", code: "#A9A9A9" },
  { name: "Davy's Gray", code: "#555555" },
  { name: "Deep Space Sparkle", code: "#4A646C" },
  { name: "Dim Gray", code: "#696969" },
  { name: "Gainsboro", code: "#DCDCDC" },
  { name: "Gray", code: "#808080" },
  { name: "Gray Cloud", code: "#B6B6B4" },
  { name: "Gray Dolphin", code: "#5C5858" },
  { name: "Gray Goose", code: "#D1D0CE" },
  { name: "Gray-Green", code: "#5E716A" },
  { name: "Gray Wolf", code: "#504A4B" },
  { name: "Glaucous", code: "#6082B6" },
  { name: "Gunmetal", code: "#2A3439" },
  { name: "Jet", code: "#343434" },
  { name: "Jet Gray", code: "#616D7E" },
  { name: "Light Gray", code: "#D3D3D3" },
  { name: "Light Slate Gray", code: "#6D7B8D" },
  { name: "Marengo", code: "#4C5866" },
  { name: "Medium Gray", code: "#BEBEBE" },
  { name: "Nevada", code: "#666A6D" },
  { name: "Nickel", code: "#727472" },
  { name: "Old Silver", code: "#848482" },
  { name: "Outer Space", code: "#414A4C" },
  { name: "Rocket Metallic", code: "#8A7F8D" },
  { name: "Scorpion", code: "#5E5E5E" },
  { name: "Silver", code: "#C0C0C0" },
  { name: "Silver Chalice", code: "#ACACAC" },
  { name: "Slate Blue", code: "#737CA1" },
  { name: "Slate Gray", code: "#657383" },
  { name: "Smoke", code: "#738276" },
  { name: "Smokey Gray", code: "#726E6D" },
  { name: "Sonic Gray", code: "#757575" },
  { name: "Spanish Gray", code: "#989898" },
  { name: "Stone Gray", code: "#928E85" },
  { name: "Stormcloud", code: "#4F666A" },
  { name: "Taupe Gray", code: "#8B8589" },
  { name: "Timberwolf", code: "#DBD7D2" },
  { name: "Payne's Gray", code: "#40404F" },
  { name: "Pink Gray", code: "#E7DADA" },
  { name: "Purple Gray", code: "#A7A6BA" },
  { name: "Rose Quartz", code: "#AA98A9" },
  { name: "Vampire Gray", code: "#565051" },
  { name: "Bright Gray", code: "#E8E9EB" },
  { name: "X11 Gray", code: "#BBBCB6" },
  { name: "Dark Silver", code: "#746D69" },
  { name: "Pastel Gray", code: "#CCCDC6" },
  { name: "Dusty Gray", code: "#B29CA2" },
  { name: "Misty Gray", code: "#BCC2C2" },
  { name: "White Gray", code: "#F2F3F5" },
  { name: "Vintage Gray", code: "#989692" },
  { name: "Gentle Gray", code: "#DADADA" },
  { name: "Zombie Gray", code: "#63645E" },
  { name: "Lavender Gray", code: "#C4C3D0" },
  { name: "Perfect Gray", code: "#A1A1A1" },
  { name: "Graphite Gray", code: "#4B4E53" },
  { name: "Rustic Gray", code: "#A6ABA5" },
  { name: "Echo", code: "#898D86" },
  { name: "Window Gray", code: "#989EA1" },
  { name: "Silk Gray", code: "#B6B3A8" },
  { name: "Light Gunmetal", code: "#344148" },
  { name: "Silver Pink", code: "#C4AEAD" },
  { name: "Matte Silver", code: "#A5A5A8" },
  { name: "Rhythm", code: "#777696" },
  { name: "Pure Silver", code: "#C3C7C7" },
  { name: "Best Gray", code: "#969892" },
  { name: "Agreeable Gray", code: "#D1CBC1" },
  { name: "Oxford Gray", code: "#8391A1" },
  { name: "Antique Pewter", code: "#808992" },
  { name: "Warm Gray", code: "#6E6259" },
  { name: "Sage Gray", code: "#B5BDA5" },
  { name: "Dull Gray", code: "#8B837E" },
  { name: "Rich Gray", code: "#1F2022" },
  { name: "Ice Gray", code: "#BEC3C6" },
  { name: "Gray CMYK", code: "#939598" },
  { name: "Solid Gray", code: "#979797" },
  { name: "Electric Gray", code: "#A5ADAD" },
  { name: "Templetion Gray", code: "#788787" },
  { name: "Chrome", code: "#DBE2E9" },
  { name: "Sea Gray", code: "#9AA2A4" },
  { name: "Glossy Gray", code: "#AFADA9" },
  { name: "Anvil Gray", code: "#6B6B6B" },
  { name: "Chameleon Gray", code: "#686965" },
  { name: "Cement Gray", code: "#858A7E" },
  { name: "Steel Gray", code: "#888B8D" },
  { name: "Dorian Gray", code: "#ACA79E" },
  { name: "Gun Smoke Gray", code: "#8A868E" },
  { name: "Camouflage Gray", code: "#545851" },
  { name: "Fashion Gray", code: "#8E8D8C" },
  { name: "Neutral Gray", code: "#898E8C" },
  { name: "Revere Pewter", code: "#CCC7B9" },
  { name: "Olive Gray", code: "#A09F8D" },
  { name: "Metallic Gray", code: "#A8A9AD" },
  { name: "French Gray", code: "#B4B19A" },
  { name: "Iron", code: "#A59C94" },
  { name: "Pale Smoke", code: "#CAD4D1" },
  { name: "Bone", code: "#D7D2CB" },
  { name: "Heather", code: "#9AA297" },
  { name: "True Silver", code: "#8A8D8F" },
  { name: "Power Gray", code: "#707272" },
  { name: "Storm Gray", code: "#B5BAB6" },
  { name: "Ultimate Gray", code: "#939597" },
  { name: "Rhino", code: "#B9BBB6" },
  { name: "Harbor Gray", code: "#C7C6C1" },
  { name: "Seal", code: "#818380" },
  { name: "Anchor", code: "#3E424B" },
  { name: "Abalone", code: "#D6CFC7" },
  { name: "Fossil", code: "#787276" },
  { name: "Mink", code: "#888078" },
  { name: "Trout", code: "#979788" },
  { name: "Thunder", code: "#BDB7AB" },
  { name: "Shades On", code: "#606060" },
  { name: "Lava", code: "#808588" },
  { name: "Stone Eagle", code: "#D8D9DA" },
  { name: "Ice Cube", code: "#E3E4E0" },
  { name: "Porpoise", code: "#4D4D5C" },
  { name: "Flint", code: "#7E7D9C" },
  { name: "Dove", code: "#7C6E7F" },
  { name: "Gray Owl", code: "#D5D5CD" },
  { name: "Coin", code: "#9897A9" },
  { name: "Fog", code: "#655967" },
  { name: "Shadow", code: "#373737" },
  { name: "Laid Back Gray", code: "#B4AFA9" },
];

const shadesOfPurple = [
  { name: "True Purple", code: "#6A0DAD" },
  { name: "Thistle", code: "#D8BFD8" },
  { name: "Plum", code: "#DDA0DD" },
  { name: "Violet", code: "#8F00FF" },
  { name: "Orchid", code: "#DA70D6" },
  { name: "Fuchsia", code: "#FF00FF" },
  { name: "Medium Orchid", code: "#BA55D3" },
  { name: "Medium Purple", code: "#9370DB" },
  { name: "Blue Violet", code: "#8A2BE2" },
  { name: "Dark Violet", code: "#9400D3" },
  { name: "Dark Orchid", code: "#9932CC" },
  { name: "Dark Magenta", code: "#8B008B" },
  { name: "Indigo", code: "#4B0082" },
  { name: "Veronica", code: "#A020F0" },
  { name: "Pale Purple", code: "#FAE6FA" },
  { name: "Mauve", code: "#D0B0FF" },
  { name: "Heliotrope", code: "#DF73FF" },
  { name: "Phlox", code: "#DF00FF" },
  { name: "Purple Pizzazz", code: "#FE4EDA" },
  { name: "Liserian Purple", code: "#DE6FA1" },
  { name: "Mulberry", code: "#C54B8C" },
  { name: "Pearly Purple", code: "#B768A2" },
  { name: "Purpureus", code: "#9A4EAE" },
  { name: "Northwestern Purple", code: "#4E2A84" },
  { name: "KSU Purple", code: "#512888" },
  { name: "Pomp and Power", code: "#86608E" },
  { name: "Mardi Gras", code: "#880085" },
  { name: "Eminence", code: "#6C3082" },
  { name: "Pansy Purple", code: "#78184A" },
  { name: "Palatinate", code: "#72246C" },
  { name: "Dark Purple", code: "#301934" },
  { name: "Byzantium", code: "#702963" },
  { name: "African Violet", code: "#B284BE" },
  { name: "Amethyst", code: "#9966CC" },
  { name: "Chinese Violet", code: "#856088" },
  { name: "English Violet", code: "#563C5C" },
  { name: "Russian Violet", code: "#32174D" },
  { name: "Fairy Tale", code: "#F2C1D1" },
  { name: "Fandango", code: "#B55338" },
  { name: "French Mauve", code: "#D473D4" },
  { name: "Affair", code: "#6F4685" },
  { name: "Boss's Jokes", code: "#B0306A" },
  { name: "iris", code: "#9867C5" },
  { name: "Long Distance", code: "#6F456E" },
  { name: "Prince Charming", code: "#493F5E" },
  { name: "Lipstick Stain", code: "#8E4785" },
  { name: "Pompadour", code: "#770058" },
  { name: "Grape Color", code: "#6F2DA8" },
  { name: "Wine", code: "#2C041C" },
  { name: "Pizza Edge", code: "#9A2CA0" },
  { name: "Tyrian Purple", code: "#66023C" },
  { name: "Ultra Violet", code: "#645394" },
  { name: "Studio", code: "#7851A9" },
  { name: "Electric Purple", code: "#BF00FF" },
  { name: "Eggplant", code: "#311432" },
  { name: "Periwinkle Purple", code: "#BE93E4" },
  { name: "Sangria", code: "#4D0F28" },
  { name: "Raisin", code: "#290916" },
  { name: "Mountbatten Pink", code: "#997A8D" },
  { name: "Fuchsia Blue", code: "#9C51B6" },
  { name: "Good Tax", code: "#C9A0FF" },
  { name: "Jam", code: "#67032F" },
  { name: "Ripe Plum", code: "#410056" },
  { name: "Heather", code: "#9E7BB5" },
  { name: "Magenta Purple", code: "#A32CC4" },
  { name: "Mountain's Majesty", code: "#9078C0" },
  { name: "Old Lavender", code: "#796878" },
  { name: "Rebecca Purple", code: "#663399" },
  { name: "Razzmic Berry Purple", code: "#8D4E85" },
  { name: "Wine Dregs Purple", code: "#673147" },
  { name: "Regalia Purple", code: "#522D80" },
  { name: "Twilight Lavender Purple", code: "#8A496B" },
  { name: "Traditional Purple", code: "#8E4585" },
  { name: "Spanish Violet Purple", code: "#4C2882" },
  { name: "Imperial Purple", code: "#602F6B" },
  { name: "Japanese Violet Purple", code: "#5B3256" },
  { name: "Munshell Purple", code: "#9F00C5" },
  { name: "Deep Ruby Purple", code: "#843F5B" },
  { name: "Purple Heart", code: "#7442C8" },
  { name: "Lavender Blush", code: "#FFF0F5" },
  { name: "Early Bird", code: "#CEA2FD" },
  { name: "Lilac", code: "#B65FCF" },
  { name: "Purple Taupe", code: "#50404D" },
  { name: "Cyber Grape Purple", code: "#58427C" },
  { name: "Kingfisher Daisy", code: "#653780" },
  { name: "Seance", code: "#61346B" },
  { name: "Lavender Gray", code: "#B6B5D8" },
  { name: "Hopbush", code: "#D05FAD" },
  { name: "Tacao", code: "#6F3096" },
  { name: "Brilliant Purple", code: "#D399E6" },
  { name: "Murasaki Purple", code: "#4F284B" },
  { name: "Blackish Purple", code: "#291E29" },
  { name: "Lovely Purple", code: "#7F38EC" },
  { name: "Vulgar Purple", code: "#3E2F84" },
  { name: "FedEx Purple", code: "#660099" },
  { name: "Carolina Plum", code: "#9B84A1" },
  { name: "Kalamata", code: "#705160" },
  { name: "Black Currant", code: "#540E32" },
  { name: "Purple 4", code: "#551A8B" },
  { name: "Strong Purple", code: "#876592" },
  { name: "Pale Purple", code: "#AA98A9" },
  { name: "Vivid Reddish Purple", code: "#870074" },
  { name: "Medium Purple 3", code: "#8968CD" },
  { name: "Medium Purple", code: "#D982B5" },
  { name: "Cardinal", code: "#8A244E" },
  { name: "Embassy Purple", code: "#3B343C" },
  { name: "Lakers Purple", code: "#552582" },
  { name: "Amaranth Purple", code: "#AB274F" },
  { name: "Purple Navy", code: "#4E5180" },
  { name: "Insolent Purple", code: "#682E3C" },
  { name: "Smyrna Purple", code: "#A2627A" },
  { name: "Little Princess", code: "#E9DCE5" },
  { name: "Aesthetic Purple", code: "#502380" },
  { name: "Kikyo-iru", code: "#5D3FCA" },
  { name: "Metallic Purple", code: "#520E7D" },
  { name: "Hot Purple", code: "#A420D0" },
  { name: "Faded Purple", code: "#795F80" },
  { name: "Mythical Purple", code: "#53277E" },
  { name: "Languid Lavender", code: "#D6CADD" },
  { name: "Mauveine", code: "#8D029B" },
  { name: "Blue Lilac", code: "#7B679A" },
  { name: "Dark Byzantium", code: "#5D3954" },
  { name: "Luxury People", code: "#743089" },
  { name: "Aztech Purple", code: "#893BFF" },
  { name: "Baltimore Ravens Purple", code: "#280353" },
  { name: "Deep Magenta", code: "#CC00CC" },
  { name: "Deep Purple", code: "#524F81" },
  { name: "Rustic Purple", code: "#593163" },
  { name: "Sunset Purple", code: "#A865B5" },
  { name: "Artist's Purple", code: "#C71585" },
  { name: "Dull Purple", code: "#9861A5" },
  { name: "Traffic Purple", code: "#913073" },
  { name: "Matte Purple", code: "#392A48" },
  { name: "Purple Violet", code: "#47243C" },
  { name: "Purple CMYK", code: "#6A317F" },
  { name: "Ocean Purple", code: "#6E2D91" },
  { name: "Shiny Purple", code: "#B941FF" },
  { name: "Autumn Purple", code: "#834468" },
];

const shadesOfYellow = [
  { name: "Sunshine Yellow", code: "#FFFD37" },
  { name: "Canary Yellow", code: "#FFEF00" },
  { name: "Lemon Yellow", code: "#FDFF00" },
  { name: "Goldenrod", code: "#DAA520" },
  { name: "Saffron", code: "#F4C430" },
  { name: "Hazelwood", code: "#C9BB8E" },
  { name: "Citrine", code: "#E4D00A" },
  { name: "Tombone", code: "#D2B55B" },
  { name: "Light Yellow", code: "#FFFFE0" },
  { name: "Lemon Chiffon", code: "#FFFACD" },
  { name: "Flax", code: "#EEDC82" },
  { name: "Light Goldenrod", code: "#FAFAD2" },
  { name: "Pale Goldenrod", code: "#EEE8AA" },
  { name: "Light Khaki", code: "#F0E68C" },
  { name: "Clover Lime", code: "#FCE883" },
  { name: "Xanthic", code: "#EEED09" },
  { name: "Royal Yellow", code: "#FADA5E" },
  { name: "Cream", code: "#FFFFCC" },
  { name: "Gold", code: "#FFD700" },
  { name: "Safety Yellow", code: "#EED202" },
  { name: "Laguna", code: "#F8E473" },
  { name: "Hunyadi Yellow", code: "#E8AC41" },
  { name: "Bright Yellow", code: "#FFFD01" },
  { name: "Greenish Yellow", code: "#EEEA62" },
  { name: "Neon Yellow", code: "#CFFF04" },
  { name: "Dark Yellow", code: "#D5B60A" },
  { name: "Sand", code: "#E2CA76" },
  { name: "Sunflower", code: "#FFDA03" },
  { name: "Bumblebee", code: "#FCE205" },
  { name: "Butter", code: "#FFFD74" },
  { name: "Yellow Tan", code: "#FFE36E" },
  { name: "Cyber Yellow", code: "#FFD300" },
  { name: "Banana", code: "#FFE135" },
  { name: "Tuscany", code: "#FCD12A" },
  { name: "Honey", code: "#FFC30B" },
  { name: "Dijon", code: "#C49102" },
  { name: "Amber", code: "#FFBF00" },
  { name: "Beige", code: "#F5F5DC" },
  { name: "Mustard", code: "#FEDC56" },
  { name: "Maximum Yellow", code: "#FAFA37" },
  { name: "Mellow Yellow", code: "#F8DE7E" },
  { name: "Unmellow Yellow", code: "#FFFF66" },
  { name: "Lemon Curry", code: "#CCA01D" },
  { name: "Moccasin", code: "#FFE4B5" },
  { name: "Orange Yellow", code: "#FFAD01" },
  { name: "Pastel Yellow", code: "#FFFE71" },
  { name: "Taxi Cab Yellow", code: "#FDB813" },
  { name: "Aureolin", code: "#FDEE00" },
  { name: "Electric Yellow", code: "#FFFF33" },
  { name: "Chartreuse", code: "#DFFF00" },
  { name: "Titanium Yellow", code: "#EEE600" },
  { name: "Mikado Yellow", code: "#FFC40C" },
  { name: "Fluorescent Yellow", code: "#CCFF00" },
  { name: "Arylide Yellow", code: "#E9D66B" },
  { name: "Indian Yellow", code: "#E3A857" },
  { name: "Durian Yellow", code: "#E1BD27" },
  { name: "Minion Yellow", code: "#F5E050" },
  { name: "Selective Yellow", code: "#FFBA00" },
  { name: "Laser Lemon", code: "#FEFE22" },
  { name: "Munsell Yellow", code: "#EFCC00" },
  { name: "Yellow Rose", code: "#FFF000" },
  { name: "Very Pale Yellow", code: "#FFFFBF" },
  { name: "Earth Yellow", code: "#E1A95F" },
  { name: "Yellow (Pantone)", code: "#FEDF00" },
  { name: "Tangerine Yellow", code: "#FFCC00" },
  { name: "Bronze Yellow", code: "#737000" },
  { name: "Psychedelic Yellow", code: "#FFF53D" },
  { name: "Maize Yellow (RAL)", code: "#DB9100" },
  { name: "Muted Yellow", code: "#E0D268" },
  { name: "Sulfur Yellow", code: "#E8DE35" },
  { name: "Yellow jasmine", code: "#CEB00D" },
  { name: "Dusty Yellow", code: "#D4CC9A" },
  { name: "Yolk Yellow (Pantone)", code: "#E2B051" },
  { name: "Light Chrome Yellow", code: "#FFCA37" },
  { name: "Cadmium Yellow lemon", code: "#FFF23E" },
  { name: "Vibrant Yellow", code: "#FFDA29" },
  { name: "Yellow CMYK", code: "#FFFF00" },
  { name: "Fire Yellow", code: "#FEDE17" },
  { name: "Buff Yellow", code: "#F1BF70" },
  { name: "Yellow Cream", code: "#EFDC75" },
  { name: "Empire Yellow", code: "#F7D000" },
  { name: "Zinc Yellow (RAL)", code: "#F2CB2E" },
  { name: "Signal Yellow", code: "#F2A900" },
  { name: "Matte Yellow", code: "#EDD94C" },
  { name: "Aesthetic Yellow", code: "#EFD033" },
  { name: "Rustic Yellow", code: "#E2C400" },
  { name: "Pale Yellow", code: "#FFFFA7" },
  { name: "Colza Yellow", code: "#EEB700" },
  { name: "Transparent Yellow", code: "#F4ECC2" },
  { name: "Blazing Yellow", code: "#FEE715" },
  { name: "Tender Yellow", code: "#EDEEB7" },
  { name: "Plae Lime Yellow", code: "#DFE69F" },
  { name: "Vintage Yellow", code: "#CBA92B" },
  { name: "Spectrum Yellow", code: "#FCE517" },
  { name: "Retro Yellow", code: "#F0E27B" },
  { name: "Old Yellow", code: "#C8AF55" },
  { name: "Chinese Yellow", code: "#FFB200" },
  { name: "Spanish Yellow", code: "#F9D73D" },
  { name: "Refresh Yellow", code: "#FFE992" },
  { name: "Sun Yellow (RAL)", code: "#EA9300" },
  { name: "Baby Yellow", code: "#FCEF91" },
  { name: "Dahila Yellow (RAL)", code: "#F39B1B" },
  { name: "Broom Yellow", code: "#DBA400" },
  { name: "Camouflage Yellow", code: "#978942" },
  { name: "Trust Yellow", code: "#EEBE15" },
  { name: "Warm Yellow", code: "#F4E98C" },
  { name: "Vivid Yellow", code: "#FFE302" },
  { name: "Turmeric", code: "#F0CA28" },
  { name: "Sunglow", code: "#FFCC33" },
  { name: "Light Saffron", code: "#FFE797" },
  { name: "Radioactive", code: "#FAE500" },
  { name: "Golden Poppy", code: "#FCC200" },
  { name: "Real Gold", code: "#E2BF36" },
  { name: "Glossy Gold", code: "#FAE481" },
  { name: "Snapchat Yellow", code: "#FFFC00" },
  { name: "Deep Chrome Yellow", code: "#FFB045" },
  { name: "Melon Yellow", code: "#FF9C00" },
  { name: "Bright Canary Yellow", code: "#FFE41E" },
  { name: "Deep Napoli Yellow", code: "#FFCF99" },
  { name: "Radiant Yellow", code: "#FC9E21" },
  { name: "Daffodil Yellow", code: "#E28D00" },
  { name: "Mineral Yellow", code: "#D39C43" },
  { name: "Relax Yellow", code: "#F3E496" },
  { name: "Rainbow Yellow", code: "#F5DE10" },
  { name: "Deep Yellow", code: "#EACE09" },
  { name: "Ochre Yellow", code: "#B5904B" },
  { name: "Dull Yellow", code: "#DECA57" },
  { name: "Hot Yellow", code: "#FFDA00" },
  { name: "Traffic Yellow", code: "#EFB700" },
  { name: "Yellow Orange", code: "#D56F00" },
  { name: "Olive Yellow", code: "#9D8F65" },
  { name: "Faded Yellow", code: "#ECE3A1" },
  { name: "Solid Yellow", code: "#FFE81C" },
  { name: "Golden Yellow", code: "#DD9F00" },
  { name: "Corn", code: "#FBEC5D" },
  { name: "Fawn", code: "#C8A951" },
  { name: "Dandelion", code: "#F0E130" },
  { name: "Icterine", code: "#FCF75E" },
  { name: "Sandstorm", code: "#ECD540" },
  { name: "Macaroon", code: "#F9E076" },
  { name: "Urobilin", code: "#E1AD21" },
  { name: "Satin Sheen Gold", code: "#CBA135" },
  { name: "School Bus Yellow", code: "#FFD800" },
  { name: "British Standard Yellow", code: "#EDC001" },
  { name: "Mimosa", code: "#FFF4BC" },
  { name: "Marigold", code: "#FCB810" },
  { name: "Shortbread", code: "#FBE790" },
  { name: "Buttermilk", code: "#FDEFB2" },
  { name: "Daisy Yellow", code: "#F8DC75" },
  { name: "Sepia", code: "#E3B778" },
  { name: "Biscotti", code: "#E3C565" },
  { name: "Parmesean", code: "#FDE992" },
  { name: "Sandcastle", code: "#DAC17C" },
  { name: "Sand", code: "#D8B863" },
  { name: "Egg Nog", code: "#FAE29C" },
  { name: "Suger Cookie", code: "#F3EAAF" },
];

const shadesOfBrown = [
  { name: "Almond", code: "#EFDECD" },
  { name: "Auburn", code: "#A52A2A" },
  { name: "Beaver", code: "#9F8170" },
  { name: "Beige", code: "#F5F5DC" },
  { name: "Bisque", code: "#FFE4C4" },
  { name: "Bistre", code: "#3D2B1F" },
  { name: "Bole", code: "#79443B" },
  { name: "Bone", code: "#E3DAC9" },
  { name: "Brass", code: "#B5A642" },
  { name: "Bronze", code: "#CD7F32" },
  { name: "Brunt Umber", code: "#8A3324" },
  { name: "Cafe Au Lait", code: "#A67B5B" },
  { name: "Cafe Noir", code: "#4B3621" },
  { name: "Champagne", code: "#FAD6A5" },
  { name: "Cinnamon", code: "#D2691E" },
  { name: "Coffee", code: "#6F4E37" },
  { name: "Deep Coffee", code: "#704242" },
  { name: "Copper", code: "#B87333" },
  { name: "Dark Brown", code: "#654321" },
  { name: "Taupe", code: "#483C32" },
  { name: "Tan", code: "#D2B48C" },
  { name: "Chestnut", code: "#CD5C5C" },
  { name: "Sand", code: "#F6D780" },
  { name: "Ecru", code: "#C2B280" },
  { name: "Fawn", code: "#E5AA70" },
  { name: "Ginger", code: "#B06500" },
  { name: "Golden Brown", code: "#996515" },
  { name: "Khaki", code: "#C3B091" },
  { name: "Mahogany", code: "#C04000" },
  { name: "Ochre", code: "#CC7722" },
  { name: "Light Brown", code: "#B5651D" },
  { name: "Saddle Brown", code: "#8B4513" },
  { name: "Wheat", code: "#F5DEB3" },
  { name: "Russet", code: "#80461B" },
  { name: "Rust", code: "#B7410E" },
  { name: "Sepia", code: "#704214" },
  { name: "Sienna", code: "#A0522D" },
  { name: "Antique Brass", code: "#CD9575" },
  { name: "Burlywood", code: "#DEB887" },
  { name: "Peru", code: "#CD853F" },
  { name: "Tumbleweed", code: "#DEAA88" },
  { name: "Dark Vanilla", code: "#D1BEA8" },
  { name: "Tuscan Brown", code: "#6F4E37" },
  { name: "Wood Brown", code: "#C19A6B" },
  { name: "Deer", code: "#BA8759" },
  { name: "Chamoisee", code: "#A0785A" },
  { name: "Dirt", code: "#9B7653" },
  { name: "Coconut", code: "#965A3E" },
  { name: "Windsor Tan", code: "#A75502" },
  { name: "Rufous", code: "#A81C07" },
  { name: "Acorn", code: "#D7A98C" },
  { name: "Ash Brown", code: "#98623C" },
  { name: "Ash Gray", code: "#C1B5A9" },
  { name: "Ash White", code: "#E9E4D4" },
  { name: "Baked Bread", code: "#DACBA9" },
  { name: "Baked Potato", code: "#B69E87" },
  { name: "Bamboo", code: "#E3DEC6" },
  { name: "Bark", code: "#996633" },
  { name: "Beeswax", code: "#E9D7AB" },
  { name: "Beige Linen", code: "#E2DAC6" },
  { name: "Birdseed", code: "#E2C28E" },
  { name: "Bitter Chocolate", code: "#9E5B40" },
  { name: "Brandy", code: "#DCB68A" },
  { name: "Brown Bear", code: "#7F6244" },
  { name: "Brown Beige", code: "#CC8833" },
  { name: "Brown Coffee", code: "#4A2C2A" },
  { name: "Brown Gray", code: "#8D8468" },
  { name: "Brown Metal", code: "#BBADA1" },
  { name: "Brown Red", code: "#922B05" },
  { name: "Brown Rust", code: "#AF593E" },
  { name: "Brown Stone", code: "#593C39" },
  { name: "Brown Sugar", code: "#A17249" },
  { name: "Brownie", code: "#964B00" },
  { name: "Brownish Gray", code: "#86775F" },
  { name: "Brownish Red", code: "#9E3623" },
  { name: "Burnt Almond", code: "#B0724A" },
  { name: "Burnt Henna", code: "#7E392F" },
  { name: "Butter Toast", code: "#D2AD84" },
  { name: "Buttercream", code: "#EFE0CD" },
  { name: "Butter Brown", code: "#F1EBDA" },
  { name: "Camel", code: "#C69F59" },
  { name: "Canadian Maple", code: "#CAB266" },
  { name: "Canvas Brown", code: "#BB8855" },
  { name: "Caramel", code: "#AF6F09" },
  { name: "Caramel Apple", code: "#B87A59" },
  { name: "Caramel Brown", code: "#BB8866" },
  { name: "Cashmere", code: "#D1B299" },
  { name: "Chai", code: "#B1832F" },
  { name: "Chamomile", code: "#DAC395" },
  { name: "Chicory", code: "#A78658" },
  { name: "Chocolate", code: "#7B3F00" },
  { name: "Cinnamon Toast", code: "#8D7D77" },
  { name: "Citrus Brown", code: "#D7C275" },
  { name: "Cotton", code: "#FAF4D4" },
  { name: "Croissant", code: "#C4AB86" },
  { name: "Dark Beige", code: "#AC9362" },
  { name: "Dark Chestnut", code: "#986960" },
  { name: "Dark Khaki", code: "#9B8F55" },
  { name: "Dark Sand", code: "#9F7D4F" },
  { name: "Dark Wood", code: "#855E42" },
  { name: "Deep Brown", code: "#410200" },
  { name: "Deep Taupe", code: "#7B6660" },
  { name: "Desert Gray", code: "#B8A487" },
  { name: "Dried Moss", code: "#CCB97E" },
  { name: "Dull Brown", code: "#876E4B" },
  { name: "Fall Harvest", code: "#A78A59" },
  { name: "Feather Brown", code: "#B8AD9E" },
  { name: "Firewood", code: "#CEBAA8" },
  { name: "Fortune Cookie", code: "#E0C5A1" },
  { name: "French Beige", code: "#A67B50" },
  { name: "Ginger Ale", code: "#C9A86A" },
  { name: "Golden Fog", code: "#F0EAD2" },
  { name: "Gray Brown", code: "#7F7053" },
  { name: "Grayish Brown", code: "#7A6A4F" },
  { name: "Hardwood", code: "#937A62" },
  { name: "Hawaiian Brown", code: "#99522C" },
  { name: "Heavy Brown", code: "#73624A" },
  { name: "Honey Brown", code: "#BA9238" },
  { name: "Iced Coffee", code: "#B18F6A" },
  { name: "Kobicha", code: "#6B4423" },
  { name: "Lace", code: "#EAE3D2" },
  { name: "Latte", code: "#C5A582" },
  { name: "Light Taupe", code: "#B38B6D" },
  { name: "Maple Sugar", code: "#C9A38D" },
  { name: "Maple Syrup", code: "#BB9351" },
  { name: "Mars Brown", code: "#AD6242" },
  { name: "Medium Brown", code: "#7F5112" },
  { name: "Mojava Desert", code: "#C7B595" },
];

const shadesOfOrange = [
  { name: "Dark Orange", code: "#FF8C00" },
  { name: "Vivid Orange", code: "#FF5E0E" },
  { name: "Orange-Red", code: "#FF4500" },
  { name: "Tomato", code: "#FF6347" },
  { name: "Metallic Orange", code: "#E26310" },
  { name: "Pumpkin", code: "#75761A" },
  { name: "Smashed Pumpkin", code: "#FD673A" },
  { name: "Yellow Orange", code: "#FFA836" },
  { name: "Carrot Orange", code: "#ED9121" },
  { name: "International Orange", code: "#FF4700" },
  { name: "Spanish Orange", code: "#F06105" },
  { name: "Tangarine", code: "#F78702" },
  { name: "Princeton Orange", code: "#FF8F00" },
  { name: "Orioles Orange", code: "#FB4F14" },
  { name: "Deep Saffron", code: "#FFA52C" },
  { name: "Alloy Orange", code: "#C35214" },
  { name: "Halloween Orange", code: "#EE5921" },
  { name: "Tangelo", code: "#FC4C02" },
  { name: "Gamboge", code: "#E89611" },
  { name: "Vermilion", code: "#D74826" },
  { name: "Medium Vermilion", code: "#CF5B2E" },
  { name: "Fulvous", code: "#E68000" },
  { name: "Pastel Orange", code: "#FEBA4F" },
  { name: "Flame", code: "#E34A27" },
  { name: "Philippine Orange", code: "#F26E01" },
  { name: "Beer Orange", code: "#F28F1C" },
  { name: "Chinese Orange", code: "#EB6841" },
  { name: "Jasper Orange", code: "#E89149" },
  { name: "Royal Orange", code: "#FF9944" },
  { name: "Coral", code: "#FF7F50" },
  { name: "Dark Coral", code: "#D75341" },
  { name: "Cadmium Orange", code: "#E6812F" },
  { name: "Dark Pastel Red", code: "#C34723" },
  { name: "Copper Red", code: "#D97448" },
  { name: "University Of Tennessee Orange", code: "#F77F00" },
  { name: "Rajah", code: "#FABA5F" },
  { name: "Mango Tango", code: "#FB8842" },
  { name: "Orange Peel", code: "#FF9F00" },
  { name: "Vivid Tangelo", code: "#EC7625" },
  { name: "Burnt Umber", code: "#8A3324" },
  { name: "Papaya Whip", code: "#FFF1D7" },
  { name: "Bittersweet", code: "#FE6F5E" },
  { name: "Persimmon", code: "#EC5800" },
  { name: "Persian Orange", code: "#D99058" },
  { name: "Terracotta", code: "#E2725B" },
  { name: "Apricot Orange", code: "#FBCEB1" },
  { name: "Bronze Orange", code: "#CD7F32" },
  { name: "Browns Orange", code: "#FF3C00" },
  { name: "Buff Orange", code: "#F2CA85" },
  { name: "Bumblebee Orange", code: "#FFC82A" },
  { name: "Burnt Orange", code: "#CC5500" },
  { name: "Butterscotch Orange", code: "#D99151" },
  { name: "Cheese Orange", code: "#FFA600" },
  { name: "Chocolate Orange", code: "#D2691E" },
  { name: "Cider Orange", code: "#D8A175" },
  { name: "Copper Orange", code: "#BB772E" },
  { name: "Crayola Orange", code: "#FF7538" },
  { name: "Desert Orange", code: "#ED8E4A" },
  { name: "Desert Sand Orange", code: "#EDC9AF" },
  { name: "Dragon Fire Orange", code: "#FD652D" },
  { name: "Dull Orange", code: "#DB804E" },
  { name: "Giants Orange", code: "#FE5A1D" },
  { name: "Ginger Orange", code: "#B06500" },
  { name: "Golden Gate Bridge Orange", code: "#CO362C" },
  { name: "Goldenrod Orange", code: "#DAA520" },
  { name: "Goldfish Orange", code: "#FF9913" },
  { name: "Honey Orange", code: "#FFBD31" },
  { name: "Hunyadi Orange", code: "#E8AC41" },
  { name: "Koi Orange", code: "#D15837" },
  { name: "Light Orange", code: "#FED8B1" },
  { name: "Light Copper Orange", code: "#F6CBA0" },
  { name: "Pumpkin Orange", code: "#FF7518" },
  { name: "Dark Topaz Orange", code: "#EABD8C" },
  { name: "Mahogany Orange", code: "#C04000" },
  { name: "Marigold Orange", code: "#EAA221" },
  { name: "Melon Orange", code: "#DF9166" },
  { name: "Mimosa Orange", code: "#FFCA4B" },
  { name: "Neon Orange", code: "#FFAD00" },
  { name: "Ochre Orange", code: "#C99700" },
  { name: "Orange Pale Orange", code: "#FFDFBF" },
  { name: "Orange Paper Orange", code: "#FEE8D6" },
  { name: "Orange Spice Orange", code: "#D76B00" },
  { name: "Outrageous Orange", code: "#FF6E4A" },
  { name: "Pantone Orange", code: "#FE5000" },
  { name: "Peach Orange", code: "#FFCC99" },
  { name: "Pepper Orange", code: "#E77D22" },
  { name: "Red Fox Orange", code: "#985629" },
  { name: "Rumba Orange", code: "#F06631" },
  { name: "Safety Orange", code: "#FF6700" },
  { name: "Safflower Orange", code: "#FDAE44" },
  { name: "Salamander Orange", code: "#F05E23" },
  { name: "Salmon Orange", code: "#FF8066" },
  { name: "Squash Orange", code: "#E89362" },
  { name: "Sunrise Orange", code: "#E67451" },
  { name: "Sunset Orange", code: "#FD5E53" },
  { name: "Syracuse Orange", code: "#D44500" },
  { name: "Tawny Orange", code: "#B25A38" },
  { name: "Tiger Orange", code: "#F96815" },
  { name: "Tiger Eye Orange", code: "#E08D3C" },
  { name: "Topaz Orange", code: "#FFC87C" },
  { name: "Tree Sap Orange", code: "#CC7711" },
  { name: "Web Orange", code: "#FFA500" },
  { name: "West Side Orange", code: "#FF9916" },
  { name: "Wheat Orange", code: "#F5DEB3" },
  { name: "Xanthaous Orange", code: "#F1B42F" },
  { name: "Yam Orange", code: "#E17E45" },
  { name: "Mecca Orange", code: "#BD5745" },
  { name: "Lava Orange", code: "#F76806" },
  { name: "Dutch Orange", code: "#FF9B00" },
  { name: "Amber", code: "#FFC600" },
  { name: "Aesthetic Orange", code: "#F4AB6A" },
  { name: "Hot Orange", code: "#FF6E00" },
  { name: "Glossy Orange", code: "#E78400" },
  { name: "Pure Orange", code: "#FF8000" },
  { name: "Rustic Orange", code: "#D78C3D" },
  { name: "Baby Orange", code: "#FCBE85" },
  { name: "Irish Orange", code: "#F5883F" },
  { name: "Marmalade", code: "#D16002" },
  { name: "Vintage Orange", code: "#C9995D" },
  { name: "Rust", code: "#B7410E" },
  { name: "Indian Saffron", code: "#FF9933" },
  { name: "Atomic Tangerine", code: "#FF9966" },
  { name: "Red Orange", code: "#B6481C" },
  { name: "Willpower Orange", code: "#FD5602" },
  { name: "Dusty Orange", code: "#E27A53" },
  { name: "Spring Orange", code: "#FD963D" },
  { name: "Greek Orange", code: "#E06E04" },
  { name: "Calm Orange", code: "#FAB972" },
  { name: "Faded Orange", code: "#CD946A" },
  { name: "Luminous Bright Orange", code: "#FFB700" },
];
